// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bulk.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addBulkChangeBooks = `-- name: AddBulkChangeBooks :exec
INSERT INTO bulk_change_books (bulk_change_id, position, book_id)
SELECT $1, b.ord::integer, b.id
FROM unnest($2::uuid[]) WITH ORDINALITY AS b (id, ord)
`

type AddBulkChangeBooksParams struct {
	BulkChangeID uuid.UUID
	BookIds      []uuid.UUID
}

func (q *Queries) AddBulkChangeBooks(ctx context.Context, arg AddBulkChangeBooksParams) error {
	_, err := q.db.Exec(ctx, addBulkChangeBooks, arg.BulkChangeID, arg.BookIds)
	return err
}

const createBulkChange = `-- name: CreateBulkChange :one
INSERT INTO bulk_changes (created_by, sees_all, action, change)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateBulkChangeParams struct {
	CreatedBy uuid.UUID
	SeesAll   bool
	Action    string
	Change    []byte
}

func (q *Queries) CreateBulkChange(ctx context.Context, arg CreateBulkChangeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createBulkChange,
		arg.CreatedBy,
		arg.SeesAll,
		arg.Action,
		arg.Change,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const finishBulkChange = `-- name: FinishBulkChange :exec
UPDATE bulk_changes SET finished_at = now() WHERE id = $1 AND finished_at IS NULL
`

func (q *Queries) FinishBulkChange(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, finishBulkChange, id)
	return err
}

const getBulkChange = `-- name: GetBulkChange :one
SELECT id, created_by, sees_all, action, change, created_at, finished_at FROM bulk_changes WHERE id = $1
`

func (q *Queries) GetBulkChange(ctx context.Context, id uuid.UUID) (BulkChange, error) {
	row := q.db.QueryRow(ctx, getBulkChange, id)
	var i BulkChange
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.SeesAll,
		&i.Action,
		&i.Change,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listBulkChangeBooks = `-- name: ListBulkChangeBooks :many
SELECT cb.book_id, cb.outcome, cb.message, cb.skipped, b.title
FROM bulk_change_books cb
JOIN books b ON b.id = cb.book_id
WHERE cb.bulk_change_id = $1
  AND b.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
ORDER BY cb.position
`

type ListBulkChangeBooksParams struct {
	ID      uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

type ListBulkChangeBooksRow struct {
	BookID  uuid.UUID
	Outcome *string
	Message *string
	Skipped []string
	Title   string
}

// The books of a change the viewer may still see: one they lost access to
// since is left out, as if it had never been in it.
func (q *Queries) ListBulkChangeBooks(ctx context.Context, arg ListBulkChangeBooksParams) ([]ListBulkChangeBooksRow, error) {
	rows, err := q.db.Query(ctx, listBulkChangeBooks, arg.ID, arg.Viewer, arg.SeesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBulkChangeBooksRow{}
	for rows.Next() {
		var i ListBulkChangeBooksRow
		if err := rows.Scan(
			&i.BookID,
			&i.Outcome,
			&i.Message,
			&i.Skipped,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBulkChangeBooks = `-- name: NextBulkChangeBooks :many
SELECT book_id
FROM bulk_change_books
WHERE bulk_change_id = $1 AND outcome IS NULL
ORDER BY position
LIMIT $2
`

type NextBulkChangeBooksParams struct {
	BulkChangeID uuid.UUID
	Limit        int32
}

// The books whose turn has not come yet, in the order they were chosen.
func (q *Queries) NextBulkChangeBooks(ctx context.Context, arg NextBulkChangeBooksParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, nextBulkChangeBooks, arg.BulkChangeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var book_id uuid.UUID
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBulkChangeOutcome = `-- name: SetBulkChangeOutcome :exec
UPDATE bulk_change_books
SET outcome = $3, message = $4, skipped = $5
WHERE bulk_change_id = $1 AND book_id = $2
`

type SetBulkChangeOutcomeParams struct {
	BulkChangeID uuid.UUID
	BookID       uuid.UUID
	Outcome      *string
	Message      *string
	Skipped      []string
}

func (q *Queries) SetBulkChangeOutcome(ctx context.Context, arg SetBulkChangeOutcomeParams) error {
	_, err := q.db.Exec(ctx, setBulkChangeOutcome,
		arg.BulkChangeID,
		arg.BookID,
		arg.Outcome,
		arg.Message,
		arg.Skipped,
	)
	return err
}
