// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalogue.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addBookContributor = `-- name: AddBookContributor :exec
INSERT INTO book_contributors (book_id, author_id, role, position)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddBookContributorParams struct {
	BookID   uuid.UUID
	AuthorID uuid.UUID
	Role     string
	Position int32
}

func (q *Queries) AddBookContributor(ctx context.Context, arg AddBookContributorParams) error {
	_, err := q.db.Exec(ctx, addBookContributor,
		arg.BookID,
		arg.AuthorID,
		arg.Role,
		arg.Position,
	)
	return err
}

const addBookIdentifier = `-- name: AddBookIdentifier :exec
INSERT INTO book_identifiers (book_id, file_id, type, value)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddBookIdentifierParams struct {
	BookID uuid.UUID
	FileID *uuid.UUID
	Type   string
	Value  string
}

func (q *Queries) AddBookIdentifier(ctx context.Context, arg AddBookIdentifierParams) error {
	_, err := q.db.Exec(ctx, addBookIdentifier,
		arg.BookID,
		arg.FileID,
		arg.Type,
		arg.Value,
	)
	return err
}

const addBookTag = `-- name: AddBookTag :exec
INSERT INTO book_tags (book_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddBookTagParams struct {
	BookID uuid.UUID
	TagID  uuid.UUID
}

func (q *Queries) AddBookTag(ctx context.Context, arg AddBookTagParams) error {
	_, err := q.db.Exec(ctx, addBookTag, arg.BookID, arg.TagID)
	return err
}

const countBookContributors = `-- name: CountBookContributors :one
SELECT count(*) FROM book_contributors WHERE book_id = $1
`

func (q *Queries) CountBookContributors(ctx context.Context, bookID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBookContributors, bookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookTags = `-- name: CountBookTags :one
SELECT count(*) FROM book_tags WHERE book_id = $1
`

func (q *Queries) CountBookTags(ctx context.Context, bookID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBookTags, bookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    library_id, title, sort_title, title_key, subtitle, description, language,
    published_on, published_precision, publisher_id, series_id, series_index, page_count,
    field_sources
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, library_id, title, sort_title, title_key, subtitle, description, language, published_on, published_precision, publisher_id, series_id, series_index, external_rating, page_count, cover_key, locked_fields, field_sources, merged_into_id, deleted_at, created_at, updated_at, primary_text_file_id, author_sort
`

type CreateBookParams struct {
	LibraryID          uuid.UUID
	Title              string
	SortTitle          string
	TitleKey           string
	Subtitle           *string
	Description        *string
	Language           *string
	PublishedOn        *time.Time
	PublishedPrecision *string
	PublisherID        *uuid.UUID
	SeriesID           *uuid.UUID
	SeriesIndex        *float64
	PageCount          *int32
	FieldSources       []byte
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.LibraryID,
		arg.Title,
		arg.SortTitle,
		arg.TitleKey,
		arg.Subtitle,
		arg.Description,
		arg.Language,
		arg.PublishedOn,
		arg.PublishedPrecision,
		arg.PublisherID,
		arg.SeriesID,
		arg.SeriesIndex,
		arg.PageCount,
		arg.FieldSources,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.SortTitle,
		&i.TitleKey,
		&i.Subtitle,
		&i.Description,
		&i.Language,
		&i.PublishedOn,
		&i.PublishedPrecision,
		&i.PublisherID,
		&i.SeriesID,
		&i.SeriesIndex,
		&i.ExternalRating,
		&i.PageCount,
		&i.CoverKey,
		&i.LockedFields,
		&i.FieldSources,
		&i.MergedIntoID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryTextFileID,
		&i.AuthorSort,
	)
	return i, err
}

const createBookFile = `-- name: CreateBookFile :one
INSERT INTO book_files (
    book_id, library_id, kind, format, rel_path, size_bytes, modified_at,
    sha256, original_sha256, part_index, uploaded_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8, $9, $10)
RETURNING id, book_id, library_id, kind, format, rel_path, size_bytes, modified_at, sha256, original_sha256, content_sha256, part_index, duration_ms, page_count, pages_estimated, has_text, drm, extract_state, extract_error, uploaded_by, missing_at, trashed_at, created_at, updated_at, track_number, disc_number
`

type CreateBookFileParams struct {
	BookID     uuid.UUID
	LibraryID  uuid.UUID
	Kind       string
	Format     string
	RelPath    string
	SizeBytes  int64
	ModifiedAt time.Time
	Sha256     []byte
	PartIndex  *int32
	UploadedBy *uuid.UUID
}

func (q *Queries) CreateBookFile(ctx context.Context, arg CreateBookFileParams) (BookFile, error) {
	row := q.db.QueryRow(ctx, createBookFile,
		arg.BookID,
		arg.LibraryID,
		arg.Kind,
		arg.Format,
		arg.RelPath,
		arg.SizeBytes,
		arg.ModifiedAt,
		arg.Sha256,
		arg.PartIndex,
		arg.UploadedBy,
	)
	var i BookFile
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.LibraryID,
		&i.Kind,
		&i.Format,
		&i.RelPath,
		&i.SizeBytes,
		&i.ModifiedAt,
		&i.Sha256,
		&i.OriginalSha256,
		&i.ContentSha256,
		&i.PartIndex,
		&i.DurationMs,
		&i.PageCount,
		&i.PagesEstimated,
		&i.HasText,
		&i.Drm,
		&i.ExtractState,
		&i.ExtractError,
		&i.UploadedBy,
		&i.MissingAt,
		&i.TrashedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackNumber,
		&i.DiscNumber,
	)
	return i, err
}

const deleteBookContributors = `-- name: DeleteBookContributors :exec
DELETE FROM book_contributors WHERE book_id = $1
`

func (q *Queries) DeleteBookContributors(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBookContributors, bookID)
	return err
}

const deleteBookOwnIdentifiers = `-- name: DeleteBookOwnIdentifiers :exec
DELETE FROM book_identifiers WHERE book_id = $1 AND file_id IS NULL
`

// The identifiers of the book itself; those its files carry stay.
func (q *Queries) DeleteBookOwnIdentifiers(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBookOwnIdentifiers, bookID)
	return err
}

const deleteBookTags = `-- name: DeleteBookTags :exec
DELETE FROM book_tags WHERE book_id = $1
`

func (q *Queries) DeleteBookTags(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBookTags, bookID)
	return err
}

const deleteFileIdentifiers = `-- name: DeleteFileIdentifiers :exec
DELETE FROM book_identifiers WHERE file_id = $1
`

func (q *Queries) DeleteFileIdentifiers(ctx context.Context, fileID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileIdentifiers, fileID)
	return err
}

const getPublisher = `-- name: GetPublisher :one
SELECT id, name, name_key FROM publishers WHERE id = $1
`

func (q *Queries) GetPublisher(ctx context.Context, id uuid.UUID) (Publisher, error) {
	row := q.db.QueryRow(ctx, getPublisher, id)
	var i Publisher
	err := row.Scan(&i.ID, &i.Name, &i.NameKey)
	return i, err
}

const getSeries = `-- name: GetSeries :one
SELECT id, name, name_key, created_at FROM series WHERE id = $1
`

func (q *Queries) GetSeries(ctx context.Context, id uuid.UUID) (Series, error) {
	row := q.db.QueryRow(ctx, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.CreatedAt,
	)
	return i, err
}

const getVisibleBook = `-- name: GetVisibleBook :one
SELECT b.id, b.library_id, b.title, b.sort_title, b.title_key, b.subtitle, b.description, b.language, b.published_on, b.published_precision, b.publisher_id, b.series_id, b.series_index, b.external_rating, b.page_count, b.cover_key, b.locked_fields, b.field_sources, b.merged_into_id, b.deleted_at, b.created_at, b.updated_at, b.primary_text_file_id, b.author_sort
FROM books b
WHERE b.id = $1
  AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
`

type GetVisibleBookParams struct {
	ID      uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

// A book the viewer may see. A book that lost a merge or was deleted is not
// a book any more.
func (q *Queries) GetVisibleBook(ctx context.Context, arg GetVisibleBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, getVisibleBook, arg.ID, arg.Viewer, arg.SeesAll)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.SortTitle,
		&i.TitleKey,
		&i.Subtitle,
		&i.Description,
		&i.Language,
		&i.PublishedOn,
		&i.PublishedPrecision,
		&i.PublisherID,
		&i.SeriesID,
		&i.SeriesIndex,
		&i.ExternalRating,
		&i.PageCount,
		&i.CoverKey,
		&i.LockedFields,
		&i.FieldSources,
		&i.MergedIntoID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryTextFileID,
		&i.AuthorSort,
	)
	return i, err
}

const getVisibleBookCover = `-- name: GetVisibleBookCover :one
SELECT b.cover_key
FROM books b
WHERE b.id = $1
  AND b.deleted_at IS NULL
  AND b.cover_key IS NOT NULL
  AND b.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
`

type GetVisibleBookCoverParams struct {
	ID      uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

// The cover of a book the viewer may see; no row for a book that is hidden,
// gone, or has none.
func (q *Queries) GetVisibleBookCover(ctx context.Context, arg GetVisibleBookCoverParams) (*string, error) {
	row := q.db.QueryRow(ctx, getVisibleBookCover, arg.ID, arg.Viewer, arg.SeesAll)
	var cover_key *string
	err := row.Scan(&cover_key)
	return cover_key, err
}

const getVisibleFile = `-- name: GetVisibleFile :one
SELECT f.id, f.book_id, f.format, f.rel_path, f.sha256, f.missing_at, l.root_path
FROM book_files f
JOIN books b ON b.id = f.book_id
JOIN libraries l ON l.id = f.library_id
WHERE f.id = $1
  AND f.trashed_at IS NULL
  AND b.deleted_at IS NULL
  AND f.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
`

type GetVisibleFileParams struct {
	ID      uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

type GetVisibleFileRow struct {
	ID        uuid.UUID
	BookID    uuid.UUID
	Format    string
	RelPath   string
	Sha256    []byte
	MissingAt *time.Time
	RootPath  string
}

// A file of a book the viewer may see, with where it lies.
func (q *Queries) GetVisibleFile(ctx context.Context, arg GetVisibleFileParams) (GetVisibleFileRow, error) {
	row := q.db.QueryRow(ctx, getVisibleFile, arg.ID, arg.Viewer, arg.SeesAll)
	var i GetVisibleFileRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Format,
		&i.RelPath,
		&i.Sha256,
		&i.MissingAt,
		&i.RootPath,
	)
	return i, err
}

const listBookContributors = `-- name: ListBookContributors :many
SELECT a.id, a.name, a.sort_name, c.role, c.position
FROM book_contributors c
JOIN authors a ON a.id = c.author_id
WHERE c.book_id = $1
ORDER BY c.position, a.sort_name
`

type ListBookContributorsRow struct {
	ID       uuid.UUID
	Name     string
	SortName string
	Role     string
	Position int32
}

func (q *Queries) ListBookContributors(ctx context.Context, bookID uuid.UUID) ([]ListBookContributorsRow, error) {
	rows, err := q.db.Query(ctx, listBookContributors, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookContributorsRow{}
	for rows.Next() {
		var i ListBookContributorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortName,
			&i.Role,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookFiles = `-- name: ListBookFiles :many
SELECT id, book_id, library_id, kind, format, rel_path, size_bytes, modified_at, sha256, original_sha256, content_sha256, part_index, duration_ms, page_count, pages_estimated, has_text, drm, extract_state, extract_error, uploaded_by, missing_at, trashed_at, created_at, updated_at, track_number, disc_number FROM book_files
WHERE book_id = $1 AND trashed_at IS NULL
ORDER BY kind, part_index NULLS FIRST, rel_path
`

func (q *Queries) ListBookFiles(ctx context.Context, bookID uuid.UUID) ([]BookFile, error) {
	rows, err := q.db.Query(ctx, listBookFiles, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookFile{}
	for rows.Next() {
		var i BookFile
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.LibraryID,
			&i.Kind,
			&i.Format,
			&i.RelPath,
			&i.SizeBytes,
			&i.ModifiedAt,
			&i.Sha256,
			&i.OriginalSha256,
			&i.ContentSha256,
			&i.PartIndex,
			&i.DurationMs,
			&i.PageCount,
			&i.PagesEstimated,
			&i.HasText,
			&i.Drm,
			&i.ExtractState,
			&i.ExtractError,
			&i.UploadedBy,
			&i.MissingAt,
			&i.TrashedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrackNumber,
			&i.DiscNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookIdentifiers = `-- name: ListBookIdentifiers :many
SELECT id, file_id, type, value
FROM book_identifiers
WHERE book_id = $1
ORDER BY type, value
`

type ListBookIdentifiersRow struct {
	ID     uuid.UUID
	FileID *uuid.UUID
	Type   string
	Value  string
}

func (q *Queries) ListBookIdentifiers(ctx context.Context, bookID uuid.UUID) ([]ListBookIdentifiersRow, error) {
	rows, err := q.db.Query(ctx, listBookIdentifiers, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookIdentifiersRow{}
	for rows.Next() {
		var i ListBookIdentifiersRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.Type,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookTags = `-- name: ListBookTags :many
SELECT t.id, t.name
FROM book_tags bt
JOIN tags t ON t.id = bt.tag_id
WHERE bt.book_id = $1
ORDER BY t.name_key
`

type ListBookTagsRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListBookTags(ctx context.Context, bookID uuid.UUID) ([]ListBookTagsRow, error) {
	rows, err := q.db.Query(ctx, listBookTags, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookTagsRow{}
	for rows.Next() {
		var i ListBookTagsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBookOfFile = `-- name: LockBookOfFile :one
SELECT b.id, b.library_id, b.title, b.sort_title, b.title_key, b.subtitle, b.description, b.language, b.published_on, b.published_precision, b.publisher_id, b.series_id, b.series_index, b.external_rating, b.page_count, b.cover_key, b.locked_fields, b.field_sources, b.merged_into_id, b.deleted_at, b.created_at, b.updated_at, b.primary_text_file_id, b.author_sort
FROM books b
JOIN book_files f ON f.book_id = b.id
WHERE f.id = $1
FOR UPDATE OF b
`

// Locked, because two files of one book may be read at the same time and
// both decide what the book is called.
func (q *Queries) LockBookOfFile(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, lockBookOfFile, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.SortTitle,
		&i.TitleKey,
		&i.Subtitle,
		&i.Description,
		&i.Language,
		&i.PublishedOn,
		&i.PublishedPrecision,
		&i.PublisherID,
		&i.SeriesID,
		&i.SeriesIndex,
		&i.ExternalRating,
		&i.PageCount,
		&i.CoverKey,
		&i.LockedFields,
		&i.FieldSources,
		&i.MergedIntoID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryTextFileID,
		&i.AuthorSort,
	)
	return i, err
}

const lockVisibleBook = `-- name: LockVisibleBook :one
SELECT b.id, b.library_id, b.title, b.sort_title, b.title_key, b.subtitle, b.description, b.language, b.published_on, b.published_precision, b.publisher_id, b.series_id, b.series_index, b.external_rating, b.page_count, b.cover_key, b.locked_fields, b.field_sources, b.merged_into_id, b.deleted_at, b.created_at, b.updated_at, b.primary_text_file_id, b.author_sort
FROM books b
WHERE b.id = $1
  AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
FOR UPDATE
`

type LockVisibleBookParams struct {
	ID      uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

// A book the viewer may see, locked for a person's edit: a file read at the
// same time must not write over it half done.
func (q *Queries) LockVisibleBook(ctx context.Context, arg LockVisibleBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, lockVisibleBook, arg.ID, arg.Viewer, arg.SeesAll)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Title,
		&i.SortTitle,
		&i.TitleKey,
		&i.Subtitle,
		&i.Description,
		&i.Language,
		&i.PublishedOn,
		&i.PublishedPrecision,
		&i.PublisherID,
		&i.SeriesID,
		&i.SeriesIndex,
		&i.ExternalRating,
		&i.PageCount,
		&i.CoverKey,
		&i.LockedFields,
		&i.FieldSources,
		&i.MergedIntoID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryTextFileID,
		&i.AuthorSort,
	)
	return i, err
}

const refreshAuthorSort = `-- name: RefreshAuthorSort :exec
UPDATE books b
SET author_sort = COALESCE((
    SELECT a.sort_name
    FROM book_contributors c
    JOIN authors a ON a.id = c.author_id
    WHERE c.book_id = b.id AND c.role = 'author'
    ORDER BY c.position
    LIMIT 1
), '')
WHERE b.id = $1
`

func (q *Queries) RefreshAuthorSort(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshAuthorSort, id)
	return err
}

const setBookLocks = `-- name: SetBookLocks :exec
UPDATE books SET locked_fields = $2 WHERE id = $1
`

type SetBookLocksParams struct {
	ID           uuid.UUID
	LockedFields []string
}

func (q *Queries) SetBookLocks(ctx context.Context, arg SetBookLocksParams) error {
	_, err := q.db.Exec(ctx, setBookLocks, arg.ID, arg.LockedFields)
	return err
}

const updateBookDescribed = `-- name: UpdateBookDescribed :exec
UPDATE books
SET title               = $2,
    sort_title          = $3,
    title_key           = $4,
    subtitle            = $5,
    description         = $6,
    language            = $7,
    published_on        = $8,
    published_precision = $9,
    publisher_id        = $10,
    series_id           = $11,
    series_index        = $12,
    page_count          = $13,
    cover_key           = $14,
    field_sources       = $15,
    updated_at          = now()
WHERE id = $1
`

type UpdateBookDescribedParams struct {
	ID                 uuid.UUID
	Title              string
	SortTitle          string
	TitleKey           string
	Subtitle           *string
	Description        *string
	Language           *string
	PublishedOn        *time.Time
	PublishedPrecision *string
	PublisherID        *uuid.UUID
	SeriesID           *uuid.UUID
	SeriesIndex        *float64
	PageCount          *int32
	CoverKey           *string
	FieldSources       []byte
}

// Every field that describes the book, as worked out by the caller from what
// was there and what a source says.
func (q *Queries) UpdateBookDescribed(ctx context.Context, arg UpdateBookDescribedParams) error {
	_, err := q.db.Exec(ctx, updateBookDescribed,
		arg.ID,
		arg.Title,
		arg.SortTitle,
		arg.TitleKey,
		arg.Subtitle,
		arg.Description,
		arg.Language,
		arg.PublishedOn,
		arg.PublishedPrecision,
		arg.PublisherID,
		arg.SeriesID,
		arg.SeriesIndex,
		arg.PageCount,
		arg.CoverKey,
		arg.FieldSources,
	)
	return err
}

const upsertAuthor = `-- name: UpsertAuthor :one
INSERT INTO authors (name, sort_name, name_key)
VALUES ($1, $2, $3)
ON CONFLICT (name_key) DO UPDATE SET name_key = EXCLUDED.name_key
RETURNING id, name, sort_name, name_key, created_at
`

type UpsertAuthorParams struct {
	Name     string
	SortName string
	NameKey  string
}

// Finds the author by the compared form of the name, or adds them. The
// spelling that arrived first is kept: a later file spelling the name without
// its accents must not take them away.
func (q *Queries) UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, upsertAuthor, arg.Name, arg.SortName, arg.NameKey)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortName,
		&i.NameKey,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPublisher = `-- name: UpsertPublisher :one
INSERT INTO publishers (name, name_key)
VALUES ($1, $2)
ON CONFLICT (name_key) DO UPDATE SET name_key = EXCLUDED.name_key
RETURNING id, name, name_key
`

type UpsertPublisherParams struct {
	Name    string
	NameKey string
}

func (q *Queries) UpsertPublisher(ctx context.Context, arg UpsertPublisherParams) (Publisher, error) {
	row := q.db.QueryRow(ctx, upsertPublisher, arg.Name, arg.NameKey)
	var i Publisher
	err := row.Scan(&i.ID, &i.Name, &i.NameKey)
	return i, err
}

const upsertSeries = `-- name: UpsertSeries :one
INSERT INTO series (name, name_key)
VALUES ($1, $2)
ON CONFLICT (name_key) DO UPDATE SET name_key = EXCLUDED.name_key
RETURNING id, name, name_key, created_at
`

type UpsertSeriesParams struct {
	Name    string
	NameKey string
}

func (q *Queries) UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, upsertSeries, arg.Name, arg.NameKey)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name, name_key)
VALUES ($1, $2)
ON CONFLICT (name_key) DO UPDATE SET name_key = EXCLUDED.name_key
RETURNING id, name, name_key
`

type UpsertTagParams struct {
	Name    string
	NameKey string
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.Name, arg.NameKey)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.NameKey)
	return i, err
}
