// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addSearchWords = `-- name: AddSearchWords :exec
INSERT INTO search_words (word)
SELECT DISTINCT w
FROM book_chunks c,
     unnest(tsvector_to_array(to_tsvector('simple', coalesce(c.body_en, c.body_de, c.body_xx)))) AS w
WHERE c.book_id = $1 AND length(w) BETWEEN 2 AND 40
ORDER BY w
ON CONFLICT (word) DO NOTHING
`

// Every word of the book's chunks that is not known yet. In order, so that
// two books adding the same new words wait for each other instead of
// deadlocking; words too long to be typed are left out.
func (q *Queries) AddSearchWords(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, addSearchWords, bookID)
	return err
}

const deleteBookChunks = `-- name: DeleteBookChunks :exec
DELETE FROM book_chunks WHERE book_id = $1 OR file_id = $2
`

type DeleteBookChunksParams struct {
	BookID uuid.UUID
	FileID uuid.UUID
}

// A book's chunks, and the file's wherever they are: a file that moved to
// another book takes its text along.
func (q *Queries) DeleteBookChunks(ctx context.Context, arg DeleteBookChunksParams) error {
	_, err := q.db.Exec(ctx, deleteBookChunks, arg.BookID, arg.FileID)
	return err
}

const deleteFileChunks = `-- name: DeleteFileChunks :exec
DELETE FROM book_chunks WHERE file_id = $1
`

func (q *Queries) DeleteFileChunks(ctx context.Context, fileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileChunks, fileID)
	return err
}

const getFileForChunking = `-- name: GetFileForChunking :one
SELECT f.id, f.book_id, f.library_id, f.format, f.sha256, f.rel_path,
       l.root_path, b.language, b.primary_text_file_id
FROM book_files f
JOIN libraries l ON l.id = f.library_id
JOIN books b ON b.id = f.book_id
WHERE f.id = $1 AND f.missing_at IS NULL AND f.trashed_at IS NULL
`

type GetFileForChunkingRow struct {
	ID                uuid.UUID
	BookID            uuid.UUID
	LibraryID         uuid.UUID
	Format            string
	Sha256            []byte
	RelPath           string
	RootPath          string
	Language          *string
	PrimaryTextFileID *uuid.UUID
}

func (q *Queries) GetFileForChunking(ctx context.Context, id uuid.UUID) (GetFileForChunkingRow, error) {
	row := q.db.QueryRow(ctx, getFileForChunking, id)
	var i GetFileForChunkingRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.LibraryID,
		&i.Format,
		&i.Sha256,
		&i.RelPath,
		&i.RootPath,
		&i.Language,
		&i.PrimaryTextFileID,
	)
	return i, err
}

const getPrimaryTextFile = `-- name: GetPrimaryTextFile :one
SELECT primary_text_file_id FROM books WHERE id = $1
`

func (q *Queries) GetPrimaryTextFile(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPrimaryTextFile, id)
	var primary_text_file_id *uuid.UUID
	err := row.Scan(&primary_text_file_id)
	return primary_text_file_id, err
}

type InsertBookChunksParams struct {
	BookID     uuid.UUID
	LibraryID  uuid.UUID
	FileID     uuid.UUID
	Position   int32
	Chapter    string
	PageFrom   *int32
	PageTo     *int32
	CharOffset int32
	Lang       string
	BodyEn     *string
	BodyDe     *string
	BodyXx     *string
}

const listBookTextFiles = `-- name: ListBookTextFiles :many
SELECT id, format, created_at
FROM book_files
WHERE book_id = $1 AND has_text AND NOT drm AND missing_at IS NULL AND trashed_at IS NULL
`

type ListBookTextFilesRow struct {
	ID        uuid.UUID
	Format    string
	CreatedAt time.Time
}

// The files of a book its text may be read from, for choosing the primary one.
func (q *Queries) ListBookTextFiles(ctx context.Context, bookID uuid.UUID) ([]ListBookTextFilesRow, error) {
	rows, err := q.db.Query(ctx, listBookTextFiles, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookTextFilesRow{}
	for rows.Next() {
		var i ListBookTextFilesRow
		if err := rows.Scan(&i.ID, &i.Format, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnchunkedTextFiles = `-- name: ListUnchunkedTextFiles :many
SELECT f.id
FROM books b
JOIN book_files f ON f.id = b.primary_text_file_id
WHERE f.chunked_at IS NULL AND f.missing_at IS NULL AND f.trashed_at IS NULL
  AND b.deleted_at IS NULL AND NOT b.placeholder
`

// The primary text files whose text is still to be cut into chunks.
func (q *Queries) ListUnchunkedTextFiles(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUnchunkedTextFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileChunked = `-- name: SetFileChunked :exec
UPDATE book_files SET chunked_at = now() WHERE id = $1
`

func (q *Queries) SetFileChunked(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setFileChunked, id)
	return err
}

const setPrimaryTextFile = `-- name: SetPrimaryTextFile :exec
UPDATE books SET primary_text_file_id = $2 WHERE id = $1
`

type SetPrimaryTextFileParams struct {
	ID                uuid.UUID
	PrimaryTextFileID *uuid.UUID
}

func (q *Queries) SetPrimaryTextFile(ctx context.Context, arg SetPrimaryTextFileParams) error {
	_, err := q.db.Exec(ctx, setPrimaryTextFile, arg.ID, arg.PrimaryTextFileID)
	return err
}
