// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const dismissCleanup = `-- name: DismissCleanup :exec
INSERT INTO cleanup_dismissals (kind, subject, value, dismissed_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (kind, subject) DO UPDATE
SET value = EXCLUDED.value, dismissed_by = EXCLUDED.dismissed_by, dismissed_at = now()
`

type DismissCleanupParams struct {
	Kind        string
	Subject     string
	Value       string
	DismissedBy *uuid.UUID
}

func (q *Queries) DismissCleanup(ctx context.Context, arg DismissCleanupParams) error {
	_, err := q.db.Exec(ctx, dismissCleanup,
		arg.Kind,
		arg.Subject,
		arg.Value,
		arg.DismissedBy,
	)
	return err
}

const listCleanupCredits = `-- name: ListCleanupCredits :many
SELECT c.book_id, a.name, a.name_key, a.person_key, COALESCE(s.name_key, '')::text AS series_key
FROM book_contributors c
JOIN authors a ON a.id = c.author_id
JOIN books b ON b.id = c.book_id
LEFT JOIN series s ON s.id = b.series_id
WHERE c.role = 'author' AND b.deleted_at IS NULL
  AND (a.person_key = ANY($1::text[]) OR a.name_key = ANY($2::text[]))
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($3::uuid, $4::boolean))
ORDER BY b.sort_title, b.id, c.position
`

type ListCleanupCreditsParams struct {
	PersonKeys []string
	NameKeys   []string
	Viewer     uuid.UUID
	SeesAll    bool
}

type ListCleanupCreditsRow struct {
	BookID    uuid.UUID
	Name      string
	NameKey   string
	PersonKey *string
	SeriesKey string
}

// The author credits of the books the viewer sees whose author is one of
// the people (person_keys) or names (name_keys) a clean-up is about, with
// the key of the book's series.
func (q *Queries) ListCleanupCredits(ctx context.Context, arg ListCleanupCreditsParams) ([]ListCleanupCreditsRow, error) {
	rows, err := q.db.Query(ctx, listCleanupCredits,
		arg.PersonKeys,
		arg.NameKeys,
		arg.Viewer,
		arg.SeesAll,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCleanupCreditsRow{}
	for rows.Next() {
		var i ListCleanupCreditsRow
		if err := rows.Scan(
			&i.BookID,
			&i.Name,
			&i.NameKey,
			&i.PersonKey,
			&i.SeriesKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
