// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCollectionItems = `-- name: AddCollectionItems :execrows
INSERT INTO collection_items (collection_id, book_id, position)
SELECT $1, b.id,
       (SELECT COALESCE(max(position), 0) FROM collection_items WHERE collection_id = $1) + n.ord::int
FROM unnest($2::uuid[]) WITH ORDINALITY AS n(id, ord)
JOIN books b ON b.id = n.id
WHERE b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($3::uuid, $4::boolean))
ON CONFLICT (collection_id, book_id) DO NOTHING
`

type AddCollectionItemsParams struct {
	CollectionID uuid.UUID
	Ids          []uuid.UUID
	Viewer       uuid.UUID
	SeesAll      bool
}

// Puts the books among ids the viewer may see at the end of the
// collection, in the order of ids; those it holds already stay where they
// are.
func (q *Queries) AddCollectionItems(ctx context.Context, arg AddCollectionItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, addCollectionItems,
		arg.CollectionID,
		arg.Ids,
		arg.Viewer,
		arg.SeesAll,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const collectionBookIDs = `-- name: CollectionBookIDs :many
SELECT i.book_id
FROM collection_items i
JOIN books b ON b.id = i.book_id
WHERE i.collection_id = $1
  AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($2::uuid, $3::boolean))
ORDER BY i.position, i.added_at, i.book_id
`

type CollectionBookIDsParams struct {
	CollectionID uuid.UUID
	Viewer       uuid.UUID
	SeesAll      bool
}

// The collection's books the viewer may see, in its order.
func (q *Queries) CollectionBookIDs(ctx context.Context, arg CollectionBookIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, collectionBookIDs, arg.CollectionID, arg.Viewer, arg.SeesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var book_id uuid.UUID
		if err := rows.Scan(&book_id); err != nil {
			return nil, err
		}
		items = append(items, book_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectionItems = `-- name: CollectionItems :many
SELECT book_id, position FROM collection_items
WHERE collection_id = $1
ORDER BY position, added_at, book_id
`

type CollectionItemsRow struct {
	BookID   uuid.UUID
	Position int32
}

// Every book of the collection with its position, seen or not.
func (q *Queries) CollectionItems(ctx context.Context, collectionID uuid.UUID) ([]CollectionItemsRow, error) {
	rows, err := q.db.Query(ctx, collectionItems, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionItemsRow{}
	for rows.Next() {
		var i CollectionItemsRow
		if err := rows.Scan(&i.BookID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCollectionItems = `-- name: CountCollectionItems :one
SELECT count(*)::int FROM collection_items WHERE collection_id = $1
`

func (q *Queries) CountCollectionItems(ctx context.Context, collectionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCollectionItems, collectionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (owner_id, name, description, visibility)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateCollectionParams struct {
	OwnerID     uuid.UUID
	Name        string
	Description string
	Visibility  string
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Visibility,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT c.id, c.owner_id, u.username::text AS owner_name, c.name, c.description, c.visibility,
       c.created_at, c.updated_at
FROM collections c
JOIN users u ON u.id = c.owner_id
WHERE c.id = $1 AND (c.owner_id = $2::uuid OR c.visibility = 'shared')
`

type GetCollectionParams struct {
	ID     uuid.UUID
	Viewer uuid.UUID
}

type GetCollectionRow struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	OwnerName   string
	Name        string
	Description string
	Visibility  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (GetCollectionRow, error) {
	row := q.db.QueryRow(ctx, getCollection, arg.ID, arg.Viewer)
	var i GetCollectionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OwnerName,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollections = `-- name: ListCollections :many
SELECT c.id, c.owner_id, u.username::text AS owner_name, c.name, c.description, c.visibility,
       c.created_at, c.updated_at,
       (SELECT count(*) FROM collection_items i JOIN books b ON b.id = i.book_id
        WHERE i.collection_id = c.id AND b.deleted_at IS NULL
          AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($1::uuid, $2::boolean)))::int AS books,
       EXISTS (SELECT 1 FROM collection_items i JOIN books b ON b.id = i.book_id
               WHERE i.collection_id = c.id AND i.book_id = $3::uuid AND b.deleted_at IS NULL
                 AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($1::uuid, $2::boolean))) AS has_book
FROM collections c
JOIN users u ON u.id = c.owner_id
WHERE c.owner_id = $1::uuid OR c.visibility = 'shared'
ORDER BY c.owner_id = $1::uuid DESC, lower(c.name), c.id
`

type ListCollectionsParams struct {
	Viewer  uuid.UUID
	SeesAll bool
	Book    *uuid.UUID
}

type ListCollectionsRow struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	OwnerName   string
	Name        string
	Description string
	Visibility  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Books       int32
	HasBook     bool
}

// The viewer's own collections and everyone's shared ones, each with how
// many of its books the viewer may see, and whether it holds the book
// asked about.
func (q *Queries) ListCollections(ctx context.Context, arg ListCollectionsParams) ([]ListCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCollections, arg.Viewer, arg.SeesAll, arg.Book)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsRow{}
	for rows.Next() {
		var i ListCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.OwnerName,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Books,
			&i.HasBook,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCollection = `-- name: LockCollection :one
SELECT owner_id, visibility FROM collections WHERE id = $1 FOR UPDATE
`

type LockCollectionRow struct {
	OwnerID    uuid.UUID
	Visibility string
}

func (q *Queries) LockCollection(ctx context.Context, id uuid.UUID) (LockCollectionRow, error) {
	row := q.db.QueryRow(ctx, lockCollection, id)
	var i LockCollectionRow
	err := row.Scan(&i.OwnerID, &i.Visibility)
	return i, err
}

const removeCollectionItem = `-- name: RemoveCollectionItem :execrows
DELETE FROM collection_items i
USING books b
WHERE i.collection_id = $1 AND i.book_id = $2
  AND b.id = i.book_id AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($3::uuid, $4::boolean))
`

type RemoveCollectionItemParams struct {
	CollectionID uuid.UUID
	BookID       uuid.UUID
	Viewer       uuid.UUID
	SeesAll      bool
}

// Takes a book the viewer may see out of the collection.
func (q *Queries) RemoveCollectionItem(ctx context.Context, arg RemoveCollectionItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeCollectionItem,
		arg.CollectionID,
		arg.BookID,
		arg.Viewer,
		arg.SeesAll,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCollectionPositions = `-- name: SetCollectionPositions :exec
UPDATE collection_items i SET position = ($1::int[])[n.ord]
FROM unnest($3::uuid[]) WITH ORDINALITY AS n(id, ord)
WHERE i.collection_id = $2 AND i.book_id = n.id
`

type SetCollectionPositionsParams struct {
	Positions    []int32
	CollectionID uuid.UUID
	Ids          []uuid.UUID
}

func (q *Queries) SetCollectionPositions(ctx context.Context, arg SetCollectionPositionsParams) error {
	_, err := q.db.Exec(ctx, setCollectionPositions, arg.Positions, arg.CollectionID, arg.Ids)
	return err
}

const touchCollection = `-- name: TouchCollection :exec
UPDATE collections SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchCollection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCollection, id)
	return err
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections
SET name = $2, description = $3, visibility = $4, updated_at = now()
WHERE id = $1
`

type UpdateCollectionParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Visibility  string
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.Exec(ctx, updateCollection,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Visibility,
	)
	return err
}
