// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertBookChunks implements pgx.CopyFromSource.
type iteratorForInsertBookChunks struct {
	rows                 []InsertBookChunksParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertBookChunks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertBookChunks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BookID,
		r.rows[0].LibraryID,
		r.rows[0].FileID,
		r.rows[0].Position,
		r.rows[0].Chapter,
		r.rows[0].PageFrom,
		r.rows[0].PageTo,
		r.rows[0].CharOffset,
		r.rows[0].Lang,
		r.rows[0].BodyEn,
		r.rows[0].BodyDe,
		r.rows[0].BodyXx,
	}, nil
}

func (r iteratorForInsertBookChunks) Err() error {
	return nil
}

func (q *Queries) InsertBookChunks(ctx context.Context, arg []InsertBookChunksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"book_chunks"}, []string{"book_id", "library_id", "file_id", "position", "chapter", "page_from", "page_to", "char_offset", "lang", "body_en", "body_de", "body_xx"}, &iteratorForInsertBookChunks{rows: arg})
}
