// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: duplicates.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addDuplicateEvidence = `-- name: AddDuplicateEvidence :exec
INSERT INTO duplicate_evidence (pair_id, kind, detail)
SELECT unnest($1::uuid[]), unnest($2::text[]), unnest($3::text[])
ON CONFLICT DO NOTHING
`

type AddDuplicateEvidenceParams struct {
	PairIds []uuid.UUID
	Kinds   []string
	Details []string
}

func (q *Queries) AddDuplicateEvidence(ctx context.Context, arg AddDuplicateEvidenceParams) error {
	_, err := q.db.Exec(ctx, addDuplicateEvidence, arg.PairIds, arg.Kinds, arg.Details)
	return err
}

const dropBookSignatures = `-- name: DropBookSignatures :exec
DELETE FROM file_signatures s
USING book_files f
WHERE s.file_id = f.id AND f.book_id = $1 AND f.id <> $2
`

type DropBookSignaturesParams struct {
	BookID uuid.UUID
	FileID uuid.UUID
}

// The signatures of the book's files other than the one its text is read
// from, which stand for it no more.
func (q *Queries) DropBookSignatures(ctx context.Context, arg DropBookSignaturesParams) error {
	_, err := q.db.Exec(ctx, dropBookSignatures, arg.BookID, arg.FileID)
	return err
}

const dropEmptyDuplicatePairs = `-- name: DropEmptyDuplicatePairs :exec
DELETE FROM duplicate_pairs p
WHERE p.state = 'open'
  AND (p.book_a = $1 OR p.book_b = $1)
  AND NOT EXISTS (SELECT 1 FROM duplicate_evidence e WHERE e.pair_id = p.id)
`

// The book's open pairs that no evidence holds up any more.
func (q *Queries) DropEmptyDuplicatePairs(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, dropEmptyDuplicatePairs, bookID)
	return err
}

const dropFileBuckets = `-- name: DropFileBuckets :exec
DELETE FROM file_lsh WHERE file_id = $1
`

func (q *Queries) DropFileBuckets(ctx context.Context, fileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, dropFileBuckets, fileID)
	return err
}

const dropFileSignature = `-- name: DropFileSignature :exec
DELETE FROM file_signatures WHERE file_id = $1
`

func (q *Queries) DropFileSignature(ctx context.Context, fileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, dropFileSignature, fileID)
	return err
}

const findDuplicateEvidence = `-- name: FindDuplicateEvidence :many
WITH me AS (
    SELECT bk.id, bk.title_key FROM books bk
    WHERE bk.id = $1 AND bk.deleted_at IS NULL AND NOT bk.placeholder
)
SELECT o.book_id AS other, 'sha256'::text AS kind, encode(f.sha256, 'hex') AS detail
FROM me
JOIN book_files f ON f.book_id = me.id AND f.missing_at IS NULL AND f.trashed_at IS NULL
JOIN book_files o ON o.sha256 = f.sha256 AND o.book_id <> me.id AND o.missing_at IS NULL AND o.trashed_at IS NULL
JOIN books ob ON ob.id = o.book_id AND ob.deleted_at IS NULL AND NOT ob.placeholder
UNION
SELECT o.book_id, 'content', encode(f.content_sha256, 'hex')
FROM me
JOIN book_files f ON f.book_id = me.id AND f.missing_at IS NULL AND f.trashed_at IS NULL
JOIN book_files o ON o.content_sha256 = f.content_sha256 AND o.book_id <> me.id AND o.missing_at IS NULL AND o.trashed_at IS NULL
JOIN books ob ON ob.id = o.book_id AND ob.deleted_at IS NULL AND NOT ob.placeholder
WHERE o.sha256 IS DISTINCT FROM f.sha256
UNION
SELECT o.book_id, 'isbn', i.value
FROM me
JOIN book_identifiers i ON i.book_id = me.id AND i.type = 'isbn'
JOIN book_identifiers o ON o.type = 'isbn' AND o.value = i.value AND o.book_id <> me.id
JOIN books ob ON ob.id = o.book_id AND ob.deleted_at IS NULL AND NOT ob.placeholder
UNION
SELECT ob.id, 'title_author', me.title_key || ' / ' || a.name_key
FROM me
JOIN books ob ON ob.title_key = me.title_key AND ob.id <> me.id
               AND ob.deleted_at IS NULL AND NOT ob.placeholder
JOIN book_contributors c ON c.book_id = me.id AND c.role = 'author'
JOIN book_contributors oc ON oc.book_id = ob.id AND oc.role = 'author' AND oc.author_id = c.author_id
JOIN authors a ON a.id = c.author_id
WHERE me.title_key <> ''
`

type FindDuplicateEvidenceRow struct {
	Other  uuid.UUID
	Kind   string
	Detail string
}

// Every other book that looks like this one, with why: a file of the same
// bytes, a file of the same content where the bytes differ, a shared ISBN,
// or the same title and an author in common. Only books in the library,
// neither deleted, merged nor wished for, count. Each branch starts from the
// book's own rows and reaches the others through an index.
func (q *Queries) FindDuplicateEvidence(ctx context.Context, bookID uuid.UUID) ([]FindDuplicateEvidenceRow, error) {
	rows, err := q.db.Query(ctx, findDuplicateEvidence, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDuplicateEvidenceRow{}
	for rows.Next() {
		var i FindDuplicateEvidenceRow
		if err := rows.Scan(&i.Other, &i.Kind, &i.Detail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookSignature = `-- name: GetBookSignature :one
SELECT s.file_id, s.shingles, s.signature
FROM books b JOIN file_signatures s ON s.file_id = b.primary_text_file_id
WHERE b.id = $1 AND b.deleted_at IS NULL AND NOT b.placeholder AND s.signature IS NOT NULL
`

type GetBookSignatureRow struct {
	FileID    uuid.UUID
	Shingles  int32
	Signature []byte
}

// The signature of the book's primary text file, if it has one.
func (q *Queries) GetBookSignature(ctx context.Context, id uuid.UUID) (GetBookSignatureRow, error) {
	row := q.db.QueryRow(ctx, getBookSignature, id)
	var i GetBookSignatureRow
	err := row.Scan(&i.FileID, &i.Shingles, &i.Signature)
	return i, err
}

const getVisiblePair = `-- name: GetVisiblePair :one
SELECT p.id, p.state FROM duplicate_pairs p
JOIN books a ON a.id = p.book_a
JOIN books b ON b.id = p.book_b
WHERE p.id = $1
  AND a.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
  AND b.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
  AND a.deleted_at IS NULL AND b.deleted_at IS NULL
FOR UPDATE OF p
`

type GetVisiblePairParams struct {
	ID      uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

type GetVisiblePairRow struct {
	ID    uuid.UUID
	State string
}

// The pair, if the viewer sees both its books.
func (q *Queries) GetVisiblePair(ctx context.Context, arg GetVisiblePairParams) (GetVisiblePairRow, error) {
	row := q.db.QueryRow(ctx, getVisiblePair, arg.ID, arg.Viewer, arg.SeesAll)
	var i GetVisiblePairRow
	err := row.Scan(&i.ID, &i.State)
	return i, err
}

const listDuplicateEvidence = `-- name: ListDuplicateEvidence :many
SELECT pair_id, kind, detail, duplicate_score(kind, detail) AS score FROM duplicate_evidence
WHERE pair_id = ANY($1::uuid[])
ORDER BY pair_id, score DESC, kind, detail
`

type ListDuplicateEvidenceRow struct {
	PairID uuid.UUID
	Kind   string
	Detail string
	Score  float32
}

func (q *Queries) ListDuplicateEvidence(ctx context.Context, pairIds []uuid.UUID) ([]ListDuplicateEvidenceRow, error) {
	rows, err := q.db.Query(ctx, listDuplicateEvidence, pairIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicateEvidenceRow{}
	for rows.Next() {
		var i ListDuplicateEvidenceRow
		if err := rows.Scan(
			&i.PairID,
			&i.Kind,
			&i.Detail,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuplicatePairs = `-- name: ListDuplicatePairs :many
SELECT p.id, p.book_a, p.book_b, p.state, p.found_at, p.score
FROM duplicate_pairs p
JOIN books a ON a.id = p.book_a
JOIN books b ON b.id = p.book_b
WHERE p.state = $1
  AND a.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
  AND b.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
  AND a.deleted_at IS NULL AND b.deleted_at IS NULL
  AND ($4::uuid IS NULL OR $4::uuid IN (a.library_id, b.library_id))
  AND ($5::text IS NULL OR EXISTS (
      SELECT 1 FROM duplicate_evidence e WHERE e.pair_id = p.id AND e.kind = $5::text))
  AND p.score >= $6::real
  AND ($7::uuid IS NULL
       OR (p.score, p.id) < ($8::real, $7::uuid))
ORDER BY p.score DESC, p.id DESC
LIMIT $9
`

type ListDuplicatePairsParams struct {
	State      string
	Viewer     uuid.UUID
	SeesAll    bool
	LibraryID  *uuid.UUID
	Kind       *string
	Least      float32
	AfterID    *uuid.UUID
	AfterScore float32
	PageSize   int32
}

type ListDuplicatePairsRow struct {
	ID      uuid.UUID
	BookA   uuid.UUID
	BookB   uuid.UUID
	State   string
	FoundAt time.Time
	Score   float32
}

// The pairs in the state whose books the viewer both sees, of a library when
// named (either book in it), with evidence of the kind and a score of at
// least the least when named, the strongest first, after the cursor's.
func (q *Queries) ListDuplicatePairs(ctx context.Context, arg ListDuplicatePairsParams) ([]ListDuplicatePairsRow, error) {
	rows, err := q.db.Query(ctx, listDuplicatePairs,
		arg.State,
		arg.Viewer,
		arg.SeesAll,
		arg.LibraryID,
		arg.Kind,
		arg.Least,
		arg.AfterID,
		arg.AfterScore,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicatePairsRow{}
	for rows.Next() {
		var i ListDuplicatePairsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookA,
			&i.BookB,
			&i.State,
			&i.FoundAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileChunkTexts = `-- name: ListFileChunkTexts :many
SELECT coalesce(body_en, body_de, body_xx)::text AS body
FROM book_chunks WHERE file_id = $1 ORDER BY position
`

// The file's text as its chunks hold it, in order.
func (q *Queries) ListFileChunkTexts(ctx context.Context, fileID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listFileChunkTexts, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var body string
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryBookIDs = `-- name: ListLibraryBookIDs :many
SELECT b.id FROM books b
WHERE b.library_id IN (SELECT visible_library_ids($1::uuid, $2::boolean))
  AND ($3::uuid IS NULL OR b.library_id = $3::uuid)
  AND b.deleted_at IS NULL AND NOT b.placeholder
`

type ListLibraryBookIDsParams struct {
	Viewer    uuid.UUID
	SeesAll   bool
	LibraryID *uuid.UUID
}

// The books of the visible libraries, of one when named, to check.
func (q *Queries) ListLibraryBookIDs(ctx context.Context, arg ListLibraryBookIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLibraryBookIDs, arg.Viewer, arg.SeesAll, arg.LibraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignatureCompanions = `-- name: ListSignatureCompanions :many
SELECT DISTINCT s.file_id, b.id AS book_id, s.shingles, s.signature
FROM file_lsh me
JOIN file_lsh o ON o.band = me.band AND o.bucket = me.bucket AND o.file_id <> me.file_id
JOIN file_signatures s ON s.file_id = o.file_id
JOIN book_files f ON f.id = s.file_id
JOIN books b ON b.id = f.book_id AND b.primary_text_file_id = f.id
WHERE me.file_id = $1
  AND b.id <> $2 AND b.deleted_at IS NULL AND NOT b.placeholder
  AND (SELECT count(*) FROM file_lsh c WHERE c.band = me.band AND c.bucket = me.bucket) <= $3::bigint
`

type ListSignatureCompanionsParams struct {
	FileID uuid.UUID
	BookID uuid.UUID
	Crowd  int64
}

type ListSignatureCompanionsRow struct {
	FileID    uuid.UUID
	BookID    uuid.UUID
	Shingles  int32
	Signature []byte
}

// The signatures of other books' primary text files that share a bucket
// with the file. A bucket shared by more than sqlc.arg(crowd) files is
// passed over: text every book of a kind carries, such as a licence, says
// nothing about two of them.
func (q *Queries) ListSignatureCompanions(ctx context.Context, arg ListSignatureCompanionsParams) ([]ListSignatureCompanionsRow, error) {
	rows, err := q.db.Query(ctx, listSignatureCompanions, arg.FileID, arg.BookID, arg.Crowd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSignatureCompanionsRow{}
	for rows.Next() {
		var i ListSignatureCompanionsRow
		if err := rows.Scan(
			&i.FileID,
			&i.BookID,
			&i.Shingles,
			&i.Signature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsignedFiles = `-- name: ListUnsignedFiles :many
SELECT f.id, f.book_id
FROM books b
JOIN book_files f ON f.id = b.primary_text_file_id
LEFT JOIN file_signatures s ON s.file_id = f.id
WHERE f.chunked_at IS NOT NULL AND b.deleted_at IS NULL AND NOT b.placeholder
  AND (s.file_id IS NULL OR s.version <> $1::smallint)
`

type ListUnsignedFilesRow struct {
	ID     uuid.UUID
	BookID uuid.UUID
}

// The chunked primary text files without a signature of this version.
func (q *Queries) ListUnsignedFiles(ctx context.Context, version int16) ([]ListUnsignedFilesRow, error) {
	rows, err := q.db.Query(ctx, listUnsignedFiles, version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnsignedFilesRow{}
	for rows.Next() {
		var i ListUnsignedFilesRow
		if err := rows.Scan(&i.ID, &i.BookID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDuplicateEvidence = `-- name: PruneDuplicateEvidence :exec
DELETE FROM duplicate_evidence e
USING duplicate_pairs p
WHERE e.pair_id = p.id AND p.state = 'open'
  AND (p.book_a = $1 OR p.book_b = $1)
  AND (e.pair_id, e.kind, e.detail) NOT IN (
      SELECT unnest($2::uuid[]), unnest($3::text[]), unnest($4::text[])
  )
`

type PruneDuplicateEvidenceParams struct {
	BookID  uuid.UUID
	PairIds []uuid.UUID
	Kinds   []string
	Details []string
}

// Takes back, from the book's open pairs, the evidence not found again.
func (q *Queries) PruneDuplicateEvidence(ctx context.Context, arg PruneDuplicateEvidenceParams) error {
	_, err := q.db.Exec(ctx, pruneDuplicateEvidence,
		arg.BookID,
		arg.PairIds,
		arg.Kinds,
		arg.Details,
	)
	return err
}

const putFileBuckets = `-- name: PutFileBuckets :exec
INSERT INTO file_lsh (band, bucket, file_id)
SELECT unnest($1::smallint[]), unnest($2::bigint[]), $3::uuid
ON CONFLICT DO NOTHING
`

type PutFileBucketsParams struct {
	Bands   []int16
	Buckets []int64
	FileID  uuid.UUID
}

func (q *Queries) PutFileBuckets(ctx context.Context, arg PutFileBucketsParams) error {
	_, err := q.db.Exec(ctx, putFileBuckets, arg.Bands, arg.Buckets, arg.FileID)
	return err
}

const putFileSignature = `-- name: PutFileSignature :exec
INSERT INTO file_signatures (file_id, version, shingles, signature) VALUES ($1, $2, $3, $4)
ON CONFLICT (file_id) DO UPDATE SET version = EXCLUDED.version, shingles = EXCLUDED.shingles,
    signature = EXCLUDED.signature, signed_at = now()
`

type PutFileSignatureParams struct {
	FileID    uuid.UUID
	Version   int16
	Shingles  int32
	Signature []byte
}

func (q *Queries) PutFileSignature(ctx context.Context, arg PutFileSignatureParams) error {
	_, err := q.db.Exec(ctx, putFileSignature,
		arg.FileID,
		arg.Version,
		arg.Shingles,
		arg.Signature,
	)
	return err
}

const refreshPairScores = `-- name: RefreshPairScores :exec
UPDATE duplicate_pairs p SET score = coalesce(
    (SELECT max(duplicate_score(e.kind, e.detail)) FROM duplicate_evidence e WHERE e.pair_id = p.id), 0)
WHERE p.book_a = $1 OR p.book_b = $1
`

// The book's pairs' scores, from their evidence as it now is.
func (q *Queries) RefreshPairScores(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshPairScores, bookID)
	return err
}

const setPairState = `-- name: SetPairState :exec
UPDATE duplicate_pairs SET state = $2, updated_at = now() WHERE id = $1
`

type SetPairStateParams struct {
	ID    uuid.UUID
	State string
}

func (q *Queries) SetPairState(ctx context.Context, arg SetPairStateParams) error {
	_, err := q.db.Exec(ctx, setPairState, arg.ID, arg.State)
	return err
}

const upsertDuplicatePair = `-- name: UpsertDuplicatePair :one
INSERT INTO duplicate_pairs (book_a, book_b) VALUES ($1, $2)
ON CONFLICT (book_a, book_b) DO UPDATE SET updated_at = duplicate_pairs.updated_at
RETURNING id
`

type UpsertDuplicatePairParams struct {
	BookA uuid.UUID
	BookB uuid.UUID
}

func (q *Queries) UpsertDuplicatePair(ctx context.Context, arg UpsertDuplicatePairParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDuplicatePair, arg.BookA, arg.BookB)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
