// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: duplicates.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addDuplicateEvidence = `-- name: AddDuplicateEvidence :exec
INSERT INTO duplicate_evidence (pair_id, kind, detail)
SELECT unnest($1::uuid[]), unnest($2::text[]), unnest($3::text[])
ON CONFLICT DO NOTHING
`

type AddDuplicateEvidenceParams struct {
	PairIds []uuid.UUID
	Kinds   []string
	Details []string
}

func (q *Queries) AddDuplicateEvidence(ctx context.Context, arg AddDuplicateEvidenceParams) error {
	_, err := q.db.Exec(ctx, addDuplicateEvidence, arg.PairIds, arg.Kinds, arg.Details)
	return err
}

const dropEmptyDuplicatePairs = `-- name: DropEmptyDuplicatePairs :exec
DELETE FROM duplicate_pairs p
WHERE p.state = 'open'
  AND (p.book_a = $1 OR p.book_b = $1)
  AND NOT EXISTS (SELECT 1 FROM duplicate_evidence e WHERE e.pair_id = p.id)
`

// The book's open pairs that no evidence holds up any more.
func (q *Queries) DropEmptyDuplicatePairs(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, dropEmptyDuplicatePairs, bookID)
	return err
}

const findDuplicateEvidence = `-- name: FindDuplicateEvidence :many
WITH me AS (
    SELECT bk.id, bk.title_key FROM books bk
    WHERE bk.id = $1 AND bk.deleted_at IS NULL AND NOT bk.placeholder
),
files AS (
    SELECT f.book_id, f.sha256, f.content_sha256
    FROM book_files f
    JOIN books b ON b.id = f.book_id
    WHERE f.missing_at IS NULL AND f.trashed_at IS NULL
      AND b.deleted_at IS NULL AND NOT b.placeholder
)
SELECT o.book_id AS other, 'sha256'::text AS kind, encode(f.sha256, 'hex') AS detail
FROM me
JOIN files f ON f.book_id = me.id
JOIN files o ON o.sha256 = f.sha256 AND o.book_id <> me.id
UNION
SELECT o.book_id, 'content', encode(f.content_sha256, 'hex')
FROM me
JOIN files f ON f.book_id = me.id
JOIN files o ON o.content_sha256 = f.content_sha256 AND o.book_id <> me.id
WHERE o.sha256 IS DISTINCT FROM f.sha256
UNION
SELECT o.book_id, 'isbn', i.value
FROM me
JOIN book_identifiers i ON i.book_id = me.id AND i.type = 'isbn'
JOIN book_identifiers o ON o.type = 'isbn' AND o.value = i.value AND o.book_id <> me.id
JOIN books ob ON ob.id = o.book_id AND ob.deleted_at IS NULL AND NOT ob.placeholder
UNION
SELECT ob.id, 'title_author', me.title_key || ' / ' || a.name_key
FROM me
JOIN books ob ON ob.title_key = me.title_key AND ob.id <> me.id
               AND ob.deleted_at IS NULL AND NOT ob.placeholder
JOIN book_contributors c ON c.book_id = me.id AND c.role = 'author'
JOIN book_contributors oc ON oc.book_id = ob.id AND oc.role = 'author' AND oc.author_id = c.author_id
JOIN authors a ON a.id = c.author_id
WHERE me.title_key <> ''
`

type FindDuplicateEvidenceRow struct {
	Other  uuid.UUID
	Kind   string
	Detail string
}

// Every other book that looks like this one, with why: a file of the same
// bytes, a file of the same content where the bytes differ, a shared ISBN,
// or the same title and an author in common. Only books in the library,
// neither deleted, merged nor wished for, count.
func (q *Queries) FindDuplicateEvidence(ctx context.Context, bookID uuid.UUID) ([]FindDuplicateEvidenceRow, error) {
	rows, err := q.db.Query(ctx, findDuplicateEvidence, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDuplicateEvidenceRow{}
	for rows.Next() {
		var i FindDuplicateEvidenceRow
		if err := rows.Scan(&i.Other, &i.Kind, &i.Detail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuplicateEvidence = `-- name: ListDuplicateEvidence :many
SELECT pair_id, kind, detail FROM duplicate_evidence
WHERE pair_id = ANY($1::uuid[])
ORDER BY pair_id, kind, detail
`

func (q *Queries) ListDuplicateEvidence(ctx context.Context, pairIds []uuid.UUID) ([]DuplicateEvidence, error) {
	rows, err := q.db.Query(ctx, listDuplicateEvidence, pairIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DuplicateEvidence{}
	for rows.Next() {
		var i DuplicateEvidence
		if err := rows.Scan(&i.PairID, &i.Kind, &i.Detail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDuplicatePairs = `-- name: ListDuplicatePairs :many
SELECT p.id, p.book_a, p.book_b, p.state, p.found_at
FROM duplicate_pairs p
JOIN books a ON a.id = p.book_a
JOIN books b ON b.id = p.book_b
WHERE p.state = $1
  AND a.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
  AND b.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
  AND a.deleted_at IS NULL AND b.deleted_at IS NULL
  AND ($4::uuid IS NULL OR $4::uuid IN (a.library_id, b.library_id))
  AND ($5::uuid IS NULL OR p.id < $5::uuid)
ORDER BY p.id DESC
LIMIT $6
`

type ListDuplicatePairsParams struct {
	State     string
	Viewer    uuid.UUID
	SeesAll   bool
	LibraryID *uuid.UUID
	Before    *uuid.UUID
	PageSize  int32
}

type ListDuplicatePairsRow struct {
	ID      uuid.UUID
	BookA   uuid.UUID
	BookB   uuid.UUID
	State   string
	FoundAt time.Time
}

// The pairs in the state whose books the viewer both sees, of a library when
// named (either book in it), newest first, after the cursor.
func (q *Queries) ListDuplicatePairs(ctx context.Context, arg ListDuplicatePairsParams) ([]ListDuplicatePairsRow, error) {
	rows, err := q.db.Query(ctx, listDuplicatePairs,
		arg.State,
		arg.Viewer,
		arg.SeesAll,
		arg.LibraryID,
		arg.Before,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDuplicatePairsRow{}
	for rows.Next() {
		var i ListDuplicatePairsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookA,
			&i.BookB,
			&i.State,
			&i.FoundAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryBookIDs = `-- name: ListLibraryBookIDs :many
SELECT b.id FROM books b
WHERE b.library_id IN (SELECT visible_library_ids($1::uuid, $2::boolean))
  AND ($3::uuid IS NULL OR b.library_id = $3::uuid)
  AND b.deleted_at IS NULL AND NOT b.placeholder
`

type ListLibraryBookIDsParams struct {
	Viewer    uuid.UUID
	SeesAll   bool
	LibraryID *uuid.UUID
}

// The books of the visible libraries, of one when named, to check.
func (q *Queries) ListLibraryBookIDs(ctx context.Context, arg ListLibraryBookIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLibraryBookIDs, arg.Viewer, arg.SeesAll, arg.LibraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDuplicateEvidence = `-- name: PruneDuplicateEvidence :exec
DELETE FROM duplicate_evidence e
USING duplicate_pairs p
WHERE e.pair_id = p.id AND p.state = 'open'
  AND (p.book_a = $1 OR p.book_b = $1)
  AND (e.pair_id, e.kind, e.detail) NOT IN (
      SELECT unnest($2::uuid[]), unnest($3::text[]), unnest($4::text[])
  )
`

type PruneDuplicateEvidenceParams struct {
	BookID  uuid.UUID
	PairIds []uuid.UUID
	Kinds   []string
	Details []string
}

// Takes back, from the book's open pairs, the evidence not found again.
func (q *Queries) PruneDuplicateEvidence(ctx context.Context, arg PruneDuplicateEvidenceParams) error {
	_, err := q.db.Exec(ctx, pruneDuplicateEvidence,
		arg.BookID,
		arg.PairIds,
		arg.Kinds,
		arg.Details,
	)
	return err
}

const upsertDuplicatePair = `-- name: UpsertDuplicatePair :one
INSERT INTO duplicate_pairs (book_a, book_b) VALUES ($1, $2)
ON CONFLICT (book_a, book_b) DO UPDATE SET updated_at = duplicate_pairs.updated_at
RETURNING id
`

type UpsertDuplicatePairParams struct {
	BookA uuid.UUID
	BookB uuid.UUID
}

func (q *Queries) UpsertDuplicatePair(ctx context.Context, arg UpsertDuplicatePairParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDuplicatePair, arg.BookA, arg.BookB)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
