// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeAdminsWithIdentity = `-- name: ActiveAdminsWithIdentity :one
SELECT count(*) FROM users u
WHERE u.role = 'admin' AND u.disabled_at IS NULL
  AND EXISTS (SELECT 1 FROM user_identities i WHERE i.user_id = u.id)
`

// Administrators who can sign in through an identity provider. While there
// is none, an administrator may sign in with a password even when
// passwords are turned off, so that nobody is locked out.
func (q *Queries) ActiveAdminsWithIdentity(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, activeAdminsWithIdentity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO user_identities (user_id, issuer, subject, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT (issuer, subject) DO NOTHING
RETURNING id
`

type CreateIdentityParams struct {
	UserID  uuid.UUID
	Issuer  string
	Subject string
	Email   *string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createOidcLogin = `-- name: CreateOidcLogin :exec
INSERT INTO oidc_logins (state_hash, nonce, verifier, return_to, link_user_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOidcLoginParams struct {
	StateHash  []byte
	Nonce      string
	Verifier   string
	ReturnTo   string
	LinkUserID *uuid.UUID
	ExpiresAt  time.Time
}

func (q *Queries) CreateOidcLogin(ctx context.Context, arg CreateOidcLoginParams) error {
	_, err := q.db.Exec(ctx, createOidcLogin,
		arg.StateHash,
		arg.Nonce,
		arg.Verifier,
		arg.ReturnTo,
		arg.LinkUserID,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredOidcLogins = `-- name: DeleteExpiredOidcLogins :exec
DELETE FROM oidc_logins WHERE expires_at <= $1::timestamptz
`

func (q *Queries) DeleteExpiredOidcLogins(ctx context.Context, now time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredOidcLogins, now)
	return err
}

const deleteUserIdentity = `-- name: DeleteUserIdentity :execrows
DELETE FROM user_identities WHERE id = $1 AND user_id = $2
`

type DeleteUserIdentityParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteUserIdentity(ctx context.Context, arg DeleteUserIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserIdentity, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdentityUser = `-- name: GetIdentityUser :one
SELECT u.id, u.username, u.email, u.password_hash, u.role, u.quota_bytes, u.disabled_at, u.created_at, u.updated_at, i.id AS identity_id
FROM user_identities i
JOIN users u ON u.id = i.user_id
WHERE i.issuer = $1 AND i.subject = $2
`

type GetIdentityUserParams struct {
	Issuer  string
	Subject string
}

type GetIdentityUserRow struct {
	ID           uuid.UUID
	Username     string
	Email        *string
	PasswordHash *string
	Role         string
	QuotaBytes   *int64
	DisabledAt   *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IdentityID   uuid.UUID
}

func (q *Queries) GetIdentityUser(ctx context.Context, arg GetIdentityUserParams) (GetIdentityUserRow, error) {
	row := q.db.QueryRow(ctx, getIdentityUser, arg.Issuer, arg.Subject)
	var i GetIdentityUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.QuotaBytes,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, role, quota_bytes, disabled_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.QuotaBytes,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserIdentities = `-- name: ListUserIdentities :many
SELECT id, issuer, email, created_at, last_used_at
FROM user_identities
WHERE user_id = $1
ORDER BY created_at
`

type ListUserIdentitiesRow struct {
	ID         uuid.UUID
	Issuer     string
	Email      *string
	CreatedAt  time.Time
	LastUsedAt time.Time
}

func (q *Queries) ListUserIdentities(ctx context.Context, userID uuid.UUID) ([]ListUserIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listUserIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserIdentitiesRow{}
	for rows.Next() {
		var i ListUserIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.Email,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRole = `-- name: SetRole :one
UPDATE users SET role = $2, updated_at = now() WHERE id = $1 RETURNING id, username, email, password_hash, role, quota_bytes, disabled_at, created_at, updated_at
`

type SetRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) SetRole(ctx context.Context, arg SetRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.QuotaBytes,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const takeOidcLogin = `-- name: TakeOidcLogin :one
DELETE FROM oidc_logins
WHERE state_hash = $1 AND expires_at > $2::timestamptz
RETURNING state_hash, nonce, verifier, return_to, link_user_id, expires_at
`

type TakeOidcLoginParams struct {
	StateHash []byte
	Now       time.Time
}

// A state is good once, and only until it runs out.
func (q *Queries) TakeOidcLogin(ctx context.Context, arg TakeOidcLoginParams) (OidcLogin, error) {
	row := q.db.QueryRow(ctx, takeOidcLogin, arg.StateHash, arg.Now)
	var i OidcLogin
	err := row.Scan(
		&i.StateHash,
		&i.Nonce,
		&i.Verifier,
		&i.ReturnTo,
		&i.LinkUserID,
		&i.ExpiresAt,
	)
	return i, err
}

const touchIdentity = `-- name: TouchIdentity :exec
UPDATE user_identities SET email = $2, last_used_at = now() WHERE id = $1
`

type TouchIdentityParams struct {
	ID    uuid.UUID
	Email *string
}

func (q *Queries) TouchIdentity(ctx context.Context, arg TouchIdentityParams) error {
	_, err := q.db.Exec(ctx, touchIdentity, arg.ID, arg.Email)
	return err
}

const usernameTaken = `-- name: UsernameTaken :one
SELECT EXISTS (SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UsernameTaken(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameTaken, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
