// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: libraries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addLibraryMember = `-- name: AddLibraryMember :exec
INSERT INTO library_members (library_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddLibraryMemberParams struct {
	LibraryID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) AddLibraryMember(ctx context.Context, arg AddLibraryMemberParams) error {
	_, err := q.db.Exec(ctx, addLibraryMember, arg.LibraryID, arg.UserID)
	return err
}

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO libraries (id, name, root_path, mode, writable, visibility, owner_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, root_path, mode, writable, visibility, owner_id, created_at, updated_at
`

type CreateLibraryParams struct {
	ID         uuid.UUID
	Name       string
	RootPath   string
	Mode       string
	Writable   bool
	Visibility string
	OwnerID    *uuid.UUID
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, createLibrary,
		arg.ID,
		arg.Name,
		arg.RootPath,
		arg.Mode,
		arg.Writable,
		arg.Visibility,
		arg.OwnerID,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Mode,
		&i.Writable,
		&i.Visibility,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLibrary = `-- name: DeleteLibrary :execrows
DELETE FROM libraries WHERE id = $1
`

func (q *Queries) DeleteLibrary(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLibrary, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVisibleLibrary = `-- name: GetVisibleLibrary :one
SELECT l.id, l.name, l.root_path, l.mode, l.writable, l.visibility, l.owner_id, l.created_at, l.updated_at
FROM libraries l
WHERE l.id = $1
  AND l.id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
`

type GetVisibleLibraryParams struct {
	ID      uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

func (q *Queries) GetVisibleLibrary(ctx context.Context, arg GetVisibleLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, getVisibleLibrary, arg.ID, arg.Viewer, arg.SeesAll)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Mode,
		&i.Writable,
		&i.Visibility,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLibraryMembers = `-- name: ListLibraryMembers :many
SELECT u.id, u.username, u.role, m.added_at
FROM library_members m
JOIN users u ON u.id = m.user_id
WHERE m.library_id = $1
ORDER BY lower(u.username)
`

type ListLibraryMembersRow struct {
	ID       uuid.UUID
	Username string
	Role     string
	AddedAt  time.Time
}

func (q *Queries) ListLibraryMembers(ctx context.Context, libraryID uuid.UUID) ([]ListLibraryMembersRow, error) {
	rows, err := q.db.Query(ctx, listLibraryMembers, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibraryMembersRow{}
	for rows.Next() {
		var i ListLibraryMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryRoots = `-- name: ListLibraryRoots :many
SELECT id, root_path FROM libraries
`

type ListLibraryRootsRow struct {
	ID       uuid.UUID
	RootPath string
}

// Every root, whoever may see it: a new library must not overlap any of them.
func (q *Queries) ListLibraryRoots(ctx context.Context) ([]ListLibraryRootsRow, error) {
	rows, err := q.db.Query(ctx, listLibraryRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibraryRootsRow{}
	for rows.Next() {
		var i ListLibraryRootsRow
		if err := rows.Scan(&i.ID, &i.RootPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleLibraries = `-- name: ListVisibleLibraries :many
SELECT l.id, l.name, l.root_path, l.mode, l.writable, l.visibility, l.owner_id, l.created_at, l.updated_at
FROM libraries l
WHERE l.id IN (SELECT visible_library_ids($1::uuid, $2::boolean))
ORDER BY lower(l.name)
`

type ListVisibleLibrariesParams struct {
	Viewer  uuid.UUID
	SeesAll bool
}

func (q *Queries) ListVisibleLibraries(ctx context.Context, arg ListVisibleLibrariesParams) ([]Library, error) {
	rows, err := q.db.Query(ctx, listVisibleLibraries, arg.Viewer, arg.SeesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RootPath,
			&i.Mode,
			&i.Writable,
			&i.Visibility,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLibraryMember = `-- name: RemoveLibraryMember :execrows
DELETE FROM library_members WHERE library_id = $1 AND user_id = $2
`

type RemoveLibraryMemberParams struct {
	LibraryID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveLibraryMember(ctx context.Context, arg RemoveLibraryMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeLibraryMember, arg.LibraryID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLibrary = `-- name: UpdateLibrary :one
UPDATE libraries
SET name       = COALESCE($2, name),
    visibility = COALESCE($3, visibility),
    writable   = COALESCE($4, writable),
    updated_at = now()
WHERE id = $1
RETURNING id, name, root_path, mode, writable, visibility, owner_id, created_at, updated_at
`

type UpdateLibraryParams struct {
	ID         uuid.UUID
	Name       *string
	Visibility *string
	Writable   *bool
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, updateLibrary,
		arg.ID,
		arg.Name,
		arg.Visibility,
		arg.Writable,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.Mode,
		&i.Writable,
		&i.Visibility,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
