// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merge.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const copyBookFields = `-- name: CopyBookFields :exec
UPDATE books s SET
    title               = CASE WHEN 'title' = ANY($1::text[]) THEN l.title ELSE s.title END,
    sort_title          = CASE WHEN 'title' = ANY($1::text[]) THEN l.sort_title ELSE s.sort_title END,
    title_key           = CASE WHEN 'title' = ANY($1::text[]) THEN l.title_key ELSE s.title_key END,
    subtitle            = CASE WHEN 'subtitle' = ANY($1::text[]) THEN l.subtitle ELSE s.subtitle END,
    description         = CASE WHEN 'description' = ANY($1::text[]) THEN l.description ELSE s.description END,
    language            = CASE WHEN 'language' = ANY($1::text[]) THEN l.language ELSE s.language END,
    published_on        = CASE WHEN 'published' = ANY($1::text[]) THEN l.published_on ELSE s.published_on END,
    published_precision = CASE WHEN 'published' = ANY($1::text[]) THEN l.published_precision ELSE s.published_precision END,
    publisher_id        = CASE WHEN 'publisher' = ANY($1::text[]) THEN l.publisher_id ELSE s.publisher_id END,
    series_id           = CASE WHEN 'series' = ANY($1::text[]) THEN l.series_id ELSE s.series_id END,
    series_index        = CASE WHEN 'series' = ANY($1::text[]) THEN l.series_index ELSE s.series_index END,
    page_count          = CASE WHEN 'pageCount' = ANY($1::text[]) THEN l.page_count ELSE s.page_count END,
    cover_key           = CASE WHEN 'cover' = ANY($1::text[]) THEN l.cover_key ELSE s.cover_key END,
    field_sources       = s.field_sources || coalesce(
        (SELECT jsonb_object_agg(k, v) FROM jsonb_each(l.field_sources) AS e(k, v) WHERE k = ANY($1::text[])),
        '{}'::jsonb),
    locked_fields       = ARRAY(SELECT DISTINCT f FROM unnest(s.locked_fields || ARRAY(
        SELECT lf FROM unnest(l.locked_fields) AS lf WHERE lf = ANY($1::text[]))) AS f ORDER BY f),
    updated_at          = now()
FROM books l
WHERE s.id = $2 AND l.id = $3
`

type CopyBookFieldsParams struct {
	Fields   []string
	IntoBook uuid.UUID
	FromBook uuid.UUID
}

// The fields named, from one book onto the other, with where each came
// from and whether a person locked it.
func (q *Queries) CopyBookFields(ctx context.Context, arg CopyBookFieldsParams) error {
	_, err := q.db.Exec(ctx, copyBookFields, arg.Fields, arg.IntoBook, arg.FromBook)
	return err
}

const copyContributors = `-- name: CopyContributors :exec
INSERT INTO book_contributors (book_id, author_id, role, position)
SELECT $1::uuid, c.author_id, c.role, c.position
FROM book_contributors c WHERE c.book_id = $2
`

type CopyContributorsParams struct {
	IntoBook uuid.UUID
	FromBook uuid.UUID
}

func (q *Queries) CopyContributors(ctx context.Context, arg CopyContributorsParams) error {
	_, err := q.db.Exec(ctx, copyContributors, arg.IntoBook, arg.FromBook)
	return err
}

const copyTags = `-- name: CopyTags :exec
INSERT INTO book_tags (book_id, tag_id)
SELECT $1::uuid, t.tag_id FROM book_tags t WHERE t.book_id = $2
`

type CopyTagsParams struct {
	IntoBook uuid.UUID
	FromBook uuid.UUID
}

func (q *Queries) CopyTags(ctx context.Context, arg CopyTagsParams) error {
	_, err := q.db.Exec(ctx, copyTags, arg.IntoBook, arg.FromBook)
	return err
}

const dropBookChunks = `-- name: DropBookChunks :exec
DELETE FROM book_chunks WHERE book_id = $1
`

func (q *Queries) DropBookChunks(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, dropBookChunks, bookID)
	return err
}

const dropBookMatches = `-- name: DropBookMatches :exec
DELETE FROM metadata_matches WHERE book_id = $1
`

// What looking the merged book up found, which was about its details.
func (q *Queries) DropBookMatches(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, dropBookMatches, bookID)
	return err
}

const dropContributors = `-- name: DropContributors :exec
DELETE FROM book_contributors WHERE book_id = $1
`

func (q *Queries) DropContributors(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, dropContributors, bookID)
	return err
}

const dropTags = `-- name: DropTags :exec
DELETE FROM book_tags WHERE book_id = $1
`

func (q *Queries) DropTags(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, dropTags, bookID)
	return err
}

const followMerges = `-- name: FollowMerges :one
WITH RECURSIVE chain AS (
    SELECT s.id, s.merged_into_id, s.deleted_at, 0 AS depth FROM books s WHERE s.id = $1
    UNION ALL
    SELECT b.id, b.merged_into_id, b.deleted_at, c.depth + 1
    FROM books b JOIN chain c ON b.id = c.merged_into_id
    WHERE c.depth < 20)
SELECT chain.id FROM chain WHERE chain.deleted_at IS NULL ORDER BY chain.depth LIMIT 1
`

// The book a merged one lives on as, through any merges after.
func (q *Queries) FollowMerges(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, followMerges, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const forwardMergedBooks = `-- name: ForwardMergedBooks :exec
UPDATE books SET merged_into_id = $1 WHERE merged_into_id = $2
`

type ForwardMergedBooksParams struct {
	IntoBook *uuid.UUID
	FromBook *uuid.UUID
}

// Books merged into the merged book before lead to the surviving one now.
func (q *Queries) ForwardMergedBooks(ctx context.Context, arg ForwardMergedBooksParams) error {
	_, err := q.db.Exec(ctx, forwardMergedBooks, arg.IntoBook, arg.FromBook)
	return err
}

const listLiveBookFiles = `-- name: ListLiveBookFiles :many
SELECT id FROM book_files
WHERE book_id = $1 AND missing_at IS NULL AND trashed_at IS NULL
ORDER BY id
`

// The book's files that are in their folders: neither missing nor trashed.
func (q *Queries) ListLiveBookFiles(ctx context.Context, bookID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLiveBookFiles, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBooksForMerge = `-- name: LockBooksForMerge :many
SELECT b.id, b.library_id, b.placeholder
FROM books b
WHERE b.id = ANY($1::uuid[]) AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids($2::uuid, $3::boolean))
ORDER BY b.id
FOR UPDATE OF b
`

type LockBooksForMergeParams struct {
	Ids     []uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

type LockBooksForMergeRow struct {
	ID          uuid.UUID
	LibraryID   uuid.UUID
	Placeholder bool
}

// Both books, in ID order so that two merges of the same pair wait for
// each other rather than deadlock, if the viewer sees them.
func (q *Queries) LockBooksForMerge(ctx context.Context, arg LockBooksForMergeParams) ([]LockBooksForMergeRow, error) {
	rows, err := q.db.Query(ctx, lockBooksForMerge, arg.Ids, arg.Viewer, arg.SeesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockBooksForMergeRow{}
	for rows.Next() {
		var i LockBooksForMergeRow
		if err := rows.Scan(&i.ID, &i.LibraryID, &i.Placeholder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeBookIdentifiers = `-- name: MergeBookIdentifiers :exec
WITH moved AS (
    DELETE FROM book_identifiers x WHERE x.book_id = $2 AND x.file_id IS NULL
    RETURNING x.type, x.value)
INSERT INTO book_identifiers (book_id, type, value)
SELECT $1, type, value FROM moved
ON CONFLICT DO NOTHING
`

type MergeBookIdentifiersParams struct {
	IntoBook uuid.UUID
	FromBook uuid.UUID
}

// The book's own identifiers, those of no file, joined to the other's.
func (q *Queries) MergeBookIdentifiers(ctx context.Context, arg MergeBookIdentifiersParams) error {
	_, err := q.db.Exec(ctx, mergeBookIdentifiers, arg.IntoBook, arg.FromBook)
	return err
}

const mergeCollectionItems = `-- name: MergeCollectionItems :exec
WITH moved AS (
    DELETE FROM collection_items x WHERE x.book_id = $2
    RETURNING collection_id, position, added_at)
INSERT INTO collection_items (collection_id, book_id, position, added_at)
SELECT collection_id, $1, position, added_at FROM moved
ON CONFLICT DO NOTHING
`

type MergeCollectionItemsParams struct {
	IntoBook uuid.UUID
	FromBook uuid.UUID
}

// The shelves the book is on; where both are, the surviving book's place.
func (q *Queries) MergeCollectionItems(ctx context.Context, arg MergeCollectionItemsParams) error {
	_, err := q.db.Exec(ctx, mergeCollectionItems, arg.IntoBook, arg.FromBook)
	return err
}

const mergeReadingProgress = `-- name: MergeReadingProgress :exec
WITH moved AS (
    DELETE FROM reading_progress x WHERE x.book_id = $2
    RETURNING user_id, medium, file_id, locator, fraction, chapter, page, position_ms, client_id, updated_at)
INSERT INTO reading_progress AS p (user_id, book_id, medium, file_id, locator, fraction, chapter, page, position_ms, client_id, updated_at)
SELECT user_id, $1, medium, file_id, locator, fraction, chapter, page, position_ms, client_id, updated_at FROM moved
ON CONFLICT (user_id, book_id, medium) DO UPDATE SET
    file_id = EXCLUDED.file_id, locator = EXCLUDED.locator, fraction = EXCLUDED.fraction,
    chapter = EXCLUDED.chapter, page = EXCLUDED.page, position_ms = EXCLUDED.position_ms,
    client_id = EXCLUDED.client_id, updated_at = EXCLUDED.updated_at
WHERE EXCLUDED.fraction > p.fraction
`

type MergeReadingProgressParams struct {
	IntoBook uuid.UUID
	FromBook uuid.UUID
}

// Everyone's place in the book, per medium: the further one.
func (q *Queries) MergeReadingProgress(ctx context.Context, arg MergeReadingProgressParams) error {
	_, err := q.db.Exec(ctx, mergeReadingProgress, arg.IntoBook, arg.FromBook)
	return err
}

const mergeRelations = `-- name: MergeRelations :exec
WITH moved AS (
    DELETE FROM book_relations r WHERE $2 IN (r.book_a, r.book_b)
    RETURNING CASE WHEN r.book_a = $2 THEN r.book_b ELSE r.book_a END AS other, r.kind)
INSERT INTO book_relations (book_a, book_b, kind)
SELECT least($1::uuid, other), greatest($1::uuid, other), kind
FROM moved WHERE other <> $1
ON CONFLICT DO NOTHING
`

type MergeRelationsParams struct {
	IntoBook uuid.UUID
	FromBook uuid.UUID
}

// The book's links to its other editions and translations; one to the
// surviving book itself goes.
func (q *Queries) MergeRelations(ctx context.Context, arg MergeRelationsParams) error {
	_, err := q.db.Exec(ctx, mergeRelations, arg.IntoBook, arg.FromBook)
	return err
}

const mergeUserBooks = `-- name: MergeUserBooks :exec
WITH moved AS (
    DELETE FROM user_books x WHERE x.book_id = $2
    RETURNING user_id, status, rating, started_on, finished_on, updated_at)
INSERT INTO user_books AS u (user_id, book_id, status, rating, started_on, finished_on, updated_at)
SELECT user_id, $1, status, rating, started_on, finished_on, updated_at FROM moved
ON CONFLICT (user_id, book_id) DO UPDATE SET
    status = CASE WHEN array_position(ARRAY['unread', 'wishlist', 'abandoned', 'reading', 'completed'], EXCLUDED.status)
                     > array_position(ARRAY['unread', 'wishlist', 'abandoned', 'reading', 'completed'], u.status)
                  THEN EXCLUDED.status ELSE u.status END,
    rating      = coalesce(u.rating, EXCLUDED.rating),
    started_on  = least(u.started_on, EXCLUDED.started_on),
    finished_on = greatest(u.finished_on, EXCLUDED.finished_on),
    updated_at  = greatest(u.updated_at, EXCLUDED.updated_at)
`

type MergeUserBooksParams struct {
	IntoBook uuid.UUID
	FromBook uuid.UUID
}

// Everyone's standing with the book: the further status, their rating where
// the surviving book has none, the earliest start and the latest finish.
func (q *Queries) MergeUserBooks(ctx context.Context, arg MergeUserBooksParams) error {
	_, err := q.db.Exec(ctx, mergeUserBooks, arg.IntoBook, arg.FromBook)
	return err
}

const moveNotifications = `-- name: MoveNotifications :exec
UPDATE notifications SET book_id = $1 WHERE book_id = $2
`

type MoveNotificationsParams struct {
	IntoBook *uuid.UUID
	FromBook *uuid.UUID
}

func (q *Queries) MoveNotifications(ctx context.Context, arg MoveNotificationsParams) error {
	_, err := q.db.Exec(ctx, moveNotifications, arg.IntoBook, arg.FromBook)
	return err
}

const moveReadingHistory = `-- name: MoveReadingHistory :exec
WITH sessions AS (
    UPDATE reading_sessions rs SET book_id = $1 WHERE rs.book_id = $2)
UPDATE reading_finishes rf SET book_id = $1 WHERE rf.book_id = $2
`

type MoveReadingHistoryParams struct {
	IntoBook uuid.UUID
	FromBook uuid.UUID
}

func (q *Queries) MoveReadingHistory(ctx context.Context, arg MoveReadingHistoryParams) error {
	_, err := q.db.Exec(ctx, moveReadingHistory, arg.IntoBook, arg.FromBook)
	return err
}

const progressByFraction = `-- name: ProgressByFraction :exec
UPDATE reading_progress p
SET locator = 'fraction:' || p.fraction::text, file_id = NULL
WHERE p.book_id = $1 AND p.locator NOT LIKE 'fraction:%'
  AND (p.file_id IS NULL OR p.file_id NOT IN (
      SELECT f.id FROM book_files f WHERE f.book_id = $1 AND f.trashed_at IS NULL AND f.missing_at IS NULL))
`

// Places read in no file the book still has in its folder say only how
// far: a locator means nothing in another file, a fraction does.
func (q *Queries) ProgressByFraction(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, progressByFraction, bookID)
	return err
}

const relateBooks = `-- name: RelateBooks :exec
INSERT INTO book_relations (book_a, book_b, kind)
VALUES (least($1::uuid, $2::uuid), greatest($1::uuid, $2::uuid), $3)
ON CONFLICT (book_a, book_b) DO UPDATE SET kind = EXCLUDED.kind
`

type RelateBooksParams struct {
	One   uuid.UUID
	Other uuid.UUID
	Kind  string
}

// The two as editions or translations of one work, as a person says.
func (q *Queries) RelateBooks(ctx context.Context, arg RelateBooksParams) error {
	_, err := q.db.Exec(ctx, relateBooks, arg.One, arg.Other, arg.Kind)
	return err
}

const setHeldFiles = `-- name: SetHeldFiles :exec
UPDATE books b SET placeholder = false
WHERE b.id = $1 AND b.placeholder AND EXISTS (SELECT 1 FROM book_files f WHERE f.book_id = b.id)
`

// A wish whose book now has files is in the library.
func (q *Queries) SetHeldFiles(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setHeldFiles, id)
	return err
}

const setPairReplaced = `-- name: SetPairReplaced :exec
UPDATE duplicate_pairs SET state = 'replaced', updated_at = now()
WHERE book_a = least($1::uuid, $2::uuid)
  AND book_b = greatest($1::uuid, $2::uuid)
`

type SetPairReplacedParams struct {
	IntoBook uuid.UUID
	FromBook uuid.UUID
}

func (q *Queries) SetPairReplaced(ctx context.Context, arg SetPairReplacedParams) error {
	_, err := q.db.Exec(ctx, setPairReplaced, arg.IntoBook, arg.FromBook)
	return err
}

const settleMergedPairs = `-- name: SettleMergedPairs :exec
WITH merged AS (
    UPDATE duplicate_pairs m SET state = 'merged', updated_at = now()
    WHERE m.book_a = least($2::uuid, $1::uuid)
      AND m.book_b = greatest($2::uuid, $1::uuid))
DELETE FROM duplicate_pairs d
WHERE d.state = 'open' AND $1 IN (d.book_a, d.book_b)
  AND NOT (d.book_a = least($2::uuid, $1::uuid)
           AND d.book_b = greatest($2::uuid, $1::uuid))
`

type SettleMergedPairsParams struct {
	FromBook uuid.UUID
	IntoBook uuid.UUID
}

// The pair of the two is merged; the merged book's other open pairs go,
// and the surviving book's are found again by its check.
func (q *Queries) SettleMergedPairs(ctx context.Context, arg SettleMergedPairsParams) error {
	_, err := q.db.Exec(ctx, settleMergedPairs, arg.FromBook, arg.IntoBook)
	return err
}
