// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countReviewBooks = `-- name: CountReviewBooks :one
SELECT count(DISTINCT b.id)
FROM metadata_matches m
JOIN books b ON b.id = m.book_id
WHERE m.state = 'pending'
  AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($1::uuid, $2::boolean))
`

type CountReviewBooksParams struct {
	Viewer  uuid.UUID
	SeesAll bool
}

func (q *Queries) CountReviewBooks(ctx context.Context, arg CountReviewBooksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewBooks, arg.Viewer, arg.SeesAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dismissOtherMatches = `-- name: DismissOtherMatches :exec
UPDATE metadata_matches SET state = 'dismissed', updated_at = now()
WHERE book_id = $1 AND id <> $2 AND state = 'pending'
`

type DismissOtherMatchesParams struct {
	BookID uuid.UUID
	ID     uuid.UUID
}

// Once one match of a book is taken, the others it waited with are done.
func (q *Queries) DismissOtherMatches(ctx context.Context, arg DismissOtherMatchesParams) error {
	_, err := q.db.Exec(ctx, dismissOtherMatches, arg.BookID, arg.ID)
	return err
}

const getProviderRecord = `-- name: GetProviderRecord :one
SELECT status, body
FROM provider_records
WHERE provider = $1 AND request_key = $2 AND expires_at > now()
`

type GetProviderRecordParams struct {
	Provider   string
	RequestKey []byte
}

type GetProviderRecordRow struct {
	Status int32
	Body   []byte
}

func (q *Queries) GetProviderRecord(ctx context.Context, arg GetProviderRecordParams) (GetProviderRecordRow, error) {
	row := q.db.QueryRow(ctx, getProviderRecord, arg.Provider, arg.RequestKey)
	var i GetProviderRecordRow
	err := row.Scan(&i.Status, &i.Body)
	return i, err
}

const getVisibleMatch = `-- name: GetVisibleMatch :one
SELECT m.id, m.book_id, m.provider, m.record_id, m.score, m.record, m.state, m.created_at, m.updated_at
FROM metadata_matches m
JOIN books b ON b.id = m.book_id
WHERE m.id = $1
  AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($2::uuid, $3::boolean))
`

type GetVisibleMatchParams struct {
	ID      uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

func (q *Queries) GetVisibleMatch(ctx context.Context, arg GetVisibleMatchParams) (MetadataMatch, error) {
	row := q.db.QueryRow(ctx, getVisibleMatch, arg.ID, arg.Viewer, arg.SeesAll)
	var i MetadataMatch
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Provider,
		&i.RecordID,
		&i.Score,
		&i.Record,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingMatches = `-- name: ListPendingMatches :many
SELECT id, book_id, provider, record_id, score, record, state, created_at, updated_at FROM metadata_matches
WHERE book_id = ANY($1::uuid[]) AND state = 'pending'
ORDER BY book_id, score DESC, id
`

func (q *Queries) ListPendingMatches(ctx context.Context, bookIds []uuid.UUID) ([]MetadataMatch, error) {
	rows, err := q.db.Query(ctx, listPendingMatches, bookIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetadataMatch{}
	for rows.Next() {
		var i MetadataMatch
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Provider,
			&i.RecordID,
			&i.Score,
			&i.Record,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewBooks = `-- name: ListReviewBooks :many
SELECT b.id
FROM metadata_matches m
JOIN books b ON b.id = m.book_id
WHERE m.state = 'pending'
  AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($1::uuid, $2::boolean))
GROUP BY b.id
ORDER BY min(m.created_at), b.id
LIMIT $3
`

type ListReviewBooksParams struct {
	Viewer   uuid.UUID
	SeesAll  bool
	MaxBooks int32
}

// The books with matches waiting, those waiting longest first, of the
// libraries the viewer may see.
func (q *Queries) ListReviewBooks(ctx context.Context, arg ListReviewBooksParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listReviewBooks, arg.Viewer, arg.SeesAll, arg.MaxBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putProviderRecord = `-- name: PutProviderRecord :exec
INSERT INTO provider_records (provider, request_key, url, status, body, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (provider, request_key) DO UPDATE
SET url = EXCLUDED.url, status = EXCLUDED.status, body = EXCLUDED.body,
    fetched_at = now(), expires_at = EXCLUDED.expires_at
`

type PutProviderRecordParams struct {
	Provider   string
	RequestKey []byte
	Url        string
	Status     int32
	Body       []byte
	ExpiresAt  time.Time
}

func (q *Queries) PutProviderRecord(ctx context.Context, arg PutProviderRecordParams) error {
	_, err := q.db.Exec(ctx, putProviderRecord,
		arg.Provider,
		arg.RequestKey,
		arg.Url,
		arg.Status,
		arg.Body,
		arg.ExpiresAt,
	)
	return err
}

const recordMatch = `-- name: RecordMatch :one
INSERT INTO metadata_matches (book_id, provider, record_id, score, record, state)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (book_id, provider, record_id) DO UPDATE
SET score = EXCLUDED.score, record = EXCLUDED.record, updated_at = now(),
    state = CASE WHEN metadata_matches.state = 'pending' THEN EXCLUDED.state ELSE metadata_matches.state END
RETURNING (xmax = 0)::boolean AS inserted
`

type RecordMatchParams struct {
	BookID   uuid.UUID
	Provider string
	RecordID string
	Score    float64
	Record   []byte
	State    string
}

// A match found again keeps what became of it: a dismissed one is not
// brought back, an applied one not made pending. inserted is false for a
// match that was there already.
func (q *Queries) RecordMatch(ctx context.Context, arg RecordMatchParams) (bool, error) {
	row := q.db.QueryRow(ctx, recordMatch,
		arg.BookID,
		arg.Provider,
		arg.RecordID,
		arg.Score,
		arg.Record,
		arg.State,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const setMatchState = `-- name: SetMatchState :exec
UPDATE metadata_matches SET state = $2, updated_at = now() WHERE id = $1
`

type SetMatchStateParams struct {
	ID    uuid.UUID
	State string
}

func (q *Queries) SetMatchState(ctx context.Context, arg SetMatchStateParams) error {
	_, err := q.db.Exec(ctx, setMatchState, arg.ID, arg.State)
	return err
}
