// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package sqlc

import (
	"context"
	"time"
)

const getProviderRecord = `-- name: GetProviderRecord :one
SELECT status, body
FROM provider_records
WHERE provider = $1 AND request_key = $2 AND expires_at > now()
`

type GetProviderRecordParams struct {
	Provider   string
	RequestKey []byte
}

type GetProviderRecordRow struct {
	Status int32
	Body   []byte
}

func (q *Queries) GetProviderRecord(ctx context.Context, arg GetProviderRecordParams) (GetProviderRecordRow, error) {
	row := q.db.QueryRow(ctx, getProviderRecord, arg.Provider, arg.RequestKey)
	var i GetProviderRecordRow
	err := row.Scan(&i.Status, &i.Body)
	return i, err
}

const putProviderRecord = `-- name: PutProviderRecord :exec
INSERT INTO provider_records (provider, request_key, url, status, body, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (provider, request_key) DO UPDATE
SET url = EXCLUDED.url, status = EXCLUDED.status, body = EXCLUDED.body,
    fetched_at = now(), expires_at = EXCLUDED.expires_at
`

type PutProviderRecordParams struct {
	Provider   string
	RequestKey []byte
	Url        string
	Status     int32
	Body       []byte
	ExpiresAt  time.Time
}

func (q *Queries) PutProviderRecord(ctx context.Context, arg PutProviderRecordParams) error {
	_, err := q.db.Exec(ctx, putProviderRecord,
		arg.Provider,
		arg.RequestKey,
		arg.Url,
		arg.Status,
		arg.Body,
		arg.ExpiresAt,
	)
	return err
}
