// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type AudioChapter struct {
	FileID   uuid.UUID
	Position int32
	Title    string
	StartMs  int64
	EndMs    int64
}

type Author struct {
	ID        uuid.UUID
	Name      string
	SortName  string
	NameKey   string
	CreatedAt time.Time
}

type Book struct {
	ID                 uuid.UUID
	LibraryID          uuid.UUID
	Title              string
	SortTitle          string
	TitleKey           string
	Subtitle           *string
	Description        *string
	Language           *string
	PublishedOn        *time.Time
	PublishedPrecision *string
	PublisherID        *uuid.UUID
	SeriesID           *uuid.UUID
	SeriesIndex        *float64
	ExternalRating     *float64
	PageCount          *int32
	CoverKey           *string
	LockedFields       []string
	FieldSources       []byte
	MergedIntoID       *uuid.UUID
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	PrimaryTextFileID  *uuid.UUID
	AuthorSort         string
}

type BookContributor struct {
	BookID   uuid.UUID
	AuthorID uuid.UUID
	Role     string
	Position int32
}

type BookFile struct {
	ID             uuid.UUID
	BookID         uuid.UUID
	LibraryID      uuid.UUID
	Kind           string
	Format         string
	RelPath        string
	SizeBytes      int64
	ModifiedAt     time.Time
	Sha256         []byte
	OriginalSha256 []byte
	ContentSha256  []byte
	PartIndex      *int32
	DurationMs     *int64
	PageCount      *int32
	PagesEstimated bool
	HasText        *bool
	Drm            bool
	ExtractState   string
	ExtractError   *string
	UploadedBy     *uuid.UUID
	MissingAt      *time.Time
	TrashedAt      *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TrackNumber    *int32
	DiscNumber     *int32
}

type BookIdentifier struct {
	ID     uuid.UUID
	BookID uuid.UUID
	FileID *uuid.UUID
	Type   string
	Value  string
}

type BookRelation struct {
	BookA uuid.UUID
	BookB uuid.UUID
	Kind  string
}

type BookTag struct {
	BookID uuid.UUID
	TagID  uuid.UUID
}

type BulkChange struct {
	ID         uuid.UUID
	CreatedBy  uuid.UUID
	SeesAll    bool
	Action     string
	Change     []byte
	CreatedAt  time.Time
	FinishedAt *time.Time
}

type BulkChangeBook struct {
	BulkChangeID uuid.UUID
	Position     int32
	BookID       uuid.UUID
	Outcome      *string
	Message      *string
	Skipped      []string
}

type Library struct {
	ID         uuid.UUID
	Name       string
	RootPath   string
	Mode       string
	Writable   bool
	Visibility string
	OwnerID    *uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type LibraryMember struct {
	LibraryID uuid.UUID
	UserID    uuid.UUID
	AddedAt   time.Time
}

type LibraryScan struct {
	ID            uuid.UUID
	LibraryID     uuid.UUID
	State         string
	RequestedBy   *uuid.UUID
	RequestedAt   time.Time
	JobID         *int64
	StartedAt     *time.Time
	FinishedAt    *time.Time
	FilesSeen     int32
	FilesAdded    int32
	FilesChanged  int32
	FilesMoved    int32
	FilesRestored int32
	FilesMissing  int32
	FilesSkipped  int32
	BooksAdded    int32
	Error         *string
}

type MetadataMatch struct {
	ID        uuid.UUID
	BookID    uuid.UUID
	Provider  string
	RecordID  string
	Score     float64
	Record    []byte
	State     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ProviderRecord struct {
	Provider   string
	RequestKey []byte
	Url        string
	Status     int32
	Body       []byte
	FetchedAt  time.Time
	ExpiresAt  time.Time
}

type Publisher struct {
	ID      uuid.UUID
	Name    string
	NameKey string
}

type Series struct {
	ID        uuid.UUID
	Name      string
	NameKey   string
	CreatedAt time.Time
}

type Session struct {
	TokenHash  []byte
	UserID     uuid.UUID
	UserAgent  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	ID         uuid.UUID
}

type Setting struct {
	Key       string
	Value     *string
	Sealed    []byte
	UpdatedAt time.Time
	UpdatedBy *uuid.UUID
}

type StorageUse struct {
	UserID    *uuid.UUID
	UsedBytes int64
}

type Tag struct {
	ID      uuid.UUID
	Name    string
	NameKey string
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        *string
	PasswordHash *string
	Role         string
	QuotaBytes   *int64
	DisabledAt   *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
