// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::int
FROM notifications n
LEFT JOIN books b ON b.id = n.book_id
WHERE n.user_id = $1::uuid AND n.read_at IS NULL
  AND (n.book_id IS NULL OR (b.deleted_at IS NULL
       AND b.library_id IN (SELECT visible_library_ids($1::uuid, $2::boolean))))
`

type CountUnreadNotificationsParams struct {
	Viewer  uuid.UUID
	SeesAll bool
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.Viewer, arg.SeesAll)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, kind, data, link, book_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateNotificationParams struct {
	UserID uuid.UUID
	Kind   string
	Data   []byte
	Link   string
	BookID *uuid.UUID
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Kind,
		arg.Data,
		arg.Link,
		arg.BookID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.kind, n.data, n.link, n.book_id, n.created_at, n.read_at
FROM notifications n
LEFT JOIN books b ON b.id = n.book_id
WHERE n.user_id = $1::uuid
  AND (n.book_id IS NULL OR (b.deleted_at IS NULL
       AND b.library_id IN (SELECT visible_library_ids($1::uuid, $2::boolean))))
  AND ($3::timestamptz IS NULL OR (n.created_at, n.id) < ($3::timestamptz, $4::uuid))
ORDER BY n.created_at DESC, n.id DESC
LIMIT $5
`

type ListNotificationsParams struct {
	Viewer   uuid.UUID
	SeesAll  bool
	BeforeAt *time.Time
	BeforeID *uuid.UUID
	MaxRows  int32
}

type ListNotificationsRow struct {
	ID        uuid.UUID
	Kind      string
	Data      []byte
	Link      string
	BookID    *uuid.UUID
	CreatedAt time.Time
	ReadAt    *time.Time
}

// The viewer's notifications, newest first, after the cursor; one about a
// book is left out while its library may not be seen.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.Viewer,
		arg.SeesAll,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Data,
			&i.Link,
			&i.BookID,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read_at = now()
WHERE user_id = $1::uuid AND read_at IS NULL
  AND ($2::uuid[] IS NULL OR id = ANY($2::uuid[]))
`

type MarkNotificationsReadParams struct {
	Viewer uuid.UUID
	Ids    []uuid.UUID
}

// Marks the viewer's notifications among ids, or all of them when ids is
// NULL, as read.
func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, arg.Viewer, arg.Ids)
	return err
}
