// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: placeholders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const bookIsUntouched = `-- name: BookIsUntouched :one
SELECT COALESCE(NOT b.placeholder
   AND cardinality(b.locked_fields) = 0
   AND NOT EXISTS (SELECT 1 FROM jsonb_each_text(b.field_sources) s
                   WHERE s.value NOT LIKE 'file:%' AND s.value <> 'filename')
   AND NOT EXISTS (SELECT 1 FROM user_books u WHERE u.book_id = b.id)
   AND NOT EXISTS (SELECT 1 FROM reading_progress p WHERE p.book_id = b.id)
   AND NOT EXISTS (SELECT 1 FROM collection_items c WHERE c.book_id = b.id), false)::boolean AS untouched
FROM books b
WHERE b.id = $1
FOR UPDATE OF b
`

// Whether a book is only what a scan made of its files: no person or
// provider set anything on it, and nobody has read, rated, wished or
// shelved it.
func (q *Queries) BookIsUntouched(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, bookIsUntouched, id)
	var untouched bool
	err := row.Scan(&untouched)
	return untouched, err
}

const findPlaceholder = `-- name: FindPlaceholder :one
SELECT b.id
FROM books b
WHERE b.library_id = $1
  AND b.placeholder
  AND b.deleted_at IS NULL
  AND (
    EXISTS (SELECT 1 FROM book_identifiers i
            WHERE i.book_id = b.id AND i.type = 'isbn' AND i.value = ANY($2::text[]))
    OR (b.title_key = $3
        AND EXISTS (SELECT 1 FROM book_contributors c JOIN authors a ON a.id = c.author_id
                    WHERE c.book_id = b.id AND c.role = 'author'
                      AND a.name_key = ANY($4::text[])))
  )
ORDER BY (EXISTS (SELECT 1 FROM book_identifiers i
                  WHERE i.book_id = b.id AND i.type = 'isbn' AND i.value = ANY($2::text[]))) DESC,
         b.created_at, b.id
LIMIT 1
FOR UPDATE
`

type FindPlaceholderParams struct {
	LibraryID  uuid.UUID
	Isbns      []string
	TitleKey   string
	AuthorKeys []string
}

// The placeholder in the library that is the book described: one that
// shares an ISBN with it, or else has its title and one of its authors.
// The one wished for first wins.
func (q *Queries) FindPlaceholder(ctx context.Context, arg FindPlaceholderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findPlaceholder,
		arg.LibraryID,
		arg.Isbns,
		arg.TitleKey,
		arg.AuthorKeys,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const isLibraryVisible = `-- name: IsLibraryVisible :one
SELECT EXISTS (
    SELECT 1 FROM libraries l
    WHERE l.id = $1
      AND l.id IN (SELECT visible_library_ids FROM visible_library_ids($2::uuid, $3::boolean))
)
`

type IsLibraryVisibleParams struct {
	ID      uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

func (q *Queries) IsLibraryVisible(ctx context.Context, arg IsLibraryVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, isLibraryVisible, arg.ID, arg.Viewer, arg.SeesAll)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const mergeBookInto = `-- name: MergeBookInto :exec
UPDATE books SET deleted_at = now(), merged_into_id = $1 WHERE id = $2
`

type MergeBookIntoParams struct {
	IntoBook *uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) MergeBookInto(ctx context.Context, arg MergeBookIntoParams) error {
	_, err := q.db.Exec(ctx, mergeBookInto, arg.IntoBook, arg.ID)
	return err
}

const moveBookFiles = `-- name: MoveBookFiles :exec
UPDATE book_files SET book_id = $1 WHERE book_id = $2
`

type MoveBookFilesParams struct {
	ToBook   uuid.UUID
	FromBook uuid.UUID
}

func (q *Queries) MoveBookFiles(ctx context.Context, arg MoveBookFilesParams) error {
	_, err := q.db.Exec(ctx, moveBookFiles, arg.ToBook, arg.FromBook)
	return err
}

const moveFileIdentifiers = `-- name: MoveFileIdentifiers :exec
UPDATE book_identifiers i SET book_id = $1
WHERE i.book_id = $2 AND i.file_id IS NOT NULL
`

type MoveFileIdentifiersParams struct {
	ToBook   uuid.UUID
	FromBook uuid.UUID
}

// The identifiers a book's files carry, ahead of the files themselves.
func (q *Queries) MoveFileIdentifiers(ctx context.Context, arg MoveFileIdentifiersParams) error {
	_, err := q.db.Exec(ctx, moveFileIdentifiers, arg.ToBook, arg.FromBook)
	return err
}

const setPlaceholder = `-- name: SetPlaceholder :exec
UPDATE books SET placeholder = $2 WHERE id = $1
`

type SetPlaceholderParams struct {
	ID          uuid.UUID
	Placeholder bool
}

func (q *Queries) SetPlaceholder(ctx context.Context, arg SetPlaceholderParams) error {
	_, err := q.db.Exec(ctx, setPlaceholder, arg.ID, arg.Placeholder)
	return err
}
