// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activityTotals = `-- name: ActivityTotals :many
SELECT s.medium,
       sum(extract(epoch FROM s.ended_at - s.started_at))::bigint AS seconds,
       sum(CASE WHEN s.medium = 'ebook'
                THEN greatest(s.to_fraction - s.from_fraction, 0) * COALESCE(f.page_count, b.page_count, 0)
                ELSE 0 END)::double precision AS pages,
       bool_or(s.medium = 'ebook' AND f.page_count IS NOT NULL AND f.pages_estimated) AS estimated
FROM reading_sessions s
JOIN books b ON b.id = s.book_id
LEFT JOIN book_files f ON f.id = b.primary_text_file_id
WHERE s.user_id = $1
  AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($1::uuid, $2::boolean))
GROUP BY s.medium
ORDER BY s.medium
`

type ActivityTotalsParams struct {
	UserID  uuid.UUID
	SeesAll bool
}

type ActivityTotalsRow struct {
	Medium    string
	Seconds   int64
	Pages     float64
	Estimated bool
}

// The same, over all time, per medium.
func (q *Queries) ActivityTotals(ctx context.Context, arg ActivityTotalsParams) ([]ActivityTotalsRow, error) {
	rows, err := q.db.Query(ctx, activityTotals, arg.UserID, arg.SeesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityTotalsRow{}
	for rows.Next() {
		var i ActivityTotalsRow
		if err := rows.Scan(
			&i.Medium,
			&i.Seconds,
			&i.Pages,
			&i.Estimated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addFinish = `-- name: AddFinish :exec
INSERT INTO reading_finishes (user_id, book_id, medium) VALUES ($1, $2, $3)
`

type AddFinishParams struct {
	UserID uuid.UUID
	BookID uuid.UUID
	Medium string
}

func (q *Queries) AddFinish(ctx context.Context, arg AddFinishParams) error {
	_, err := q.db.Exec(ctx, addFinish, arg.UserID, arg.BookID, arg.Medium)
	return err
}

const countFinishes = `-- name: CountFinishes :one
SELECT count(*) FROM reading_finishes WHERE user_id = $1 AND book_id = $2
`

type CountFinishesParams struct {
	UserID uuid.UUID
	BookID uuid.UUID
}

func (q *Queries) CountFinishes(ctx context.Context, arg CountFinishesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFinishes, arg.UserID, arg.BookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dailyActivity = `-- name: DailyActivity :many
SELECT (s.started_at AT TIME ZONE $1::text)::date AS day,
       s.medium,
       sum(extract(epoch FROM s.ended_at - s.started_at))::bigint AS seconds,
       sum(CASE WHEN s.medium = 'ebook'
                THEN greatest(s.to_fraction - s.from_fraction, 0) * COALESCE(f.page_count, b.page_count, 0)
                ELSE 0 END)::double precision AS pages,
       bool_or(s.medium = 'ebook' AND f.page_count IS NOT NULL AND f.pages_estimated) AS estimated
FROM reading_sessions s
JOIN books b ON b.id = s.book_id
LEFT JOIN book_files f ON f.id = b.primary_text_file_id
WHERE s.user_id = $2
  AND s.started_at >= $3
  AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($2::uuid, $4::boolean))
GROUP BY 1, 2
ORDER BY 1, 2
`

type DailyActivityParams struct {
	Tz      string
	UserID  uuid.UUID
	Since   time.Time
	SeesAll bool
}

type DailyActivityRow struct {
	Day       time.Time
	Medium    string
	Seconds   int64
	Pages     float64
	Estimated bool
}

// What a person read and listened to per day of their time zone since a
// time, of books they may still see. Pages are the share of the book a
// session covered times its page count: its main text file's, or the
// book's; estimated says the file's was worked out from its text.
func (q *Queries) DailyActivity(ctx context.Context, arg DailyActivityParams) ([]DailyActivityRow, error) {
	rows, err := q.db.Query(ctx, dailyActivity,
		arg.Tz,
		arg.UserID,
		arg.Since,
		arg.SeesAll,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyActivityRow{}
	for rows.Next() {
		var i DailyActivityRow
		if err := rows.Scan(
			&i.Day,
			&i.Medium,
			&i.Seconds,
			&i.Pages,
			&i.Estimated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const extendSession = `-- name: ExtendSession :execrows
UPDATE reading_sessions
SET ended_at = now(), to_fraction = $1
WHERE id = (
    SELECT s.id FROM reading_sessions s
    WHERE s.user_id = $2 AND s.book_id = $3 AND s.medium = $4
      AND s.client_id = $5 AND s.ended_at > now() - make_interval(secs => $6::double precision)
    ORDER BY s.ended_at DESC
    LIMIT 1
)
`

type ExtendSessionParams struct {
	Fraction   float64
	UserID     uuid.UUID
	BookID     uuid.UUID
	Medium     string
	ClientID   string
	GapSeconds float64
}

// The client's session goes on if it wrote recently.
func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendSession,
		arg.Fraction,
		arg.UserID,
		arg.BookID,
		arg.Medium,
		arg.ClientID,
		arg.GapSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fileOfBook = `-- name: FileOfBook :one
SELECT EXISTS (SELECT 1 FROM book_files WHERE id = $1 AND book_id = $2)
`

type FileOfBookParams struct {
	ID     uuid.UUID
	BookID uuid.UUID
}

func (q *Queries) FileOfBook(ctx context.Context, arg FileOfBookParams) (bool, error) {
	row := q.db.QueryRow(ctx, fileOfBook, arg.ID, arg.BookID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const finishesByYear = `-- name: FinishesByYear :many
SELECT extract(year FROM rf.finished_at AT TIME ZONE $1::text)::int AS year,
       count(*) AS finishes,
       count(DISTINCT rf.book_id) AS books
FROM reading_finishes rf
JOIN books b ON b.id = rf.book_id
WHERE rf.user_id = $2
  AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($2::uuid, $3::boolean))
GROUP BY 1
ORDER BY 1 DESC
`

type FinishesByYearParams struct {
	Tz      string
	UserID  uuid.UUID
	SeesAll bool
}

type FinishesByYearRow struct {
	Year     int32
	Finishes int64
	Books    int64
}

// Every time a book was read to its end counts, so a book read twice in a
// year counts twice there; books is how many different ones.
func (q *Queries) FinishesByYear(ctx context.Context, arg FinishesByYearParams) ([]FinishesByYearRow, error) {
	rows, err := q.db.Query(ctx, finishesByYear, arg.Tz, arg.UserID, arg.SeesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinishesByYearRow{}
	for rows.Next() {
		var i FinishesByYearRow
		if err := rows.Scan(&i.Year, &i.Finishes, &i.Books); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgress = `-- name: ListProgress :many
SELECT user_id, book_id, medium, file_id, locator, fraction, chapter, page, position_ms, client_id, updated_at FROM reading_progress WHERE user_id = $1 AND book_id = $2 ORDER BY medium
`

type ListProgressParams struct {
	UserID uuid.UUID
	BookID uuid.UUID
}

func (q *Queries) ListProgress(ctx context.Context, arg ListProgressParams) ([]ReadingProgress, error) {
	rows, err := q.db.Query(ctx, listProgress, arg.UserID, arg.BookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingProgress{}
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.UserID,
			&i.BookID,
			&i.Medium,
			&i.FileID,
			&i.Locator,
			&i.Fraction,
			&i.Chapter,
			&i.Page,
			&i.PositionMs,
			&i.ClientID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProgress = `-- name: LockProgress :one
SELECT user_id, book_id, medium, file_id, locator, fraction, chapter, page, position_ms, client_id, updated_at FROM reading_progress WHERE user_id = $1 AND book_id = $2 AND medium = $3 FOR UPDATE
`

type LockProgressParams struct {
	UserID uuid.UUID
	BookID uuid.UUID
	Medium string
}

func (q *Queries) LockProgress(ctx context.Context, arg LockProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, lockProgress, arg.UserID, arg.BookID, arg.Medium)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Medium,
		&i.FileID,
		&i.Locator,
		&i.Fraction,
		&i.Chapter,
		&i.Page,
		&i.PositionMs,
		&i.ClientID,
		&i.UpdatedAt,
	)
	return i, err
}

const putProgress = `-- name: PutProgress :one
INSERT INTO reading_progress (user_id, book_id, medium, file_id, locator, fraction, chapter, page, position_ms, client_id, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, clock_timestamp())
ON CONFLICT (user_id, book_id, medium) DO UPDATE
SET file_id = EXCLUDED.file_id, locator = EXCLUDED.locator, fraction = EXCLUDED.fraction,
    chapter = EXCLUDED.chapter, page = EXCLUDED.page, position_ms = EXCLUDED.position_ms,
    client_id = EXCLUDED.client_id, updated_at = clock_timestamp()
RETURNING user_id, book_id, medium, file_id, locator, fraction, chapter, page, position_ms, client_id, updated_at
`

type PutProgressParams struct {
	UserID     uuid.UUID
	BookID     uuid.UUID
	Medium     string
	FileID     *uuid.UUID
	Locator    string
	Fraction   float64
	Chapter    *string
	Page       *int32
	PositionMs *int64
	ClientID   string
}

func (q *Queries) PutProgress(ctx context.Context, arg PutProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, putProgress,
		arg.UserID,
		arg.BookID,
		arg.Medium,
		arg.FileID,
		arg.Locator,
		arg.Fraction,
		arg.Chapter,
		arg.Page,
		arg.PositionMs,
		arg.ClientID,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Medium,
		&i.FileID,
		&i.Locator,
		&i.Fraction,
		&i.Chapter,
		&i.Page,
		&i.PositionMs,
		&i.ClientID,
		&i.UpdatedAt,
	)
	return i, err
}

const readingHistory = `-- name: ReadingHistory :many
SELECT h.book_id, b.title, h.event, h.day
FROM (
    SELECT ub.book_id, 'started' AS event, ub.started_on AS day
    FROM user_books ub
    WHERE ub.user_id = $1 AND ub.started_on IS NOT NULL
  UNION ALL
    SELECT rf.book_id, 'finished', (rf.finished_at AT TIME ZONE $2::text)::date
    FROM reading_finishes rf
    WHERE rf.user_id = $1
) h
JOIN books b ON b.id = h.book_id
WHERE b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($1::uuid, $3::boolean))
ORDER BY h.day DESC, h.event DESC, b.title
LIMIT $4
`

type ReadingHistoryParams struct {
	UserID  uuid.UUID
	Tz      string
	SeesAll bool
	MaxRows int32
}

type ReadingHistoryRow struct {
	BookID uuid.UUID
	Title  string
	Event  string
	Day    *time.Time
}

// When a person began and finished books, the latest first.
func (q *Queries) ReadingHistory(ctx context.Context, arg ReadingHistoryParams) ([]ReadingHistoryRow, error) {
	rows, err := q.db.Query(ctx, readingHistory,
		arg.UserID,
		arg.Tz,
		arg.SeesAll,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingHistoryRow{}
	for rows.Next() {
		var i ReadingHistoryRow
		if err := rows.Scan(
			&i.BookID,
			&i.Title,
			&i.Event,
			&i.Day,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startSession = `-- name: StartSession :exec
INSERT INTO reading_sessions (user_id, book_id, medium, client_id, from_fraction, to_fraction)
VALUES ($1, $2, $3, $4, $5, $6)
`

type StartSessionParams struct {
	UserID       uuid.UUID
	BookID       uuid.UUID
	Medium       string
	ClientID     string
	FromFraction float64
	ToFraction   float64
}

func (q *Queries) StartSession(ctx context.Context, arg StartSessionParams) error {
	_, err := q.db.Exec(ctx, startSession,
		arg.UserID,
		arg.BookID,
		arg.Medium,
		arg.ClientID,
		arg.FromFraction,
		arg.ToFraction,
	)
	return err
}
