// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addFinish = `-- name: AddFinish :exec
INSERT INTO reading_finishes (user_id, book_id, medium) VALUES ($1, $2, $3)
`

type AddFinishParams struct {
	UserID uuid.UUID
	BookID uuid.UUID
	Medium string
}

func (q *Queries) AddFinish(ctx context.Context, arg AddFinishParams) error {
	_, err := q.db.Exec(ctx, addFinish, arg.UserID, arg.BookID, arg.Medium)
	return err
}

const countFinishes = `-- name: CountFinishes :one
SELECT count(*) FROM reading_finishes WHERE user_id = $1 AND book_id = $2
`

type CountFinishesParams struct {
	UserID uuid.UUID
	BookID uuid.UUID
}

func (q *Queries) CountFinishes(ctx context.Context, arg CountFinishesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFinishes, arg.UserID, arg.BookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const extendSession = `-- name: ExtendSession :execrows
UPDATE reading_sessions
SET ended_at = now(), to_fraction = $1
WHERE id = (
    SELECT s.id FROM reading_sessions s
    WHERE s.user_id = $2 AND s.book_id = $3 AND s.medium = $4
      AND s.client_id = $5 AND s.ended_at > now() - make_interval(secs => $6::double precision)
    ORDER BY s.ended_at DESC
    LIMIT 1
)
`

type ExtendSessionParams struct {
	Fraction   float64
	UserID     uuid.UUID
	BookID     uuid.UUID
	Medium     string
	ClientID   string
	GapSeconds float64
}

// The client's session goes on if it wrote recently.
func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendSession,
		arg.Fraction,
		arg.UserID,
		arg.BookID,
		arg.Medium,
		arg.ClientID,
		arg.GapSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fileOfBook = `-- name: FileOfBook :one
SELECT EXISTS (SELECT 1 FROM book_files WHERE id = $1 AND book_id = $2)
`

type FileOfBookParams struct {
	ID     uuid.UUID
	BookID uuid.UUID
}

func (q *Queries) FileOfBook(ctx context.Context, arg FileOfBookParams) (bool, error) {
	row := q.db.QueryRow(ctx, fileOfBook, arg.ID, arg.BookID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listProgress = `-- name: ListProgress :many
SELECT user_id, book_id, medium, file_id, locator, fraction, chapter, page, position_ms, client_id, updated_at FROM reading_progress WHERE user_id = $1 AND book_id = $2 ORDER BY medium
`

type ListProgressParams struct {
	UserID uuid.UUID
	BookID uuid.UUID
}

func (q *Queries) ListProgress(ctx context.Context, arg ListProgressParams) ([]ReadingProgress, error) {
	rows, err := q.db.Query(ctx, listProgress, arg.UserID, arg.BookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingProgress{}
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.UserID,
			&i.BookID,
			&i.Medium,
			&i.FileID,
			&i.Locator,
			&i.Fraction,
			&i.Chapter,
			&i.Page,
			&i.PositionMs,
			&i.ClientID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProgress = `-- name: LockProgress :one
SELECT user_id, book_id, medium, file_id, locator, fraction, chapter, page, position_ms, client_id, updated_at FROM reading_progress WHERE user_id = $1 AND book_id = $2 AND medium = $3 FOR UPDATE
`

type LockProgressParams struct {
	UserID uuid.UUID
	BookID uuid.UUID
	Medium string
}

func (q *Queries) LockProgress(ctx context.Context, arg LockProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, lockProgress, arg.UserID, arg.BookID, arg.Medium)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Medium,
		&i.FileID,
		&i.Locator,
		&i.Fraction,
		&i.Chapter,
		&i.Page,
		&i.PositionMs,
		&i.ClientID,
		&i.UpdatedAt,
	)
	return i, err
}

const putProgress = `-- name: PutProgress :one
INSERT INTO reading_progress (user_id, book_id, medium, file_id, locator, fraction, chapter, page, position_ms, client_id, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, clock_timestamp())
ON CONFLICT (user_id, book_id, medium) DO UPDATE
SET file_id = EXCLUDED.file_id, locator = EXCLUDED.locator, fraction = EXCLUDED.fraction,
    chapter = EXCLUDED.chapter, page = EXCLUDED.page, position_ms = EXCLUDED.position_ms,
    client_id = EXCLUDED.client_id, updated_at = clock_timestamp()
RETURNING user_id, book_id, medium, file_id, locator, fraction, chapter, page, position_ms, client_id, updated_at
`

type PutProgressParams struct {
	UserID     uuid.UUID
	BookID     uuid.UUID
	Medium     string
	FileID     *uuid.UUID
	Locator    string
	Fraction   float64
	Chapter    *string
	Page       *int32
	PositionMs *int64
	ClientID   string
}

func (q *Queries) PutProgress(ctx context.Context, arg PutProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, putProgress,
		arg.UserID,
		arg.BookID,
		arg.Medium,
		arg.FileID,
		arg.Locator,
		arg.Fraction,
		arg.Chapter,
		arg.Page,
		arg.PositionMs,
		arg.ClientID,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Medium,
		&i.FileID,
		&i.Locator,
		&i.Fraction,
		&i.Chapter,
		&i.Page,
		&i.PositionMs,
		&i.ClientID,
		&i.UpdatedAt,
	)
	return i, err
}

const startSession = `-- name: StartSession :exec
INSERT INTO reading_sessions (user_id, book_id, medium, client_id, from_fraction, to_fraction)
VALUES ($1, $2, $3, $4, $5, $6)
`

type StartSessionParams struct {
	UserID       uuid.UUID
	BookID       uuid.UUID
	Medium       string
	ClientID     string
	FromFraction float64
	ToFraction   float64
}

func (q *Queries) StartSession(ctx context.Context, arg StartSessionParams) error {
	_, err := q.db.Exec(ctx, startSession,
		arg.UserID,
		arg.BookID,
		arg.Medium,
		arg.ClientID,
		arg.FromFraction,
		arg.ToFraction,
	)
	return err
}
