// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserBook = `-- name: GetUserBook :one
SELECT user_id, book_id, status, rating, started_on, finished_on, updated_at FROM user_books WHERE user_id = $1 AND book_id = $2
`

type GetUserBookParams struct {
	UserID uuid.UUID
	BookID uuid.UUID
}

func (q *Queries) GetUserBook(ctx context.Context, arg GetUserBookParams) (UserBook, error) {
	row := q.db.QueryRow(ctx, getUserBook, arg.UserID, arg.BookID)
	var i UserBook
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Status,
		&i.Rating,
		&i.StartedOn,
		&i.FinishedOn,
		&i.UpdatedAt,
	)
	return i, err
}

const lockVisibleBookIDs = `-- name: LockVisibleBookIDs :many
SELECT b.id
FROM books b
WHERE b.id = ANY($1::uuid[])
  AND b.deleted_at IS NULL
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($2::uuid, $3::boolean))
ORDER BY b.id
FOR SHARE
`

type LockVisibleBookIDsParams struct {
	Ids     []uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

// The books among these the viewer may see, locked against a change of
// their state in parallel.
func (q *Queries) LockVisibleBookIDs(ctx context.Context, arg LockVisibleBookIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockVisibleBookIDs, arg.Ids, arg.Viewer, arg.SeesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putUserBook = `-- name: PutUserBook :exec
INSERT INTO user_books (user_id, book_id, status, rating, started_on, finished_on)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, book_id) DO UPDATE
SET status = EXCLUDED.status, rating = EXCLUDED.rating, started_on = EXCLUDED.started_on,
    finished_on = EXCLUDED.finished_on, updated_at = now()
`

type PutUserBookParams struct {
	UserID     uuid.UUID
	BookID     uuid.UUID
	Status     string
	Rating     *int16
	StartedOn  *time.Time
	FinishedOn *time.Time
}

func (q *Queries) PutUserBook(ctx context.Context, arg PutUserBookParams) error {
	_, err := q.db.Exec(ctx, putUserBook,
		arg.UserID,
		arg.BookID,
		arg.Status,
		arg.Rating,
		arg.StartedOn,
		arg.FinishedOn,
	)
	return err
}
