// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTracker = `-- name: DeleteTracker :one
WITH gone AS (
    DELETE FROM trackers WHERE id = $1::uuid AND user_id = $2::uuid
    RETURNING subject_id
), orphan AS (
    DELETE FROM release_subjects s
    USING gone g
    WHERE s.id = g.subject_id
      AND NOT EXISTS (SELECT 1 FROM trackers t WHERE t.subject_id = s.id AND t.id <> $1::uuid)
)
SELECT count(*)::int AS deleted FROM gone
`

type DeleteTrackerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// The caller's tracker gone, and its subject with what was found for it
// once nobody follows that any more.
func (q *Queries) DeleteTracker(ctx context.Context, arg DeleteTrackerParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteTracker, arg.ID, arg.UserID)
	var deleted int32
	err := row.Scan(&deleted)
	return deleted, err
}

const listDueReleases = `-- name: ListDueReleases :many
SELECT r.id, r.release_date, r.title, r.authors, s.name AS subject
FROM releases r
JOIN release_subjects s ON s.id = r.subject_id
WHERE r.precision = 'day'
  AND r.release_date <= current_date
  AND r.release_date > current_date - 7
`

type ListDueReleasesRow struct {
	ID          uuid.UUID
	ReleaseDate *time.Time
	Title       string
	Authors     []string
	Subject     string
}

// Releases whose day came within the last week, for telling that they
// are out; those told already are skipped by QueueReleaseNotices.
func (q *Queries) ListDueReleases(ctx context.Context) ([]ListDueReleasesRow, error) {
	rows, err := q.db.Query(ctx, listDueReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueReleasesRow{}
	for rows.Next() {
		var i ListDueReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseDate,
			&i.Title,
			&i.Authors,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
WITH mine AS (
    SELECT DISTINCT ON (r.dedupe_key) r.id, r.subject_id, r.dedupe_key, r.title, r.authors, r.author_keys, r.series, r.series_index, r.release_date, r.precision, r.isbns, r.provider, r.provider_id, r.cover_url, r.backlog, r.first_seen_at, s.kind AS subject_kind, s.name AS subject_name
    FROM releases r
    JOIN trackers t ON t.subject_id = r.subject_id AND t.user_id = $1::uuid
    JOIN release_subjects s ON s.id = r.subject_id
    WHERE CASE WHEN $3::boolean
               THEN r.release_date > current_date OR (r.release_date IS NULL AND NOT r.backlog)
               ELSE r.release_date <= current_date AND r.release_date > current_date - 365 END
    ORDER BY r.dedupe_key, s.kind, r.id
)
SELECT m.id, m.title, m.authors, m.series, m.series_index, m.release_date, m.precision,
       m.provider, m.cover_url, m.subject_kind, m.subject_name,
       (EXISTS (
            SELECT 1 FROM books b
            WHERE b.title_key = m.dedupe_key AND b.deleted_at IS NULL AND NOT b.placeholder
              AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($1::uuid, $2::boolean))
              AND (cardinality(m.author_keys) = 0 OR EXISTS (
                  SELECT 1 FROM book_contributors c JOIN authors a ON a.id = c.author_id
                  WHERE c.book_id = b.id AND a.name_key = ANY(m.author_keys))))
        OR EXISTS (
            SELECT 1 FROM book_identifiers i
            JOIN books b ON b.id = i.book_id
            WHERE i.type = 'isbn' AND i.value = ANY(m.isbns) AND b.deleted_at IS NULL AND NOT b.placeholder
              AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($1::uuid, $2::boolean)))
       )::boolean AS in_library
FROM mine m
ORDER BY CASE WHEN $3::boolean THEN m.release_date END ASC NULLS LAST,
         CASE WHEN NOT $3::boolean THEN m.release_date END DESC,
         lower(m.title)
LIMIT 200
`

type ListReleasesParams struct {
	Viewer   uuid.UUID
	SeesAll  bool
	Upcoming bool
}

type ListReleasesRow struct {
	ID          uuid.UUID
	Title       string
	Authors     []string
	Series      *string
	SeriesIndex *float64
	ReleaseDate *time.Time
	Precision   *string
	Provider    string
	CoverUrl    *string
	SubjectKind string
	SubjectName string
	InLibrary   bool
}

// The books of the subjects the viewer follows, upcoming (later than
// today, or with no date and not of the subject's past) or out within the
// last year, each book once; in_library says whether a library they see
// has it.
func (q *Queries) ListReleases(ctx context.Context, arg ListReleasesParams) ([]ListReleasesRow, error) {
	rows, err := q.db.Query(ctx, listReleases, arg.Viewer, arg.SeesAll, arg.Upcoming)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleasesRow{}
	for rows.Next() {
		var i ListReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Authors,
			&i.Series,
			&i.SeriesIndex,
			&i.ReleaseDate,
			&i.Precision,
			&i.Provider,
			&i.CoverUrl,
			&i.SubjectKind,
			&i.SubjectName,
			&i.InLibrary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackers = `-- name: ListTrackers :many
SELECT t.id, s.kind, s.name, t.created_at, s.polled_at
FROM trackers t
JOIN release_subjects s ON s.id = t.subject_id
WHERE t.user_id = $1::uuid
ORDER BY s.kind, lower(s.name)
`

type ListTrackersRow struct {
	ID        uuid.UUID
	Kind      string
	Name      string
	CreatedAt time.Time
	PolledAt  *time.Time
}

func (q *Queries) ListTrackers(ctx context.Context, userID uuid.UUID) ([]ListTrackersRow, error) {
	rows, err := q.db.Query(ctx, listTrackers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackersRow{}
	for rows.Next() {
		var i ListTrackersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.CreatedAt,
			&i.PolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReleaseSubjectPolled = `-- name: MarkReleaseSubjectPolled :exec
UPDATE release_subjects SET polled_at = now() WHERE id = $1
`

func (q *Queries) MarkReleaseSubjectPolled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markReleaseSubjectPolled, id)
	return err
}

const nextReleaseSubject = `-- name: NextReleaseSubject :one
SELECT s.id, s.kind, s.name
FROM release_subjects s
WHERE (s.polled_at IS NULL OR s.polled_at < $1::timestamptz)
  AND EXISTS (SELECT 1 FROM trackers t WHERE t.subject_id = s.id)
ORDER BY s.polled_at NULLS FIRST, s.id
LIMIT 1
`

type NextReleaseSubjectRow struct {
	ID   uuid.UUID
	Kind string
	Name string
}

// The followed subject asked about longest ago, if that is before the
// given time.
func (q *Queries) NextReleaseSubject(ctx context.Context, before time.Time) (NextReleaseSubjectRow, error) {
	row := q.db.QueryRow(ctx, nextReleaseSubject, before)
	var i NextReleaseSubjectRow
	err := row.Scan(&i.ID, &i.Kind, &i.Name)
	return i, err
}

const putRelease = `-- name: PutRelease :one
INSERT INTO releases (subject_id, dedupe_key, title, authors, author_keys, series, series_index,
                      release_date, precision, isbns, provider, provider_id, cover_url, backlog)
VALUES ($1::uuid, $2::text, $3::text,
        $4::text[], $5::text[],
        $6::text, $7::float8,
        $8::date, $9::text, $10::text[],
        $11::text, $12::text, $13::text,
        $14::boolean)
ON CONFLICT (subject_id, dedupe_key) DO UPDATE SET
    release_date = CASE WHEN precision_rank(EXCLUDED.precision) > precision_rank(releases.precision)
                          OR (EXCLUDED.provider = releases.provider AND EXCLUDED.precision = releases.precision)
                        THEN EXCLUDED.release_date ELSE releases.release_date END,
    precision    = CASE WHEN precision_rank(EXCLUDED.precision) > precision_rank(releases.precision)
                        THEN EXCLUDED.precision ELSE releases.precision END,
    series       = coalesce(releases.series, EXCLUDED.series),
    series_index = coalesce(releases.series_index, EXCLUDED.series_index),
    cover_url    = coalesce(releases.cover_url, EXCLUDED.cover_url),
    isbns        = ARRAY(SELECT DISTINCT unnest(releases.isbns || EXCLUDED.isbns)),
    author_keys  = ARRAY(SELECT DISTINCT unnest(releases.author_keys || EXCLUDED.author_keys))
RETURNING id, (xmax = 0)::boolean AS inserted, backlog, release_date, precision, first_seen_at
`

type PutReleaseParams struct {
	SubjectID   uuid.UUID
	DedupeKey   string
	Title       string
	Authors     []string
	AuthorKeys  []string
	Series      *string
	SeriesIndex *float64
	ReleaseDate *time.Time
	Precision   *string
	Isbns       []string
	Provider    string
	ProviderID  string
	CoverUrl    *string
	Backlog     bool
}

type PutReleaseRow struct {
	ID          uuid.UUID
	Inserted    bool
	Backlog     bool
	ReleaseDate *time.Time
	Precision   *string
	FirstSeenAt time.Time
}

// A book a provider listed for the subject. One listed already, by this
// provider or another, is the same release, which takes a more exact date,
// or a moved one from the provider that first listed it, and what it
// lacked. Says whether it is new.
func (q *Queries) PutRelease(ctx context.Context, arg PutReleaseParams) (PutReleaseRow, error) {
	row := q.db.QueryRow(ctx, putRelease,
		arg.SubjectID,
		arg.DedupeKey,
		arg.Title,
		arg.Authors,
		arg.AuthorKeys,
		arg.Series,
		arg.SeriesIndex,
		arg.ReleaseDate,
		arg.Precision,
		arg.Isbns,
		arg.Provider,
		arg.ProviderID,
		arg.CoverUrl,
		arg.Backlog,
	)
	var i PutReleaseRow
	err := row.Scan(
		&i.ID,
		&i.Inserted,
		&i.Backlog,
		&i.ReleaseDate,
		&i.Precision,
		&i.FirstSeenAt,
	)
	return i, err
}

const putReleasePoll = `-- name: PutReleasePoll :one
INSERT INTO release_polls (subject_id, provider)
VALUES ($1::uuid, $2::text)
ON CONFLICT (subject_id, provider) DO UPDATE SET last_at = now()
RETURNING (xmax = 0)::boolean AS first
`

type PutReleasePollParams struct {
	SubjectID uuid.UUID
	Provider  string
}

// Records that the provider answered about the subject, and says whether
// it was its first answer.
func (q *Queries) PutReleasePoll(ctx context.Context, arg PutReleasePollParams) (bool, error) {
	row := q.db.QueryRow(ctx, putReleasePoll, arg.SubjectID, arg.Provider)
	var first bool
	err := row.Scan(&first)
	return first, err
}

const putReleaseSubject = `-- name: PutReleaseSubject :one
INSERT INTO release_subjects (kind, name, name_key)
VALUES ($1::text, $2::text, $3::text)
ON CONFLICT (kind, name_key) DO UPDATE SET kind = EXCLUDED.kind
RETURNING id, kind, name, polled_at
`

type PutReleaseSubjectParams struct {
	Kind    string
	Name    string
	NameKey string
}

type PutReleaseSubjectRow struct {
	ID       uuid.UUID
	Kind     string
	Name     string
	PolledAt *time.Time
}

// The subject of that kind and key, made if nobody followed it before; it
// keeps the spelling it was first followed by.
func (q *Queries) PutReleaseSubject(ctx context.Context, arg PutReleaseSubjectParams) (PutReleaseSubjectRow, error) {
	row := q.db.QueryRow(ctx, putReleaseSubject, arg.Kind, arg.Name, arg.NameKey)
	var i PutReleaseSubjectRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.PolledAt,
	)
	return i, err
}

const putTracker = `-- name: PutTracker :one
INSERT INTO trackers (user_id, subject_id)
VALUES ($1::uuid, $2::uuid)
ON CONFLICT (user_id, subject_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, created_at
`

type PutTrackerParams struct {
	UserID    uuid.UUID
	SubjectID uuid.UUID
}

type PutTrackerRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) PutTracker(ctx context.Context, arg PutTrackerParams) (PutTrackerRow, error) {
	row := q.db.QueryRow(ctx, putTracker, arg.UserID, arg.SubjectID)
	var i PutTrackerRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const queueReleaseNotices = `-- name: QueueReleaseNotices :many
INSERT INTO release_notices (user_id, release_id, stage)
SELECT t.user_id, r.id, $1::text
FROM releases r
JOIN trackers t ON t.subject_id = r.subject_id
JOIN users u ON u.id = t.user_id
WHERE r.id = $2::uuid
  AND u.disabled_at IS NULL
  AND t.created_at < $3::timestamptz
  AND NOT EXISTS (
      SELECT 1 FROM release_notices n
      JOIN releases o ON o.id = n.release_id
      WHERE n.user_id = t.user_id AND n.stage = $1::text AND o.dedupe_key = r.dedupe_key)
  -- Two tests rather than one with OR, so that each finds its books by
  -- an index instead of reading them all.
  AND NOT EXISTS (
      SELECT 1 FROM books b
      WHERE b.title_key = r.dedupe_key AND b.deleted_at IS NULL AND NOT b.placeholder
        AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids(u.id, u.role = ANY($4::text[])))
        AND (cardinality(r.author_keys) = 0 OR EXISTS (
            SELECT 1 FROM book_contributors c JOIN authors a ON a.id = c.author_id
            WHERE c.book_id = b.id AND a.name_key = ANY(r.author_keys))))
  AND NOT EXISTS (
      SELECT 1 FROM book_identifiers i
      JOIN books b ON b.id = i.book_id
      WHERE i.type = 'isbn' AND i.value = ANY(r.isbns) AND b.deleted_at IS NULL AND NOT b.placeholder
        AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids(u.id, u.role = ANY($4::text[]))))
ON CONFLICT DO NOTHING
RETURNING user_id
`

type QueueReleaseNoticesParams struct {
	Stage          string
	ReleaseID      uuid.UUID
	FollowedBefore time.Time
	SeesAllRoles   []string
}

// Who is to be told that the release reached the stage, each once, and
// remembers it: an active person following its subject since before the
// given time, not told of the same book through another subject they
// follow, and without a book in a library they see that is the release:
// the same title and an author, or an ISBN.
func (q *Queries) QueueReleaseNotices(ctx context.Context, arg QueueReleaseNoticesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, queueReleaseNotices,
		arg.Stage,
		arg.ReleaseID,
		arg.FollowedBefore,
		arg.SeesAllRoles,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
