// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const finishScan = `-- name: FinishScan :exec
UPDATE library_scans
SET state = $2, error = $3, finished_at = now()
WHERE id = $1
`

type FinishScanParams struct {
	ID    uuid.UUID
	State string
	Error *string
}

func (q *Queries) FinishScan(ctx context.Context, arg FinishScanParams) error {
	_, err := q.db.Exec(ctx, finishScan, arg.ID, arg.State, arg.Error)
	return err
}

const latestVisibleScans = `-- name: LatestVisibleScans :many
SELECT DISTINCT ON (s.library_id) s.id, s.library_id, s.state, s.requested_by, s.requested_at, s.job_id, s.started_at, s.finished_at, s.files_seen, s.files_added, s.files_changed, s.files_moved, s.files_restored, s.files_missing, s.files_skipped, s.books_added, s.error
FROM library_scans s
WHERE s.library_id IN (SELECT visible_library_ids($1::uuid, $2::boolean))
ORDER BY s.library_id, s.requested_at DESC, s.id DESC
`

type LatestVisibleScansParams struct {
	Viewer  uuid.UUID
	SeesAll bool
}

// The newest scan of each library the viewer may see.
func (q *Queries) LatestVisibleScans(ctx context.Context, arg LatestVisibleScansParams) ([]LibraryScan, error) {
	rows, err := q.db.Query(ctx, latestVisibleScans, arg.Viewer, arg.SeesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryScan{}
	for rows.Next() {
		var i LibraryScan
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.State,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.JobID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.FilesSeen,
			&i.FilesAdded,
			&i.FilesChanged,
			&i.FilesMoved,
			&i.FilesRestored,
			&i.FilesMissing,
			&i.FilesSkipped,
			&i.BooksAdded,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesForScan = `-- name: ListFilesForScan :many
SELECT id, book_id, kind, format, rel_path, size_bytes, modified_at, sha256,
       part_index, missing_at, trashed_at
FROM book_files
WHERE library_id = $1
`

type ListFilesForScanRow struct {
	ID         uuid.UUID
	BookID     uuid.UUID
	Kind       string
	Format     string
	RelPath    string
	SizeBytes  int64
	ModifiedAt time.Time
	Sha256     []byte
	PartIndex  *int32
	MissingAt  *time.Time
	TrashedAt  *time.Time
}

// Every file the library knows, trashed ones included: their paths are taken.
func (q *Queries) ListFilesForScan(ctx context.Context, libraryID uuid.UUID) ([]ListFilesForScanRow, error) {
	rows, err := q.db.Query(ctx, listFilesForScan, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilesForScanRow{}
	for rows.Next() {
		var i ListFilesForScanRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Kind,
			&i.Format,
			&i.RelPath,
			&i.SizeBytes,
			&i.ModifiedAt,
			&i.Sha256,
			&i.PartIndex,
			&i.MissingAt,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryIDs = `-- name: ListLibraryIDs :many
SELECT id FROM libraries ORDER BY id
`

func (q *Queries) ListLibraryIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLibraryIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveScan = `-- name: LockActiveScan :one
SELECT id, library_id, state, requested_by, requested_at, job_id, started_at, finished_at, files_seen, files_added, files_changed, files_moved, files_restored, files_missing, files_skipped, books_added, error FROM library_scans
WHERE library_id = $1 AND state IN ('queued', 'running')
FOR UPDATE
`

// Locked, so that two people asking at once do not both decide that the scan
// needs a job.
func (q *Queries) LockActiveScan(ctx context.Context, libraryID uuid.UUID) (LibraryScan, error) {
	row := q.db.QueryRow(ctx, lockActiveScan, libraryID)
	var i LibraryScan
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.State,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.JobID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FilesSeen,
		&i.FilesAdded,
		&i.FilesChanged,
		&i.FilesMoved,
		&i.FilesRestored,
		&i.FilesMissing,
		&i.FilesSkipped,
		&i.BooksAdded,
		&i.Error,
	)
	return i, err
}

const markFilesMissing = `-- name: MarkFilesMissing :execrows
UPDATE book_files
SET missing_at = now(), updated_at = now()
WHERE id = ANY($1::uuid[]) AND missing_at IS NULL
`

func (q *Queries) MarkFilesMissing(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markFilesMissing, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveFile = `-- name: MoveFile :exec
UPDATE book_files
SET rel_path = $2, size_bytes = $3, modified_at = $4, missing_at = NULL, updated_at = now()
WHERE id = $1
`

type MoveFileParams struct {
	ID         uuid.UUID
	RelPath    string
	SizeBytes  int64
	ModifiedAt time.Time
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) error {
	_, err := q.db.Exec(ctx, moveFile,
		arg.ID,
		arg.RelPath,
		arg.SizeBytes,
		arg.ModifiedAt,
	)
	return err
}

const pruneScans = `-- name: PruneScans :exec
DELETE FROM library_scans s
WHERE s.library_id = $1
  AND s.id NOT IN (
      SELECT k.id FROM library_scans k
      WHERE k.library_id = $1
      ORDER BY k.requested_at DESC, k.id DESC
      LIMIT $2::int
  )
`

type PruneScansParams struct {
	LibraryID uuid.UUID
	Keep      int32
}

// A library scanned four times a day would otherwise grow a row each time.
func (q *Queries) PruneScans(ctx context.Context, arg PruneScansParams) error {
	_, err := q.db.Exec(ctx, pruneScans, arg.LibraryID, arg.Keep)
	return err
}

const queueScan = `-- name: QueueScan :one
INSERT INTO library_scans (library_id, requested_by)
VALUES ($1, $2)
ON CONFLICT (library_id) WHERE state IN ('queued', 'running') DO NOTHING
RETURNING id, library_id, state, requested_by, requested_at, job_id, started_at, finished_at, files_seen, files_added, files_changed, files_moved, files_restored, files_missing, files_skipped, books_added, error
`

type QueueScanParams struct {
	LibraryID   uuid.UUID
	RequestedBy *uuid.UUID
}

// Returns no row when the library already has a scan waiting or running.
func (q *Queries) QueueScan(ctx context.Context, arg QueueScanParams) (LibraryScan, error) {
	row := q.db.QueryRow(ctx, queueScan, arg.LibraryID, arg.RequestedBy)
	var i LibraryScan
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.State,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.JobID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FilesSeen,
		&i.FilesAdded,
		&i.FilesChanged,
		&i.FilesMoved,
		&i.FilesRestored,
		&i.FilesMissing,
		&i.FilesSkipped,
		&i.BooksAdded,
		&i.Error,
	)
	return i, err
}

const recordScanProgress = `-- name: RecordScanProgress :exec
UPDATE library_scans
SET files_seen     = $2,
    files_added    = files_added + $3,
    files_changed  = files_changed + $4,
    files_moved    = files_moved + $5,
    files_restored = files_restored + $6,
    files_missing  = files_missing + $7,
    files_skipped  = $8,
    books_added    = books_added + $9
WHERE id = $1
`

type RecordScanProgressParams struct {
	ID            uuid.UUID
	FilesSeen     int32
	FilesAdded    int32
	FilesChanged  int32
	FilesMoved    int32
	FilesRestored int32
	FilesMissing  int32
	FilesSkipped  int32
	BooksAdded    int32
}

// What one run found is added to what earlier runs of the same scan found;
// only the walk's count is of the whole library each time.
func (q *Queries) RecordScanProgress(ctx context.Context, arg RecordScanProgressParams) error {
	_, err := q.db.Exec(ctx, recordScanProgress,
		arg.ID,
		arg.FilesSeen,
		arg.FilesAdded,
		arg.FilesChanged,
		arg.FilesMoved,
		arg.FilesRestored,
		arg.FilesMissing,
		arg.FilesSkipped,
		arg.BooksAdded,
	)
	return err
}

const restoreFile = `-- name: RestoreFile :exec
UPDATE book_files
SET missing_at = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreFile, id)
	return err
}

const setFilePartIndex = `-- name: SetFilePartIndex :exec
UPDATE book_files
SET part_index = $2, updated_at = now()
WHERE id = $1
`

type SetFilePartIndexParams struct {
	ID        uuid.UUID
	PartIndex *int32
}

func (q *Queries) SetFilePartIndex(ctx context.Context, arg SetFilePartIndexParams) error {
	_, err := q.db.Exec(ctx, setFilePartIndex, arg.ID, arg.PartIndex)
	return err
}

const setScanJob = `-- name: SetScanJob :exec
UPDATE library_scans SET job_id = $2 WHERE id = $1
`

type SetScanJobParams struct {
	ID    uuid.UUID
	JobID *int64
}

func (q *Queries) SetScanJob(ctx context.Context, arg SetScanJobParams) error {
	_, err := q.db.Exec(ctx, setScanJob, arg.ID, arg.JobID)
	return err
}

const startScan = `-- name: StartScan :one
INSERT INTO library_scans (library_id, state, started_at, job_id)
VALUES ($1, 'running', now(), $2)
ON CONFLICT (library_id) WHERE state IN ('queued', 'running')
DO UPDATE SET state = 'running', started_at = COALESCE(library_scans.started_at, now())
RETURNING id, library_id, state, requested_by, requested_at, job_id, started_at, finished_at, files_seen, files_added, files_changed, files_moved, files_restored, files_missing, files_skipped, books_added, error
`

type StartScanParams struct {
	LibraryID uuid.UUID
	JobID     *int64
}

// The worker takes the library's waiting scan, or the one an earlier run left
// unfinished. A job without either still has a scan to show for its work.
func (q *Queries) StartScan(ctx context.Context, arg StartScanParams) (LibraryScan, error) {
	row := q.db.QueryRow(ctx, startScan, arg.LibraryID, arg.JobID)
	var i LibraryScan
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.State,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.JobID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FilesSeen,
		&i.FilesAdded,
		&i.FilesChanged,
		&i.FilesMoved,
		&i.FilesRestored,
		&i.FilesMissing,
		&i.FilesSkipped,
		&i.BooksAdded,
		&i.Error,
	)
	return i, err
}

const updateFileContent = `-- name: UpdateFileContent :exec
UPDATE book_files
SET size_bytes      = $2,
    modified_at     = $3,
    original_sha256 = CASE WHEN sha256 IS DISTINCT FROM $4::bytea THEN $4::bytea ELSE original_sha256 END,
    content_sha256  = CASE WHEN sha256 IS DISTINCT FROM $4::bytea THEN NULL ELSE content_sha256 END,
    extract_state   = CASE WHEN sha256 IS DISTINCT FROM $4::bytea THEN 'pending' ELSE extract_state END,
    extract_error   = CASE WHEN sha256 IS DISTINCT FROM $4::bytea THEN NULL ELSE extract_error END,
    sha256          = $4::bytea,
    missing_at      = NULL,
    updated_at      = now()
WHERE id = $1
`

type UpdateFileContentParams struct {
	ID         uuid.UUID
	SizeBytes  int64
	ModifiedAt time.Time
	Sha256     []byte
}

// A file whose bytes changed is a file nothing has been extracted from yet.
func (q *Queries) UpdateFileContent(ctx context.Context, arg UpdateFileContentParams) error {
	_, err := q.db.Exec(ctx, updateFileContent,
		arg.ID,
		arg.SizeBytes,
		arg.ModifiedAt,
		arg.Sha256,
	)
	return err
}
