// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFileChapter = `-- name: AddFileChapter :exec
INSERT INTO audio_chapters (file_id, position, title, start_ms, end_ms)
VALUES ($1, $2, $3, $4, $5)
`

type AddFileChapterParams struct {
	FileID   uuid.UUID
	Position int32
	Title    string
	StartMs  int64
	EndMs    int64
}

func (q *Queries) AddFileChapter(ctx context.Context, arg AddFileChapterParams) error {
	_, err := q.db.Exec(ctx, addFileChapter,
		arg.FileID,
		arg.Position,
		arg.Title,
		arg.StartMs,
		arg.EndMs,
	)
	return err
}

const countPendingFiles = `-- name: CountPendingFiles :many
SELECT library_id, count(*)::int AS pending
FROM book_files
WHERE extract_state = 'pending'
  AND missing_at IS NULL AND trashed_at IS NULL
  AND library_id IN (SELECT visible_library_ids($1::uuid, $2::boolean))
GROUP BY library_id
`

type CountPendingFilesParams struct {
	Viewer  uuid.UUID
	SeesAll bool
}

type CountPendingFilesRow struct {
	LibraryID uuid.UUID
	Pending   int32
}

// Per library the viewer may see, how many files found are still to be read.
func (q *Queries) CountPendingFiles(ctx context.Context, arg CountPendingFilesParams) ([]CountPendingFilesRow, error) {
	rows, err := q.db.Query(ctx, countPendingFiles, arg.Viewer, arg.SeesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPendingFilesRow{}
	for rows.Next() {
		var i CountPendingFilesRow
		if err := rows.Scan(&i.LibraryID, &i.Pending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFileChapters = `-- name: DeleteFileChapters :exec
DELETE FROM audio_chapters WHERE file_id = $1
`

func (q *Queries) DeleteFileChapters(ctx context.Context, fileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileChapters, fileID)
	return err
}

const finishScan = `-- name: FinishScan :exec
UPDATE library_scans
SET state = $2, error = $3, finished_at = now()
WHERE id = $1
`

type FinishScanParams struct {
	ID    uuid.UUID
	State string
	Error *string
}

func (q *Queries) FinishScan(ctx context.Context, arg FinishScanParams) error {
	_, err := q.db.Exec(ctx, finishScan, arg.ID, arg.State, arg.Error)
	return err
}

const getFileForExtraction = `-- name: GetFileForExtraction :one
SELECT f.id, f.book_id, f.format, f.rel_path, f.sha256, f.missing_at, f.trashed_at, l.root_path
FROM book_files f
JOIN libraries l ON l.id = f.library_id
WHERE f.id = $1
`

type GetFileForExtractionRow struct {
	ID        uuid.UUID
	BookID    uuid.UUID
	Format    string
	RelPath   string
	Sha256    []byte
	MissingAt *time.Time
	TrashedAt *time.Time
	RootPath  string
}

func (q *Queries) GetFileForExtraction(ctx context.Context, id uuid.UUID) (GetFileForExtractionRow, error) {
	row := q.db.QueryRow(ctx, getFileForExtraction, id)
	var i GetFileForExtractionRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Format,
		&i.RelPath,
		&i.Sha256,
		&i.MissingAt,
		&i.TrashedAt,
		&i.RootPath,
	)
	return i, err
}

const latestVisibleScans = `-- name: LatestVisibleScans :many
SELECT DISTINCT ON (s.library_id) s.id, s.library_id, s.state, s.requested_by, s.requested_at, s.job_id, s.started_at, s.finished_at, s.files_seen, s.files_added, s.files_changed, s.files_moved, s.files_restored, s.files_missing, s.files_skipped, s.books_added, s.error
FROM library_scans s
WHERE s.library_id IN (SELECT visible_library_ids($1::uuid, $2::boolean))
ORDER BY s.library_id, s.requested_at DESC, s.id DESC
`

type LatestVisibleScansParams struct {
	Viewer  uuid.UUID
	SeesAll bool
}

// The newest scan of each library the viewer may see.
func (q *Queries) LatestVisibleScans(ctx context.Context, arg LatestVisibleScansParams) ([]LibraryScan, error) {
	rows, err := q.db.Query(ctx, latestVisibleScans, arg.Viewer, arg.SeesAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryScan{}
	for rows.Next() {
		var i LibraryScan
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.State,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.JobID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.FilesSeen,
			&i.FilesAdded,
			&i.FilesChanged,
			&i.FilesMoved,
			&i.FilesRestored,
			&i.FilesMissing,
			&i.FilesSkipped,
			&i.BooksAdded,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookParts = `-- name: ListBookParts :many
SELECT id, rel_path, part_index, track_number, disc_number
FROM book_files
WHERE book_id = $1 AND kind = 'audio' AND part_index IS NOT NULL AND trashed_at IS NULL
`

type ListBookPartsRow struct {
	ID          uuid.UUID
	RelPath     string
	PartIndex   *int32
	TrackNumber *int32
	DiscNumber  *int32
}

// The parts of a book's audiobook, which are its audio files with a place.
func (q *Queries) ListBookParts(ctx context.Context, bookID uuid.UUID) ([]ListBookPartsRow, error) {
	rows, err := q.db.Query(ctx, listBookParts, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookPartsRow{}
	for rows.Next() {
		var i ListBookPartsRow
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.PartIndex,
			&i.TrackNumber,
			&i.DiscNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesForScan = `-- name: ListFilesForScan :many
SELECT id, book_id, kind, format, rel_path, size_bytes, modified_at, sha256,
       part_index, missing_at, trashed_at
FROM book_files
WHERE library_id = $1
`

type ListFilesForScanRow struct {
	ID         uuid.UUID
	BookID     uuid.UUID
	Kind       string
	Format     string
	RelPath    string
	SizeBytes  int64
	ModifiedAt time.Time
	Sha256     []byte
	PartIndex  *int32
	MissingAt  *time.Time
	TrashedAt  *time.Time
}

// Every file the library knows, trashed ones included: their paths are taken.
func (q *Queries) ListFilesForScan(ctx context.Context, libraryID uuid.UUID) ([]ListFilesForScanRow, error) {
	rows, err := q.db.Query(ctx, listFilesForScan, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilesForScanRow{}
	for rows.Next() {
		var i ListFilesForScanRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Kind,
			&i.Format,
			&i.RelPath,
			&i.SizeBytes,
			&i.ModifiedAt,
			&i.Sha256,
			&i.PartIndex,
			&i.MissingAt,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryIDs = `-- name: ListLibraryIDs :many
SELECT id FROM libraries ORDER BY id
`

func (q *Queries) ListLibraryIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLibraryIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingExtractions = `-- name: ListPendingExtractions :many
SELECT id FROM book_files
WHERE library_id = $1
  AND extract_state = 'pending'
  AND missing_at IS NULL AND trashed_at IS NULL
  AND sha256 IS NOT NULL
  AND format = ANY($2::text[])
ORDER BY id
`

type ListPendingExtractionsParams struct {
	LibraryID uuid.UUID
	Formats   []string
}

// Files of the library that are there, have been hashed, and that nothing
// has been read out of yet, of the formats there is a reader for.
func (q *Queries) ListPendingExtractions(ctx context.Context, arg ListPendingExtractionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPendingExtractions, arg.LibraryID, arg.Formats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveScan = `-- name: LockActiveScan :one
SELECT id, library_id, state, requested_by, requested_at, job_id, started_at, finished_at, files_seen, files_added, files_changed, files_moved, files_restored, files_missing, files_skipped, books_added, error FROM library_scans
WHERE library_id = $1 AND state IN ('queued', 'running')
FOR UPDATE
`

// Locked, so that two people asking at once do not both decide that the scan
// needs a job.
func (q *Queries) LockActiveScan(ctx context.Context, libraryID uuid.UUID) (LibraryScan, error) {
	row := q.db.QueryRow(ctx, lockActiveScan, libraryID)
	var i LibraryScan
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.State,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.JobID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FilesSeen,
		&i.FilesAdded,
		&i.FilesChanged,
		&i.FilesMoved,
		&i.FilesRestored,
		&i.FilesMissing,
		&i.FilesSkipped,
		&i.BooksAdded,
		&i.Error,
	)
	return i, err
}

const markFilesMissing = `-- name: MarkFilesMissing :execrows
UPDATE book_files
SET missing_at = now(), updated_at = now()
WHERE id = ANY($1::uuid[]) AND missing_at IS NULL
`

func (q *Queries) MarkFilesMissing(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markFilesMissing, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveFile = `-- name: MoveFile :exec
UPDATE book_files
SET rel_path = $2, size_bytes = $3, modified_at = $4, missing_at = NULL, updated_at = now()
WHERE id = $1
`

type MoveFileParams struct {
	ID         uuid.UUID
	RelPath    string
	SizeBytes  int64
	ModifiedAt time.Time
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) error {
	_, err := q.db.Exec(ctx, moveFile,
		arg.ID,
		arg.RelPath,
		arg.SizeBytes,
		arg.ModifiedAt,
	)
	return err
}

const pruneScans = `-- name: PruneScans :exec
DELETE FROM library_scans s
WHERE s.library_id = $1
  AND s.id NOT IN (
      SELECT k.id FROM library_scans k
      WHERE k.library_id = $1
      ORDER BY k.requested_at DESC, k.id DESC
      LIMIT $2::int
  )
`

type PruneScansParams struct {
	LibraryID uuid.UUID
	Keep      int32
}

// A library scanned four times a day would otherwise grow a row each time.
func (q *Queries) PruneScans(ctx context.Context, arg PruneScansParams) error {
	_, err := q.db.Exec(ctx, pruneScans, arg.LibraryID, arg.Keep)
	return err
}

const queueScan = `-- name: QueueScan :one
INSERT INTO library_scans (library_id, requested_by)
VALUES ($1, $2)
ON CONFLICT (library_id) WHERE state IN ('queued', 'running') DO NOTHING
RETURNING id, library_id, state, requested_by, requested_at, job_id, started_at, finished_at, files_seen, files_added, files_changed, files_moved, files_restored, files_missing, files_skipped, books_added, error
`

type QueueScanParams struct {
	LibraryID   uuid.UUID
	RequestedBy *uuid.UUID
}

// Returns no row when the library already has a scan waiting or running.
func (q *Queries) QueueScan(ctx context.Context, arg QueueScanParams) (LibraryScan, error) {
	row := q.db.QueryRow(ctx, queueScan, arg.LibraryID, arg.RequestedBy)
	var i LibraryScan
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.State,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.JobID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FilesSeen,
		&i.FilesAdded,
		&i.FilesChanged,
		&i.FilesMoved,
		&i.FilesRestored,
		&i.FilesMissing,
		&i.FilesSkipped,
		&i.BooksAdded,
		&i.Error,
	)
	return i, err
}

const recordScanProgress = `-- name: RecordScanProgress :exec
UPDATE library_scans
SET files_seen     = $2,
    files_added    = files_added + $3,
    files_changed  = files_changed + $4,
    files_moved    = files_moved + $5,
    files_restored = files_restored + $6,
    files_missing  = files_missing + $7,
    files_skipped  = $8,
    books_added    = books_added + $9
WHERE id = $1
`

type RecordScanProgressParams struct {
	ID            uuid.UUID
	FilesSeen     int32
	FilesAdded    int32
	FilesChanged  int32
	FilesMoved    int32
	FilesRestored int32
	FilesMissing  int32
	FilesSkipped  int32
	BooksAdded    int32
}

// What one run found is added to what earlier runs of the same scan found;
// only the walk's count is of the whole library each time.
func (q *Queries) RecordScanProgress(ctx context.Context, arg RecordScanProgressParams) error {
	_, err := q.db.Exec(ctx, recordScanProgress,
		arg.ID,
		arg.FilesSeen,
		arg.FilesAdded,
		arg.FilesChanged,
		arg.FilesMoved,
		arg.FilesRestored,
		arg.FilesMissing,
		arg.FilesSkipped,
		arg.BooksAdded,
	)
	return err
}

const restoreFile = `-- name: RestoreFile :exec
UPDATE book_files
SET missing_at = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreFile, id)
	return err
}

const setFileExtractFailed = `-- name: SetFileExtractFailed :exec
UPDATE book_files
SET extract_state = 'failed', extract_error = $2, updated_at = now()
WHERE id = $1 AND sha256 = $3
`

type SetFileExtractFailedParams struct {
	ID     uuid.UUID
	Error  *string
	Sha256 []byte
}

func (q *Queries) SetFileExtractFailed(ctx context.Context, arg SetFileExtractFailedParams) error {
	_, err := q.db.Exec(ctx, setFileExtractFailed, arg.ID, arg.Error, arg.Sha256)
	return err
}

const setFileExtracted = `-- name: SetFileExtracted :execrows
UPDATE book_files
SET content_sha256  = $2,
    drm             = $3,
    has_text        = $4,
    page_count      = $5,
    pages_estimated = $6,
    duration_ms     = $7,
    track_number    = $8,
    disc_number     = $9,
    extract_state   = 'done',
    extract_error   = NULL,
    updated_at      = now()
WHERE id = $1 AND sha256 = $10
`

type SetFileExtractedParams struct {
	ID             uuid.UUID
	ContentSha256  []byte
	Drm            bool
	HasText        *bool
	PageCount      *int32
	PagesEstimated bool
	DurationMs     *int64
	TrackNumber    *int32
	DiscNumber     *int32
	Sha256         []byte
}

// Only while the file is still the one that was read: a scan that found it
// changed in the meantime has asked for it to be read again.
func (q *Queries) SetFileExtracted(ctx context.Context, arg SetFileExtractedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFileExtracted,
		arg.ID,
		arg.ContentSha256,
		arg.Drm,
		arg.HasText,
		arg.PageCount,
		arg.PagesEstimated,
		arg.DurationMs,
		arg.TrackNumber,
		arg.DiscNumber,
		arg.Sha256,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setFilePartIndex = `-- name: SetFilePartIndex :exec
UPDATE book_files
SET part_index = $2, updated_at = now()
WHERE id = $1
`

type SetFilePartIndexParams struct {
	ID        uuid.UUID
	PartIndex *int32
}

func (q *Queries) SetFilePartIndex(ctx context.Context, arg SetFilePartIndexParams) error {
	_, err := q.db.Exec(ctx, setFilePartIndex, arg.ID, arg.PartIndex)
	return err
}

const setPrimaryTextFile = `-- name: SetPrimaryTextFile :exec
UPDATE books
SET primary_text_file_id = $2
WHERE id = $1 AND primary_text_file_id IS NULL
`

type SetPrimaryTextFileParams struct {
	ID                uuid.UUID
	PrimaryTextFileID *uuid.UUID
}

// The first file of a book that has text is the one its text is read from.
func (q *Queries) SetPrimaryTextFile(ctx context.Context, arg SetPrimaryTextFileParams) error {
	_, err := q.db.Exec(ctx, setPrimaryTextFile, arg.ID, arg.PrimaryTextFileID)
	return err
}

const setScanJob = `-- name: SetScanJob :exec
UPDATE library_scans SET job_id = $2 WHERE id = $1
`

type SetScanJobParams struct {
	ID    uuid.UUID
	JobID *int64
}

func (q *Queries) SetScanJob(ctx context.Context, arg SetScanJobParams) error {
	_, err := q.db.Exec(ctx, setScanJob, arg.ID, arg.JobID)
	return err
}

const startScan = `-- name: StartScan :one
INSERT INTO library_scans (library_id, state, started_at, job_id)
VALUES ($1, 'running', now(), $2)
ON CONFLICT (library_id) WHERE state IN ('queued', 'running')
DO UPDATE SET state = 'running', started_at = COALESCE(library_scans.started_at, now())
RETURNING id, library_id, state, requested_by, requested_at, job_id, started_at, finished_at, files_seen, files_added, files_changed, files_moved, files_restored, files_missing, files_skipped, books_added, error
`

type StartScanParams struct {
	LibraryID uuid.UUID
	JobID     *int64
}

// The worker takes the library's waiting scan, or the one an earlier run left
// unfinished. A job without either still has a scan to show for its work.
func (q *Queries) StartScan(ctx context.Context, arg StartScanParams) (LibraryScan, error) {
	row := q.db.QueryRow(ctx, startScan, arg.LibraryID, arg.JobID)
	var i LibraryScan
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.State,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.JobID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.FilesSeen,
		&i.FilesAdded,
		&i.FilesChanged,
		&i.FilesMoved,
		&i.FilesRestored,
		&i.FilesMissing,
		&i.FilesSkipped,
		&i.BooksAdded,
		&i.Error,
	)
	return i, err
}

const updateFileContent = `-- name: UpdateFileContent :exec
UPDATE book_files
SET size_bytes      = $2,
    modified_at     = $3,
    original_sha256 = CASE WHEN sha256 IS DISTINCT FROM $4::bytea THEN $4::bytea ELSE original_sha256 END,
    content_sha256  = CASE WHEN sha256 IS DISTINCT FROM $4::bytea THEN NULL ELSE content_sha256 END,
    extract_state   = CASE WHEN sha256 IS DISTINCT FROM $4::bytea THEN 'pending' ELSE extract_state END,
    extract_error   = CASE WHEN sha256 IS DISTINCT FROM $4::bytea THEN NULL ELSE extract_error END,
    sha256          = $4::bytea,
    missing_at      = NULL,
    updated_at      = now()
WHERE id = $1
`

type UpdateFileContentParams struct {
	ID         uuid.UUID
	SizeBytes  int64
	ModifiedAt time.Time
	Sha256     []byte
}

// A file whose bytes changed is a file nothing has been extracted from yet.
func (q *Queries) UpdateFileContent(ctx context.Context, arg UpdateFileContentParams) error {
	_, err := q.db.Exec(ctx, updateFileContent,
		arg.ID,
		arg.SizeBytes,
		arg.ModifiedAt,
		arg.Sha256,
	)
	return err
}
