// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_index.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearAllChunked = `-- name: ClearAllChunked :exec
UPDATE book_files SET chunked_at = NULL WHERE chunked_at IS NOT NULL
`

func (q *Queries) ClearAllChunked(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearAllChunked)
	return err
}

const clearChunked = `-- name: ClearChunked :many
UPDATE book_files f SET chunked_at = NULL
FROM books b
WHERE f.id = b.primary_text_file_id
  AND b.library_id IN (SELECT visible_library_ids($1::uuid, $2::boolean))
  AND ($3::uuid IS NULL OR b.library_id = $3::uuid)
  AND ($4::uuid IS NULL OR b.id = $4::uuid)
  AND f.missing_at IS NULL AND f.trashed_at IS NULL
  AND b.deleted_at IS NULL AND NOT b.placeholder
RETURNING f.id
`

type ClearChunkedParams struct {
	Viewer    uuid.UUID
	SeesAll   bool
	LibraryID *uuid.UUID
	BookID    *uuid.UUID
}

// Marks the primary text files of the visible books, of a library or of
// one book when named, as still to be chunked. Their chunks stay, and are
// found, until the new ones replace them.
func (q *Queries) ClearChunked(ctx context.Context, arg ClearChunkedParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, clearChunked,
		arg.Viewer,
		arg.SeesAll,
		arg.LibraryID,
		arg.BookID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countChunked = `-- name: CountChunked :one
SELECT count(*) AS files, count(f.chunked_at) AS chunked
FROM books b
JOIN book_files f ON f.id = b.primary_text_file_id
WHERE b.library_id IN (SELECT visible_library_ids($1::uuid, $2::boolean))
  AND ($3::uuid IS NULL OR b.library_id = $3::uuid)
  AND f.missing_at IS NULL AND f.trashed_at IS NULL
  AND b.deleted_at IS NULL AND NOT b.placeholder
`

type CountChunkedParams struct {
	Viewer    uuid.UUID
	SeesAll   bool
	LibraryID *uuid.UUID
}

type CountChunkedRow struct {
	Files   int64
	Chunked int64
}

// How many of the visible books' primary text files, of a library when
// named, there are, and how many of them are chunked.
func (q *Queries) CountChunked(ctx context.Context, arg CountChunkedParams) (CountChunkedRow, error) {
	row := q.db.QueryRow(ctx, countChunked, arg.Viewer, arg.SeesAll, arg.LibraryID)
	var i CountChunkedRow
	err := row.Scan(&i.Files, &i.Chunked)
	return i, err
}

const getIndexVersion = `-- name: GetIndexVersion :one
SELECT version FROM index_versions WHERE name = $1
`

func (q *Queries) GetIndexVersion(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, getIndexVersion, name)
	var version string
	err := row.Scan(&version)
	return version, err
}

const setIndexVersion = `-- name: SetIndexVersion :exec
INSERT INTO index_versions (name, version) VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET version = EXCLUDED.version, updated_at = now()
`

type SetIndexVersionParams struct {
	Name    string
	Version string
}

func (q *Queries) SetIndexVersion(ctx context.Context, arg SetIndexVersionParams) error {
	_, err := q.db.Exec(ctx, setIndexVersion, arg.Name, arg.Version)
	return err
}
