// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, user_agent, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	UserAgent string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= $1::timestamptz
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :execrows
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

type DeleteUserSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteUserSession(ctx context.Context, arg DeleteUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions
WHERE user_id = $1 AND token_hash IS DISTINCT FROM $2::bytea
`

type DeleteUserSessionsParams struct {
	UserID uuid.UUID
	Keep   []byte
}

// Every session of the user but the one kept, which may be none.
func (q *Queries) DeleteUserSessions(ctx context.Context, arg DeleteUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, arg.UserID, arg.Keep)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.username, u.email, u.password_hash, u.role, u.quota_bytes, u.disabled_at, u.created_at, u.updated_at, s.last_seen_at AS session_last_seen_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > $2::timestamptz
  AND u.disabled_at IS NULL
`

type GetSessionUserParams struct {
	TokenHash []byte
	Now       time.Time
}

type GetSessionUserRow struct {
	ID                uuid.UUID
	Username          string
	Email             *string
	PasswordHash      *string
	Role              string
	QuotaBytes        *int64
	DisabledAt        *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	SessionLastSeenAt time.Time
}

// The user a live session belongs to. A disabled user has no live sessions.
func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, arg.TokenHash, arg.Now)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.QuotaBytes,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionLastSeenAt,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, token_hash, user_agent, created_at, last_seen_at, expires_at
FROM sessions
WHERE user_id = $1 AND expires_at > $2::timestamptz
ORDER BY last_seen_at DESC
`

type ListUserSessionsParams struct {
	UserID uuid.UUID
	Now    time.Time
}

type ListUserSessionsRow struct {
	ID         uuid.UUID
	TokenHash  []byte
	UserAgent  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = $3::timestamptz, expires_at = $2
WHERE token_hash = $1
`

type TouchSessionParams struct {
	TokenHash []byte
	ExpiresAt time.Time
	Now       time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.TokenHash, arg.ExpiresAt, arg.Now)
	return err
}
