// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, user_agent, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	UserAgent string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= $1::timestamptz
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.username, u.email, u.password_hash, u.role, u.quota_bytes, u.disabled_at, u.created_at, u.updated_at, s.last_seen_at AS session_last_seen_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > $2::timestamptz
  AND u.disabled_at IS NULL
`

type GetSessionUserParams struct {
	TokenHash []byte
	Now       time.Time
}

type GetSessionUserRow struct {
	ID                uuid.UUID
	Username          string
	Email             *string
	PasswordHash      *string
	Role              string
	QuotaBytes        *int64
	DisabledAt        *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	SessionLastSeenAt time.Time
}

// The user a live session belongs to. A disabled user has no live sessions.
func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, arg.TokenHash, arg.Now)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.QuotaBytes,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionLastSeenAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = $3::timestamptz, expires_at = $2
WHERE token_hash = $1
`

type TouchSessionParams struct {
	TokenHash []byte
	ExpiresAt time.Time
	Now       time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.TokenHash, arg.ExpiresAt, arg.Now)
	return err
}
