// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addKeyCheck = `-- name: AddKeyCheck :exec
INSERT INTO settings (key, sealed) VALUES ($1, $2)
ON CONFLICT (key) DO NOTHING
`

type AddKeyCheckParams struct {
	Key    string
	Sealed []byte
}

// The first start under a key leaves this behind; every later one opens it.
func (q *Queries) AddKeyCheck(ctx context.Context, arg AddKeyCheckParams) error {
	_, err := q.db.Exec(ctx, addKeyCheck, arg.Key, arg.Sealed)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT key, value, sealed, updated_at, updated_by FROM settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Sealed,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, sealed, updated_at, updated_by FROM settings
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Sealed,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (key, value, sealed, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, sealed = EXCLUDED.sealed,
    updated_by = EXCLUDED.updated_by, updated_at = now()
`

type PutSettingParams struct {
	Key       string
	Value     *string
	Sealed    []byte
	UpdatedBy *uuid.UUID
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.Exec(ctx, putSetting,
		arg.Key,
		arg.Value,
		arg.Sealed,
		arg.UpdatedBy,
	)
	return err
}
