// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: smart_shelves.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSmartShelf = `-- name: CreateSmartShelf :one
INSERT INTO smart_shelves (owner_id, name, filter, visibility)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateSmartShelfParams struct {
	OwnerID    uuid.UUID
	Name       string
	Filter     []byte
	Visibility string
}

func (q *Queries) CreateSmartShelf(ctx context.Context, arg CreateSmartShelfParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSmartShelf,
		arg.OwnerID,
		arg.Name,
		arg.Filter,
		arg.Visibility,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSmartShelf = `-- name: DeleteSmartShelf :exec
DELETE FROM smart_shelves WHERE id = $1
`

func (q *Queries) DeleteSmartShelf(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSmartShelf, id)
	return err
}

const getSmartShelf = `-- name: GetSmartShelf :one
SELECT s.id, s.owner_id, u.username::text AS owner_name, s.name, s.filter, s.visibility, s.updated_at
FROM smart_shelves s
JOIN users u ON u.id = s.owner_id
WHERE s.id = $1 AND (s.owner_id = $2::uuid OR s.visibility = 'shared')
`

type GetSmartShelfParams struct {
	ID     uuid.UUID
	Viewer uuid.UUID
}

type GetSmartShelfRow struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	OwnerName  string
	Name       string
	Filter     []byte
	Visibility string
	UpdatedAt  time.Time
}

func (q *Queries) GetSmartShelf(ctx context.Context, arg GetSmartShelfParams) (GetSmartShelfRow, error) {
	row := q.db.QueryRow(ctx, getSmartShelf, arg.ID, arg.Viewer)
	var i GetSmartShelfRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OwnerName,
		&i.Name,
		&i.Filter,
		&i.Visibility,
		&i.UpdatedAt,
	)
	return i, err
}

const listSmartShelves = `-- name: ListSmartShelves :many
SELECT s.id, s.owner_id, u.username::text AS owner_name, s.name, s.filter, s.visibility, s.updated_at
FROM smart_shelves s
JOIN users u ON u.id = s.owner_id
WHERE s.owner_id = $1::uuid OR s.visibility = 'shared'
ORDER BY s.owner_id = $1::uuid DESC, lower(s.name), s.id
`

type ListSmartShelvesRow struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	OwnerName  string
	Name       string
	Filter     []byte
	Visibility string
	UpdatedAt  time.Time
}

// The viewer's own smart shelves and everyone's shared ones.
func (q *Queries) ListSmartShelves(ctx context.Context, viewer uuid.UUID) ([]ListSmartShelvesRow, error) {
	rows, err := q.db.Query(ctx, listSmartShelves, viewer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSmartShelvesRow{}
	for rows.Next() {
		var i ListSmartShelvesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.OwnerName,
			&i.Name,
			&i.Filter,
			&i.Visibility,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSmartShelf = `-- name: LockSmartShelf :one
SELECT owner_id, visibility FROM smart_shelves WHERE id = $1 FOR UPDATE
`

type LockSmartShelfRow struct {
	OwnerID    uuid.UUID
	Visibility string
}

func (q *Queries) LockSmartShelf(ctx context.Context, id uuid.UUID) (LockSmartShelfRow, error) {
	row := q.db.QueryRow(ctx, lockSmartShelf, id)
	var i LockSmartShelfRow
	err := row.Scan(&i.OwnerID, &i.Visibility)
	return i, err
}

const updateSmartShelf = `-- name: UpdateSmartShelf :exec
UPDATE smart_shelves
SET name = $2, filter = $3, visibility = $4, updated_at = now()
WHERE id = $1
`

type UpdateSmartShelfParams struct {
	ID         uuid.UUID
	Name       string
	Filter     []byte
	Visibility string
}

func (q *Queries) UpdateSmartShelf(ctx context.Context, arg UpdateSmartShelfParams) error {
	_, err := q.db.Exec(ctx, updateSmartShelf,
		arg.ID,
		arg.Name,
		arg.Filter,
		arg.Visibility,
	)
	return err
}
