// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trash.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTrashedFile = `-- name: DeleteTrashedFile :exec
DELETE FROM book_files WHERE id = $1 AND trashed_at IS NOT NULL
`

func (q *Queries) DeleteTrashedFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrashedFile, id)
	return err
}

const getFileToTrash = `-- name: GetFileToTrash :one
SELECT f.id, f.book_id, f.library_id, f.rel_path, f.missing_at, f.trashed_at,
       l.root_path, l.writable
FROM book_files f
JOIN libraries l ON l.id = f.library_id
WHERE f.id = $1
  AND f.library_id IN (SELECT visible_library_ids FROM visible_library_ids($2::uuid, $3::boolean))
`

type GetFileToTrashParams struct {
	ID      uuid.UUID
	Viewer  uuid.UUID
	SeesAll bool
}

type GetFileToTrashRow struct {
	ID        uuid.UUID
	BookID    uuid.UUID
	LibraryID uuid.UUID
	RelPath   string
	MissingAt *time.Time
	TrashedAt *time.Time
	RootPath  string
	Writable  bool
}

// A file of a library the viewer sees, with what moving it needs.
func (q *Queries) GetFileToTrash(ctx context.Context, arg GetFileToTrashParams) (GetFileToTrashRow, error) {
	row := q.db.QueryRow(ctx, getFileToTrash, arg.ID, arg.Viewer, arg.SeesAll)
	var i GetFileToTrashRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.LibraryID,
		&i.RelPath,
		&i.MissingAt,
		&i.TrashedAt,
		&i.RootPath,
		&i.Writable,
	)
	return i, err
}

const getTrashedFile = `-- name: GetTrashedFile :one
SELECT f.id, f.book_id, f.rel_path, l.root_path
FROM book_files f JOIN libraries l ON l.id = f.library_id
WHERE f.id = $1 AND f.trashed_at IS NOT NULL
FOR UPDATE OF f
`

type GetTrashedFileRow struct {
	ID       uuid.UUID
	BookID   uuid.UUID
	RelPath  string
	RootPath string
}

func (q *Queries) GetTrashedFile(ctx context.Context, id uuid.UUID) (GetTrashedFileRow, error) {
	row := q.db.QueryRow(ctx, getTrashedFile, id)
	var i GetTrashedFileRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.RelPath,
		&i.RootPath,
	)
	return i, err
}

const listExpiredTrash = `-- name: ListExpiredTrash :many
SELECT id FROM book_files WHERE trashed_at < $1::timestamptz ORDER BY trashed_at
`

func (q *Queries) ListExpiredTrash(ctx context.Context, before time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredTrash, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrash = `-- name: ListTrash :many
SELECT f.id, f.rel_path, f.format, f.size_bytes, f.trashed_at::timestamptz AS trashed_at,
       f.book_id, b.title, l.id AS library_id, l.name AS library_name,
       u.username AS trashed_by
FROM book_files f
JOIN books b ON b.id = f.book_id
JOIN libraries l ON l.id = f.library_id
LEFT JOIN users u ON u.id = f.trashed_by
WHERE f.trashed_at IS NOT NULL
  AND f.library_id IN (SELECT visible_library_ids FROM visible_library_ids($1::uuid, $2::boolean))
  AND ($3::uuid IS NULL OR f.library_id = $3::uuid)
ORDER BY f.trashed_at DESC, f.id DESC
`

type ListTrashParams struct {
	Viewer    uuid.UUID
	SeesAll   bool
	LibraryID *uuid.UUID
}

type ListTrashRow struct {
	ID          uuid.UUID
	RelPath     string
	Format      string
	SizeBytes   int64
	TrashedAt   time.Time
	BookID      uuid.UUID
	Title       string
	LibraryID   uuid.UUID
	LibraryName string
	TrashedBy   *string
}

// The trashed files of the libraries the viewer sees, of one when named,
// the latest first.
func (q *Queries) ListTrash(ctx context.Context, arg ListTrashParams) ([]ListTrashRow, error) {
	rows, err := q.db.Query(ctx, listTrash, arg.Viewer, arg.SeesAll, arg.LibraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrashRow{}
	for rows.Next() {
		var i ListTrashRow
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.Format,
			&i.SizeBytes,
			&i.TrashedAt,
			&i.BookID,
			&i.Title,
			&i.LibraryID,
			&i.LibraryName,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileRestored = `-- name: SetFileRestored :exec
UPDATE book_files SET trashed_at = NULL, trashed_by = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) SetFileRestored(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setFileRestored, id)
	return err
}

const setFileTrashed = `-- name: SetFileTrashed :exec
UPDATE book_files
SET trashed_at = now(), trashed_by = $1, chunked_at = NULL, updated_at = now()
WHERE id = $2
`

type SetFileTrashedParams struct {
	By *uuid.UUID
	ID uuid.UUID
}

func (q *Queries) SetFileTrashed(ctx context.Context, arg SetFileTrashedParams) error {
	_, err := q.db.Exec(ctx, setFileTrashed, arg.By, arg.ID)
	return err
}
