// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const findVisibleFileByHash = `-- name: FindVisibleFileByHash :one
SELECT b.id AS book_id, b.library_id, b.title
FROM book_files f
JOIN books b ON b.id = f.book_id
WHERE f.sha256 = $1
  AND f.missing_at IS NULL AND f.trashed_at IS NULL AND b.deleted_at IS NULL
  AND f.library_id IN (SELECT visible_library_ids FROM visible_library_ids($2::uuid, $3::boolean))
ORDER BY f.created_at, f.id
LIMIT 1
`

type FindVisibleFileByHashParams struct {
	Sha256  []byte
	Viewer  uuid.UUID
	SeesAll bool
}

type FindVisibleFileByHashRow struct {
	BookID    uuid.UUID
	LibraryID uuid.UUID
	Title     string
}

// A file with exactly these bytes in a library the viewer may see, the
// oldest first. Files that are gone or in the trash do not count.
func (q *Queries) FindVisibleFileByHash(ctx context.Context, arg FindVisibleFileByHashParams) (FindVisibleFileByHashRow, error) {
	row := q.db.QueryRow(ctx, findVisibleFileByHash, arg.Sha256, arg.Viewer, arg.SeesAll)
	var i FindVisibleFileByHashRow
	err := row.Scan(&i.BookID, &i.LibraryID, &i.Title)
	return i, err
}

const getBookTitle = `-- name: GetBookTitle :one
SELECT title FROM books WHERE id = $1
`

func (q *Queries) GetBookTitle(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getBookTitle, id)
	var title string
	err := row.Scan(&title)
	return title, err
}

const getUserStorage = `-- name: GetUserStorage :one
SELECT u.quota_bytes, COALESCE(s.used_bytes, 0)::bigint AS used_bytes
FROM users u
LEFT JOIN storage_use s ON s.user_id = u.id
WHERE u.id = $1
`

type GetUserStorageRow struct {
	QuotaBytes *int64
	UsedBytes  int64
}

func (q *Queries) GetUserStorage(ctx context.Context, id uuid.UUID) (GetUserStorageRow, error) {
	row := q.db.QueryRow(ctx, getUserStorage, id)
	var i GetUserStorageRow
	err := row.Scan(&i.QuotaBytes, &i.UsedBytes)
	return i, err
}

const listFolderFiles = `-- name: ListFolderFiles :many
SELECT id, book_id, rel_path, part_index
FROM book_files
WHERE library_id = $1 AND trashed_at IS NULL
  AND starts_with(rel_path, $2::text || '/')
`

type ListFolderFilesParams struct {
	LibraryID uuid.UUID
	Folder    string
}

type ListFolderFilesRow struct {
	ID        uuid.UUID
	BookID    uuid.UUID
	RelPath   string
	PartIndex *int32
}

// The files below one folder of a library, for grouping a new file with them.
func (q *Queries) ListFolderFiles(ctx context.Context, arg ListFolderFilesParams) ([]ListFolderFilesRow, error) {
	rows, err := q.db.Query(ctx, listFolderFiles, arg.LibraryID, arg.Folder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFolderFilesRow{}
	for rows.Next() {
		var i ListFolderFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.RelPath,
			&i.PartIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTakenPaths = `-- name: ListTakenPaths :many
SELECT rel_path
FROM book_files
WHERE library_id = $1 AND rel_path = ANY ($2::text[])
`

type ListTakenPathsParams struct {
	LibraryID uuid.UUID
	Paths     []string
}

func (q *Queries) ListTakenPaths(ctx context.Context, arg ListTakenPathsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listTakenPaths, arg.LibraryID, arg.Paths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var rel_path string
		if err := rows.Scan(&rel_path); err != nil {
			return nil, err
		}
		items = append(items, rel_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLibraryFiles = `-- name: LockLibraryFiles :exec
SELECT pg_advisory_xact_lock(hashtextextended('book_files:' || $1::uuid::text, 0))
`

// Uploads and scans both add files to a library. Whoever holds this lock
// until the end of their transaction is the only one choosing new paths in
// it, and sees every path the other has taken.
func (q *Queries) LockLibraryFiles(ctx context.Context, libraryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockLibraryFiles, libraryID)
	return err
}

const lockUserStorage = `-- name: LockUserStorage :exec
SELECT pg_advisory_xact_lock(hashtextextended('storage:' || $1::uuid::text, 0))
`

// Two uploads of one user at once must not both find room for themselves.
func (q *Queries) LockUserStorage(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockUserStorage, userID)
	return err
}
