// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vectors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteBookVector = `-- name: DeleteBookVector :exec
DELETE FROM book_vectors WHERE book_id = $1 AND kind = $2
`

type DeleteBookVectorParams struct {
	BookID uuid.UUID
	Kind   string
}

func (q *Queries) DeleteBookVector(ctx context.Context, arg DeleteBookVectorParams) error {
	_, err := q.db.Exec(ctx, deleteBookVector, arg.BookID, arg.Kind)
	return err
}

const deleteVectorsOfGoneBooks = `-- name: DeleteVectorsOfGoneBooks :execrows
DELETE FROM book_vectors v USING books b
WHERE b.id = v.book_id AND (b.deleted_at IS NOT NULL OR b.placeholder)
`

// Deleted, merged and placeholder books have none.
func (q *Queries) DeleteVectorsOfGoneBooks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVectorsOfGoneBooks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBookMetadataText = `-- name: GetBookMetadataText :one
SELECT coalesce(book_metadata_text($1::uuid), '')::text
`

func (q *Queries) GetBookMetadataText(ctx context.Context, bookID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getBookMetadataText, bookID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const listBooksToEmbed = `-- name: ListBooksToEmbed :many
SELECT b.id AS book_id,
       f.id AS text_file_id,
       h.content_hash::bytea AS content_hash,
       (mv.book_id IS NULL OR mv.model <> $1::text
        OR mv.model_version <> $2::text
        OR mv.source_hash <> h.metadata_hash)::boolean AS metadata_stale,
       (h.content_hash IS NOT NULL
        AND (cv.book_id IS NULL OR cv.model <> $1::text
             OR cv.model_version <> $2::text
             OR cv.source_hash <> h.content_hash))::boolean AS content_stale,
       (h.content_hash IS NULL AND cv.book_id IS NOT NULL)::boolean AS content_gone
FROM books b
LEFT JOIN book_files f ON f.id = b.primary_text_file_id AND f.chunked_at IS NOT NULL
CROSS JOIN LATERAL (
    SELECT sha256(convert_to(book_metadata_text(b.id), 'UTF8')) AS metadata_hash,
           CASE WHEN f.id IS NOT NULL THEN
               sha256(convert_to(f.id::text || ' ' || f.chunked_at::text || ' ' || $3::text, 'UTF8'))
           END::bytea AS content_hash
) h
LEFT JOIN book_vectors mv ON mv.book_id = b.id AND mv.kind = 'metadata'
LEFT JOIN book_vectors cv ON cv.book_id = b.id AND cv.kind = 'content'
WHERE b.deleted_at IS NULL AND NOT b.placeholder AND b.id > $4::uuid
ORDER BY b.id
LIMIT $5::int
`

type ListBooksToEmbedParams struct {
	Model        string
	ModelVersion string
	Recipe       string
	After        uuid.UUID
	Page         int32
}

type ListBooksToEmbedRow struct {
	BookID        uuid.UUID
	TextFileID    *uuid.UUID
	ContentHash   []byte
	MetadataStale bool
	ContentStale  bool
	ContentGone   bool
}

// A page of books after the given one, in ID order, and whether each one's
// vectors are missing, of another model or made from something that has
// changed since. The content's source is the primary text file as it was
// chunked (its ID, when, and how it is sampled); a book without one has no
// content vector, and content_gone says one is still stored.
func (q *Queries) ListBooksToEmbed(ctx context.Context, arg ListBooksToEmbedParams) ([]ListBooksToEmbedRow, error) {
	rows, err := q.db.Query(ctx, listBooksToEmbed,
		arg.Model,
		arg.ModelVersion,
		arg.Recipe,
		arg.After,
		arg.Page,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksToEmbedRow{}
	for rows.Next() {
		var i ListBooksToEmbedRow
		if err := rows.Scan(
			&i.BookID,
			&i.TextFileID,
			&i.ContentHash,
			&i.MetadataStale,
			&i.ContentStale,
			&i.ContentGone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunkBodies = `-- name: ListChunkBodies :many
SELECT coalesce(body_en, body_de, body_xx)::text AS body
FROM book_chunks
WHERE file_id = $1 AND position = ANY($2::int[])
ORDER BY position
`

type ListChunkBodiesParams struct {
	FileID    uuid.UUID
	Positions []int32
}

func (q *Queries) ListChunkBodies(ctx context.Context, arg ListChunkBodiesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listChunkBodies, arg.FileID, arg.Positions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var body string
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunkPositions = `-- name: ListChunkPositions :many
SELECT position FROM book_chunks WHERE file_id = $1 ORDER BY position
`

func (q *Queries) ListChunkPositions(ctx context.Context, fileID uuid.UUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, listChunkPositions, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var position int32
		if err := rows.Scan(&position); err != nil {
			return nil, err
		}
		items = append(items, position)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putBookVector = `-- name: PutBookVector :exec
INSERT INTO book_vectors (book_id, kind, model, model_version, source_hash, embedding)
SELECT b.id, $1::text, $2::text, $3::text,
       $4::bytea, CAST($5::text AS vector)
FROM books b WHERE b.id = $6::uuid AND b.deleted_at IS NULL
ON CONFLICT (book_id, kind) DO UPDATE
SET model = excluded.model, model_version = excluded.model_version,
    source_hash = excluded.source_hash, embedding = excluded.embedding, embedded_at = now()
`

type PutBookVectorParams struct {
	Kind         string
	Model        string
	ModelVersion string
	SourceHash   []byte
	Embedding    string
	BookID       uuid.UUID
}

// Nothing is stored for a book deleted since it was read.
func (q *Queries) PutBookVector(ctx context.Context, arg PutBookVectorParams) error {
	_, err := q.db.Exec(ctx, putBookVector,
		arg.Kind,
		arg.Model,
		arg.ModelVersion,
		arg.SourceHash,
		arg.Embedding,
		arg.BookID,
	)
	return err
}
