// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vectors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteBookVector = `-- name: DeleteBookVector :exec
DELETE FROM book_vectors WHERE book_id = $1 AND kind = $2
`

type DeleteBookVectorParams struct {
	BookID uuid.UUID
	Kind   string
}

// Of every model: what it was made from is gone.
func (q *Queries) DeleteBookVector(ctx context.Context, arg DeleteBookVectorParams) error {
	_, err := q.db.Exec(ctx, deleteBookVector, arg.BookID, arg.Kind)
	return err
}

const deleteVectorsOfGoneBooks = `-- name: DeleteVectorsOfGoneBooks :execrows
DELETE FROM book_vectors v USING books b
WHERE b.id = v.book_id AND (b.deleted_at IS NOT NULL OR b.placeholder)
`

// Deleted, merged and placeholder books have none.
func (q *Queries) DeleteVectorsOfGoneBooks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVectorsOfGoneBooks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBookMetadataText = `-- name: GetBookMetadataText :one
SELECT coalesce(book_metadata_text($1::uuid), '')::text
`

func (q *Queries) GetBookMetadataText(ctx context.Context, bookID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getBookMetadataText, bookID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const listBookTitles = `-- name: ListBookTitles :many
SELECT b.id, b.title,
       COALESCE((SELECT a.name FROM book_contributors c JOIN authors a ON a.id = c.author_id
                 WHERE c.book_id = b.id AND c.role = 'author' ORDER BY c.position LIMIT 1), '')::text AS author
FROM books b
WHERE b.id = ANY($1::uuid[])
`

type ListBookTitlesRow struct {
	ID     uuid.UUID
	Title  string
	Author string
}

// Books by their title and first author, for a check to print.
func (q *Queries) ListBookTitles(ctx context.Context, ids []uuid.UUID) ([]ListBookTitlesRow, error) {
	rows, err := q.db.Query(ctx, listBookTitles, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookTitlesRow{}
	for rows.Next() {
		var i ListBookTitlesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Author); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookTraits = `-- name: ListBookTraits :many
SELECT b.id, b.title, b.series_id,
       COALESCE(array_agg(a.person_key ORDER BY c.position) FILTER (WHERE a.person_key IS NOT NULL), '{}')::text[] AS people
FROM books b
LEFT JOIN book_contributors c ON c.book_id = b.id AND c.role = 'author'
LEFT JOIN authors a ON a.id = c.author_id
WHERE b.id = ANY($1::uuid[])
GROUP BY b.id
`

type ListBookTraitsRow struct {
	ID       uuid.UUID
	Title    string
	SeriesID *uuid.UUID
	People   []string
}

// What a similar-check compares books by: the title, the series and the
// authors, each by person_key.
func (q *Queries) ListBookTraits(ctx context.Context, ids []uuid.UUID) ([]ListBookTraitsRow, error) {
	rows, err := q.db.Query(ctx, listBookTraits, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookTraitsRow{}
	for rows.Next() {
		var i ListBookTraitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SeriesID,
			&i.People,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksNearQuery = `-- name: ListBooksNearQuery :many
WITH near AS (
    SELECT v.book_id,
           max(1 - (v.embedding <=> $6::text::vector)) FILTER (WHERE v.kind = 'content') AS content,
           max(1 - (v.embedding <=> $6::text::vector)) FILTER (WHERE v.kind = 'metadata') AS metadata
    FROM book_vectors v
    WHERE v.model = $7::text AND v.model_version = $8::text
    GROUP BY v.book_id
)
SELECT n.book_id,
       (CASE WHEN n.content IS NOT NULL AND n.metadata IS NOT NULL
             THEN 0.6 * n.content + 0.4 * n.metadata
             ELSE coalesce(n.content, n.metadata)
        END)::float8 AS score
FROM near n
JOIN books b ON b.id = n.book_id
WHERE b.deleted_at IS NULL AND NOT b.placeholder
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($1::uuid, $2::boolean))
  AND ($3::uuid IS NULL OR b.library_id = $3::uuid)
ORDER BY score DESC, n.book_id
LIMIT $5::int OFFSET $4::int
`

type ListBooksNearQueryParams struct {
	Viewer       uuid.UUID
	SeesAll      bool
	LibraryID    *uuid.UUID
	Skip         int32
	Max          int32
	Query        string
	Model        string
	ModelVersion string
}

type ListBooksNearQueryRow struct {
	BookID uuid.UUID
	Score  float64
}

// The books whose vectors of the model are nearest a query's, among those
// the viewer sees, of one library when named, as ListSimilarBooks blends
// them: the best first, a page at a time.
func (q *Queries) ListBooksNearQuery(ctx context.Context, arg ListBooksNearQueryParams) ([]ListBooksNearQueryRow, error) {
	rows, err := q.db.Query(ctx, listBooksNearQuery,
		arg.Viewer,
		arg.SeesAll,
		arg.LibraryID,
		arg.Skip,
		arg.Max,
		arg.Query,
		arg.Model,
		arg.ModelVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksNearQueryRow{}
	for rows.Next() {
		var i ListBooksNearQueryRow
		if err := rows.Scan(&i.BookID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksToEmbed = `-- name: ListBooksToEmbed :many
SELECT b.id AS book_id,
       f.id AS text_file_id,
       h.content_hash::bytea AS content_hash,
       (mv.book_id IS NULL OR mv.model_version <> $1::text
        OR mv.source_hash <> h.metadata_hash)::boolean AS metadata_stale,
       (h.content_hash IS NOT NULL
        AND (cv.book_id IS NULL OR cv.model_version <> $1::text
             OR cv.source_hash <> h.content_hash))::boolean AS content_stale,
       (h.content_hash IS NULL AND cv.book_id IS NOT NULL)::boolean AS content_gone
FROM books b
LEFT JOIN book_files f ON f.id = b.primary_text_file_id AND f.chunked_at IS NOT NULL
CROSS JOIN LATERAL (
    SELECT sha256(convert_to(book_metadata_text(b.id), 'UTF8')) AS metadata_hash,
           CASE WHEN f.id IS NOT NULL THEN
               sha256(convert_to(f.id::text || ' ' || f.chunked_at::text || ' ' || $2::text, 'UTF8'))
           END::bytea AS content_hash
) h
LEFT JOIN book_vectors mv ON mv.book_id = b.id AND mv.kind = 'metadata' AND mv.model = $3::text
LEFT JOIN book_vectors cv ON cv.book_id = b.id AND cv.kind = 'content' AND cv.model = $3::text
WHERE b.deleted_at IS NULL AND NOT b.placeholder AND b.id > $4::uuid
ORDER BY b.id
LIMIT $5::int
`

type ListBooksToEmbedParams struct {
	ModelVersion string
	Recipe       string
	Model        string
	After        uuid.UUID
	Page         int32
}

type ListBooksToEmbedRow struct {
	BookID        uuid.UUID
	TextFileID    *uuid.UUID
	ContentHash   []byte
	MetadataStale bool
	ContentStale  bool
	ContentGone   bool
}

// A page of books after the given one, in ID order, and whether each one's
// vectors of the model are missing, of another version of it or made from
// something that has changed since. The content's source is the primary text file as it was
// chunked (its ID, when, and how it is sampled); a book without one has no
// content vector, and content_gone says one is still stored.
func (q *Queries) ListBooksToEmbed(ctx context.Context, arg ListBooksToEmbedParams) ([]ListBooksToEmbedRow, error) {
	rows, err := q.db.Query(ctx, listBooksToEmbed,
		arg.ModelVersion,
		arg.Recipe,
		arg.Model,
		arg.After,
		arg.Page,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksToEmbedRow{}
	for rows.Next() {
		var i ListBooksToEmbedRow
		if err := rows.Scan(
			&i.BookID,
			&i.TextFileID,
			&i.ContentHash,
			&i.MetadataStale,
			&i.ContentStale,
			&i.ContentGone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunkBodies = `-- name: ListChunkBodies :many
SELECT coalesce(body_en, body_de, body_xx)::text AS body
FROM book_chunks
WHERE file_id = $1 AND position = ANY($2::int[])
ORDER BY position
`

type ListChunkBodiesParams struct {
	FileID    uuid.UUID
	Positions []int32
}

func (q *Queries) ListChunkBodies(ctx context.Context, arg ListChunkBodiesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listChunkBodies, arg.FileID, arg.Positions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var body string
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunkPositions = `-- name: ListChunkPositions :many
SELECT position FROM book_chunks WHERE file_id = $1 ORDER BY position
`

func (q *Queries) ListChunkPositions(ctx context.Context, fileID uuid.UUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, listChunkPositions, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var position int32
		if err := rows.Scan(&position); err != nil {
			return nil, err
		}
		items = append(items, position)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimilarBooks = `-- name: ListSimilarBooks :many
WITH mine AS (
    SELECT v.kind, v.embedding
    FROM book_vectors v
    WHERE v.book_id = $3::uuid
      AND v.model = $5::text AND v.model_version = $6::text
),
near AS (
    SELECT v.book_id,
           max(1 - (v.embedding <=> m.embedding)) FILTER (WHERE v.kind = 'content') AS content,
           max(1 - (v.embedding <=> m.embedding)) FILTER (WHERE v.kind = 'metadata') AS metadata
    FROM book_vectors v
    JOIN mine m ON m.kind = v.kind
    WHERE v.model = $5::text AND v.model_version = $6::text
      AND v.book_id <> $3::uuid
    GROUP BY v.book_id
)
SELECT n.book_id,
       (CASE WHEN n.content IS NOT NULL AND n.metadata IS NOT NULL
             THEN 0.6 * n.content + 0.4 * n.metadata
             ELSE coalesce(n.content, n.metadata)
        END)::float8 AS score
FROM near n
JOIN books b ON b.id = n.book_id
WHERE b.deleted_at IS NULL AND NOT b.placeholder
  AND b.library_id IN (SELECT visible_library_ids FROM visible_library_ids($1::uuid, $2::boolean))
  AND NOT EXISTS (
      SELECT 1 FROM duplicate_pairs p
      WHERE (p.book_a, p.book_b) IN ((n.book_id, $3::uuid), ($3::uuid, n.book_id)))
  AND NOT EXISTS (
      SELECT 1 FROM book_relations r
      WHERE (r.book_a, r.book_b) IN ((n.book_id, $3::uuid), ($3::uuid, n.book_id)))
ORDER BY score DESC, n.book_id
LIMIT $4::int
`

type ListSimilarBooksParams struct {
	Viewer       uuid.UUID
	SeesAll      bool
	BookID       uuid.UUID
	Max          int32
	Model        string
	ModelVersion string
}

type ListSimilarBooksRow struct {
	BookID uuid.UUID
	Score  float64
}

// The books nearest the given one among those the viewer sees, by the
// cosine of their vectors of the model: an exact scan, which at two vectors
// a book needs no index. Where two books both have a content and a metadata
// vector the two are blended, the text weighing more, as it says more of
// what a book is about than its description; otherwise the kind they share
// decides. The book itself, books it is known to be a copy of (a duplicate
// pair in any state) and books it is related to are left out.
func (q *Queries) ListSimilarBooks(ctx context.Context, arg ListSimilarBooksParams) ([]ListSimilarBooksRow, error) {
	rows, err := q.db.Query(ctx, listSimilarBooks,
		arg.Viewer,
		arg.SeesAll,
		arg.BookID,
		arg.Max,
		arg.Model,
		arg.ModelVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSimilarBooksRow{}
	for rows.Next() {
		var i ListSimilarBooksRow
		if err := rows.Scan(&i.BookID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimilarCheckSample = `-- name: ListSimilarCheckSample :many
WITH people AS (
    SELECT a.person_key, count(DISTINCT c.book_id) AS books
    FROM book_contributors c
    JOIN authors a ON a.id = c.author_id
    JOIN books b ON b.id = c.book_id
    WHERE c.role = 'author' AND b.deleted_at IS NULL AND NOT b.placeholder
    GROUP BY a.person_key
)
SELECT b.id
FROM books b
WHERE b.deleted_at IS NULL AND NOT b.placeholder
  AND EXISTS (SELECT 1 FROM book_vectors v
              WHERE v.book_id = b.id AND v.kind = 'content'
                AND v.model = $1::text AND v.model_version = $2::text)
  AND EXISTS (SELECT 1 FROM book_contributors c
              JOIN authors a ON a.id = c.author_id
              JOIN people p ON p.person_key = a.person_key
              WHERE c.book_id = b.id AND c.role = 'author' AND p.books >= $3::int)
ORDER BY md5(b.id::text)
LIMIT $4::int
`

type ListSimilarCheckSampleParams struct {
	Model        string
	ModelVersion string
	MinBooks     int32
	Max          int32
}

// The books a similar-check asks about: with a content vector of the model,
// by an author with at least min_books books in either order of the name,
// in the order of a hash of their ID, so a library gives the same sample
// each time.
func (q *Queries) ListSimilarCheckSample(ctx context.Context, arg ListSimilarCheckSampleParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSimilarCheckSample,
		arg.Model,
		arg.ModelVersion,
		arg.MinBooks,
		arg.Max,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putBookVector = `-- name: PutBookVector :exec
INSERT INTO book_vectors (book_id, kind, model, model_version, source_hash, embedding)
SELECT b.id, $1::text, $2::text, $3::text,
       $4::bytea, CAST($5::text AS vector)
FROM books b WHERE b.id = $6::uuid AND b.deleted_at IS NULL
ON CONFLICT (book_id, kind, model) DO UPDATE
SET model_version = excluded.model_version,
    source_hash = excluded.source_hash, embedding = excluded.embedding, embedded_at = now()
`

type PutBookVectorParams struct {
	Kind         string
	Model        string
	ModelVersion string
	SourceHash   []byte
	Embedding    string
	BookID       uuid.UUID
}

// Nothing is stored for a book deleted since it was read.
func (q *Queries) PutBookVector(ctx context.Context, arg PutBookVectorParams) error {
	_, err := q.db.Exec(ctx, putBookVector,
		arg.Kind,
		arg.Model,
		arg.ModelVersion,
		arg.SourceHash,
		arg.Embedding,
		arg.BookID,
	)
	return err
}
