/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with user name and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is signed in */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One page of the books the caller may see, in one library or all */
        get: operations["listBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One book with everything that describes it and its files */
        get: operations["getBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{bookId}/covers/{size}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A book's cover as a JPEG; size is small or large */
        get: operations["getBookCover"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{fileId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A book's file as it lies on disk; answers range requests */
        get: operations["downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The libraries the caller may see */
        get: operations["listLibraries"];
        put?: never;
        /** Add a library */
        post: operations["createLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{libraryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One library, if the caller may see it */
        get: operations["getLibrary"];
        put?: never;
        post?: never;
        /** Remove a library from GOtome; its folder and files stay */
        delete: operations["deleteLibrary"];
        options?: never;
        head?: never;
        /** Change a library's name, visibility or whether GOtome may write to it */
        patch: operations["updateLibrary"];
        trace?: never;
    };
    "/libraries/{libraryId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who may see a private library besides its owner */
        get: operations["listLibraryMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{libraryId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Let a user see a private library */
        put: operations["addLibraryMember"];
        post?: never;
        /** Take a private library away from a user again */
        delete: operations["removeLibraryMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{libraryId}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Look through a library's folder for new, changed and missing files */
        post: operations["scanLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the first account still has to be created */
        get: operations["getSetup"];
        put?: never;
        /** Create the first account, an administrator, and sign in as it */
        post: operations["completeSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which build of GOtome is running */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Why a request failed. */
        APIError: {
            code: string;
            fields?: {
                [key: string]: string;
            };
            message: string;
            requestId?: string;
        };
        BookDetail: {
            /** Format: date-time */
            addedAt: string;
            contributors: components["schemas"]["Contributor"][];
            coverKey?: string;
            description?: string;
            durationMs?: number;
            files: components["schemas"]["BookFile"][];
            /** Format: uuid */
            id: string;
            identifiers: components["schemas"]["Identifier"][];
            language?: string;
            /** Format: uuid */
            libraryId: string;
            pageCount?: number;
            published?: string;
            publisher?: string;
            series?: string;
            seriesIndex?: number;
            subtitle?: string;
            tags: string[];
            title: string;
        };
        BookFile: {
            drm: boolean;
            durationMs?: number;
            format: string;
            hasText?: boolean;
            /** Format: uuid */
            id: string;
            kind: string;
            missing: boolean;
            name: string;
            pageCount?: number;
            part?: number;
            relPath?: string;
            size: number;
        };
        BookList: {
            books: components["schemas"]["BookSummary"][];
            nextCursor?: string;
        };
        BookSummary: {
            /** Format: date-time */
            addedAt: string;
            authors: string[];
            coverKey?: string;
            formats: string[];
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            libraryId: string;
            publishedYear?: number;
            series?: string;
            seriesIndex?: number;
            subtitle?: string;
            title: string;
        };
        BuildInfo: {
            commit?: string;
            version: string;
        };
        Contributor: {
            name: string;
            role: string;
        };
        CreateLibraryRequest: {
            mode: string;
            name: string;
            rootPath?: string;
            visibility: string;
            writable?: boolean;
        };
        CurrentUser: {
            email?: string;
            /** Format: uuid */
            id: string;
            permissions: ("library:read" | "personal:manage" | "books:upload" | "metadata:edit" | "index:rebuild" | "users:manage" | "settings:manage" | "storage:manage")[];
            role: string;
            username: string;
        };
        ErrorEnvelope: {
            error: components["schemas"]["APIError"];
        };
        Identifier: {
            type: string;
            value: string;
        };
        LibraryList: {
            libraries: components["schemas"]["LibraryResponse"][];
        };
        LibraryResponse: {
            /** Format: date-time */
            createdAt: string;
            filesPending: number;
            /** Format: uuid */
            id: string;
            lastScan?: components["schemas"]["Scan"];
            mode: string;
            name: string;
            /** Format: uuid */
            ownerId?: string;
            rootPath?: string;
            visibility: string;
            writable: boolean;
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        Member: {
            /** Format: date-time */
            addedAt: string;
            /** Format: uuid */
            id: string;
            role: string;
            username: string;
        };
        MemberList: {
            members: components["schemas"]["Member"][];
        };
        Scan: {
            booksAdded: number;
            error?: string;
            filesAdded: number;
            filesChanged: number;
            filesMissing: number;
            filesMoved: number;
            filesRestored: number;
            filesSeen: number;
            filesSkipped: number;
            /** Format: date-time */
            finishedAt?: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            libraryId: string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            startedAt?: string;
            state: string;
        };
        SetupRequest: {
            email?: string;
            password: string;
            username: string;
        };
        SetupStatus: {
            needed: boolean;
        };
        UpdateLibraryRequest: {
            name?: string;
            visibility?: string;
            writable?: boolean;
        };
        User: {
            email?: string;
            /** Format: uuid */
            id: string;
            role: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listBooks: {
        parameters: {
            query?: {
                /** @description A library's ID; left out, every library the caller may see. */
                library?: string;
                /** @description What the books are ordered by; title when left out. */
                sort?: "title" | "author" | "added";
                /** @description The direction; asc when left out. */
                order?: "asc" | "desc";
                /** @description The nextCursor of the page before. */
                cursor?: string;
                /** @description How many books a page holds, at most 200; 50 when left out. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookList"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getBookCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
                size: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listLibraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryList"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLibraryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deleteLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    updateLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLibraryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryResponse"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listLibraryMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    addLibraryMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    removeLibraryMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    scanLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    completeSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildInfo"];
                };
            };
            /** @description The request failed. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
