// Package db opens the database, brings its schema up to date and runs
// transactions. The queries themselves are generated by sqlc into the sqlc
// subpackage from the files in backend/queries.
package db

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
	"github.com/pressly/goose/v3/lock"

	"github.com/praetorianer777/gotome/backend/migrations"
)

// The app container may start alongside Postgres rather than after it, so
// Open waits this long for the database before giving up.
const (
	connectAttempts = 30
	connectPause    = time.Second
	connectTimeout  = 3 * time.Second
)

// Open connects to the database, waiting for it to accept connections.
func Open(ctx context.Context, url string, log *slog.Logger) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(url)
	if err != nil {
		// pgx quotes the URL in its error, password included.
		return nil, errors.New("GOTOME_DATABASE_URL is not a valid Postgres URL, such as postgres://gotome:secret@db:5432/gotome")
	}
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("database pool: %w", err)
	}

	var lastErr error
	for attempt := 1; attempt <= connectAttempts; attempt++ {
		pingCtx, cancel := context.WithTimeout(ctx, connectTimeout)
		lastErr = pool.Ping(pingCtx)
		cancel()
		if lastErr == nil {
			return pool, nil
		}
		log.Info("waiting for the database", "attempt", attempt, "error", lastErr)
		select {
		case <-ctx.Done():
			pool.Close()
			return nil, ctx.Err()
		case <-time.After(connectPause):
		}
	}
	pool.Close()
	return nil, fmt.Errorf("the database did not answer after %d attempts: %w", connectAttempts, lastErr)
}

// Migrate applies every migration the database has not seen and returns how
// many that were. It holds a Postgres advisory lock while it works, so two
// processes starting together apply each migration once, one after the other.
func Migrate(ctx context.Context, pool *pgxpool.Pool) (applied int, err error) {
	sqlDB := stdlib.OpenDBFromPool(pool)
	defer sqlDB.Close()

	locker, err := lock.NewPostgresSessionLocker()
	if err != nil {
		return 0, fmt.Errorf("migration lock: %w", err)
	}
	provider, err := goose.NewProvider(goose.DialectPostgres, sqlDB, migrations.FS,
		goose.WithSessionLocker(locker),
		// Branches merge in any order, so a lower number may arrive after a
		// higher one is already applied.
		goose.WithAllowOutofOrder(true),
	)
	if err != nil {
		return 0, fmt.Errorf("migrations: %w", err)
	}
	results, err := provider.Up(ctx)
	if err != nil {
		return len(results), fmt.Errorf("migrate: %w", err)
	}
	return len(results), nil
}

// SchemaVersion is the highest migration applied.
func SchemaVersion(ctx context.Context, pool *pgxpool.Pool) (int64, error) {
	sqlDB := stdlib.OpenDBFromPool(pool)
	defer sqlDB.Close()
	provider, err := goose.NewProvider(goose.DialectPostgres, sqlDB, migrations.FS)
	if err != nil {
		return 0, err
	}
	return provider.GetDBVersion(ctx)
}

// InTx runs fn in a transaction: committed when fn returns nil, rolled back
// when it returns an error or panics.
func InTx(ctx context.Context, pool *pgxpool.Pool, fn func(tx pgx.Tx) error) error {
	tx, err := pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin: %w", err)
	}
	// After a commit this is a no-op; before one it is what a panic or an
	// early return leaves to be undone. The request's context may already be
	// cancelled by then, and the rollback must still reach the server.
	defer func() { _ = tx.Rollback(context.WithoutCancel(ctx)) }()

	if err := fn(tx); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit: %w", err)
	}
	return nil
}
